### ISSUE TITLE
How to implement optional values?

### ISSUE THREAD

**Issue by tomitrescak** [xaviergonz/mobx-keystone#10]
I have a following store, where `message` is only optional:

```ts
@model('geodas/Modal')
export class ModalStore extends Model({
  message: tProp(types.model<ModalMessage | null>(ModalMessage), null)
}) {}
```

when I initialise this store `new ModalStore()` I receive an error that the message is not of type `ModalMessage`.

Is there any way how to do this?

**Comment by sisp** [comment]
Without having tried it, does `new ModalMessage({})` work?

**Comment by terrysahaidak** [comment]
The problem here is with `types.model`. It should be a model class, not `Model | null`. In order to use `null`, you need to use `maybeNull` like here:

```ts
@model('geodas/Modal')
export class ModalStore extends Model({
  message: tProp(types.maybeNull(types.model<ModalMessage>(ModalMessage)), null)
}) {}
```

**Comment by tomitrescak** [comment]
@terrysahaidak thats what I was after thanks! I did not see that type ...
