### ISSUE TITLE
applySnapshot messes with onAttachedToRootStore

### ISSUE THREAD

**Issue by martinheidegger** [xaviergonz/mobx-keystone#103]
_This might be related to #27._

### / Short
Last night I tried to figure out why I got following execution order:

`.onAttachedToRootStore`
`.onAttachedToRootStore`
`(detachMethod)`

and it seems that `applySnapshot` will mess with the onAttachedToRootStore hooks.
I worked around it by only counting how many calls to either are made and only execute `onAttached...` the first time and only execute `detach` once its called at an equal amount as the `onAttached..` amount. But it would be nice if it would be executed in order.

### / Long

In my code I have a [`User` Model](https://github.com/consento-org/mobile/blob/12568714816480060a091e50f58d390df8266c6a/src/model/User.ts#L38) that is restored/persisted in [the `.onAttachedToRootStore` hook](https://github.com/consento-org/mobile/blob/12568714816480060a091e50f58d390df8266c6a/src/model/User.ts#L45). When the app is started, the user is [created and attached to the rootStore](https://github.com/consento-org/mobile/blob/12568714816480060a091e50f58d390df8266c6a/src/ConsentoApp.tsx#L21-L28). Once all data is loaded [`.applySnapshot` is called](https://github.com/consento-org/mobile/blob/12568714816480060a091e50f58d390df8266c6a/src/util/mobxPersist.ts#L72) to restore the user. There is also a [`Vault`](https://github.com/consento-org/mobile/blob/12568714816480060a091e50f58d390df8266c6a/src/model/Vault.ts#L54) child of `User` that will be restored with the user.
There is also a [`VaultData` model](https://github.com/consento-org/mobile/blob/12568714816480060a091e50f58d390df8266c6a/src/model/VaultData.ts#L55-L60) that is to be restored/replicated from a different physical location when [attached to the root store](https://github.com/consento-org/mobile/blob/12568714816480060a091e50f58d390df8266c6a/src/model/VaultData.ts#L74). The `VaultData` is conceptually linked `Vault` as [`Vault.dataKeyHex`](https://github.com/consento-org/mobile/blob/12568714816480060a091e50f58d390df8266c6a/src/model/Vault.ts#L58) contains the storage location of the VaultData. So: once there is a new Vault, I need to also create/restore the  `VaultData` with it. In a previous version I tried using [`onInit`](https://github.com/consento-org/mobile/blob/6851d56a54879e4e36c1d071a2ebf003411d7a2e/src/model/Vault.ts#L81) to [restore the data](https://github.com/consento-org/mobile/blob/6851d56a54879e4e36c1d071a2ebf003411d7a2e/src/model/Vault.ts#L124). (_more about the current version later_). It worked somehow but I noticed that the `VaultData.onAttachedToRootStore` method was called more than once, screwing with my restore logic _(the store was restored twice)_. I attempted to make sure that in it can be destructed at any time and still I ran into weird states.

_... so i tried to debug mobx-keystone..._

I figured out that both `onAttachedToRootStore` calls are triggered by this block:

https://github.com/xaviergonz/mobx-keystone/blob/93103c520c35fa1a97eba4fa256305d664db9a75/packages/lib/src/parent/setParent.ts#L112-L119

where the listener execution is added to a queue, which is filled twice for the same object before being executed with applySnapshot. I noticed that when executing `on...` here

https://github.com/xaviergonz/mobx-keystone/blob/93103c520c35fa1a97eba4fa256305d664db9a75/packages/lib/src/rootStore/attachDetach.ts#L23-L25

before the execution ` onAttachedDisposers.get(ch)` was already defined, causing in an overwrite (and loss) of the previous disposer without it ever being called.

I didn't find a good way for a test yet but I worked around this by storing the `VaultData` in a [separate rootStore](https://github.com/consento-org/mobile/blob/12568714816480060a091e50f58d390df8266c6a/src/model/Vault.ts#L51), [counting how often `.onAttachedToRootStore` is called](https://github.com/consento-org/mobile/blob/master/src/model/Vault.ts#L93) on the Vault and only [running it the first time](https://github.com/consento-org/mobile/blob/12568714816480060a091e50f58d390df8266c6a/src/model/Vault.ts#L94) while [registering the destruction](https://github.com/consento-org/mobile/blob/12568714816480060a091e50f58d390df8266c6a/src/model/Vault.ts#L115-L117) to be called once the [counter is back to 0](https://github.com/consento-org/mobile/blob/12568714816480060a091e50f58d390df8266c6a/src/model/Vault.ts#L123).

Now this workaround somehow does the job, _even if it feels fishy_, but it would be good if `.onAttachedToRootStore` was called only once, or alternatively if the destruct method to be called before the next onAttachedToRootStore call.

**Comment by xaviergonz** [comment]
Seems like a bug, is there any chance you could provide a unit test that exposes the problem though? That'd make it much easier to fix.

**Comment by xaviergonz** [comment]
By the way, are both calls to onAttachedToRootStore made with the same rootStore as parameter or different ones?

**Comment by xaviergonz** [comment]
I just released v0.35.0 with some changes related to this, let me know if it fixes anything

**Comment by martinheidegger** [comment]
It seems to be fixed, but let me test for a little more.

**Comment by xaviergonz** [comment]
@martinheidegger can the issue be closed then?
