### ISSUE TITLE
Map support

### ISSUE THREAD

**Issue by olee** [xaviergonz/mobx-keystone#106]
Are there any plans to support Map as a valid prop type?
I could imagine something like `entities: prop(() => new Map<string, MyEntity>, e => e.id)` where the second argument would define a function to get the key of the item in the map.

If there are no plans to support Map or it's not possible, what would you recommend as alternative?

PS: Also the same could be said about Set.

**Comment by xaviergonz** [comment]
Hi! Maybe this section could be of interest:

https://mobx-keystone.js.org/mapsAndSets

**Comment by olee** [comment]
Ouch.... how couldn't I see this in the docs 😅 
Maybe it should be added to the [error message](https://github.com/xaviergonz/mobx-keystone/blob/master/packages/lib/src/tweaker/tweak.ts#L75) as well and make it `Maps are not supported. Use ObjectMap instead`

**Comment by olee** [comment]
I have a few more questions:

- From what I could read [here](https://mobx-keystone.js.org/references#example-reference-to-multiple-selected-todos), putting a reference into an array and invalidating it, will automatically splice it from the array. Is it possible to achieve the same behavior with object maps as well?
- Is it possible to reach you for smaller questions over something like Gitter, Discord, etc.?

**Comment by xaviergonz** [comment]
> From what I could read here, putting a reference into an array and invalidating it, will automatically splice it from the array. Is it possible to achieve the same behavior with object maps as well?

yep, as long as the reference `onResolvedValueChange` uses detach (since detach supports arrays, objects, as well as objectMap and arraySet), or some custom logic that supports those

> objectMap.map seems to force a second parameter thisArg which breaks compatibility with Map.map and does not look like a required parameter

Care to elaborate with an example? I'm not sure what you mean :-/

> Is it possible to reach you for smaller questions over something like Gitter, Discord, etc.?

See https://github.com/xaviergonz/mobx-keystone/issues/89 :)

**Comment by olee** [comment]
For the second point: Sorry, I meant objectMap.forEach - I updated the post

**Comment by xaviergonz** [comment]
Ah, didn't notice! It will be fixed in v0.36.1
