### ISSUE TITLE
Better error messages on snapshot mismatch

### ISSUE THREAD

**Issue by martinheidegger** [xaviergonz/mobx-keystone#108]
When I try to apply a snapshot for some reason I get an error message stating: 

`snapshot model type 'consento/User' does not match target model type 'consento/User'`

Which is fine as I probably have a mistake somewhere but it would be helpful to know where the mismatch happened as its probably a small issue in the case at hand.

**Comment by xaviergonz** [comment]
this commit should address it: 
https://github.com/xaviergonz/mobx-keystone/commit/5568a3a47e97ca6152f785e48db97068db66f8c4

**Comment by xaviergonz** [comment]
Released as v0.36.2

**Comment by martinheidegger** [comment]
The error doesn't occur anymore in the latest version, I assume the error message is better as well. Closing this issue. Thanks!
