### ISSUE TITLE
Using the library without decorators

### ISSUE THREAD

**Issue by ivandotv** [xaviergonz/mobx-keystone#113]
I'm coming from evaluating typescript version of mobx-MST for a project, and battling with the typescript nuances somehow I'have ended up here (although I have starred this project a long time ago and totally forgot about it) :)
I have a hard **no** from other team members on the usage of decorators in the project (no stable specification and we are using create react app)
Can this library be used without the **decorator** syntax?
If yes, are there any limitations in that scenario? Nothing is mentioned in the documentation.

Also, are there any sample applications that I could take a look at?
Repo for the todo app?

**Comment by xaviergonz** [comment]
Hi, it can be used, but it won't look pretty, and TS won't like it at the moment too much.

I'm thinking of an alternate syntax to skip decorators, but it would look something like this (when using TS)

(note, *this won't work right now*, it is just an idea)

```ts
const Point = model("myApp/point", {
  x: prop<number>(),
  y: prop<number>()
}. props => ({
  setX(val: number) {
    props.x = val
  },
  setY(val: number) {
    props.y = val
  },
  setXY(x: number, y: number) {
    this.setX(x);
    this.setY(y);
  },
  get length() {
    return props.x + props.y;
  },
  // volatile stuff, hooks, etc...
}). {
  setX: modelAction,
  setY: modelAction,
  length: computed
})
```

Btw, it is absolutely possible to use create-react-app with decorators (especially with TS), that's what I actually use.

**Comment by xaviergonz** [comment]
Or maybe something like this:

```ts
const Point = model("myApp/point", 
class extends Model({
  x: prop<number>(),
  y: prop<number>()
}) {
  setX(val: number) {
    props.x = val
  }
  setY(val: number) {
    props.y = val
  }
  setXY(x: number, y: number) {
    this.setX(x);
    this.setY(y);
  }
  get length() {
    return props.x + props.y;
  }
  // volatile stuff, hooks, etc...
}. {
  setX: modelAction,
  setY: modelAction,
  length: computed
})

const point = new Point({x: 10, y: 20})
```

Exploring options...

**Comment by terrysahaidak** [comment]
Won't the first approach get same problems MST has right now? When you have to create multiple actions or views in order to all the defined actions be visible in others actions?

I think the second idea is good because it's got as close to Mobx itself as possible. So people who don't like decorators in mobx will be at home here as well.

**Comment by xaviergonz** [comment]
Just created a PR with the second idea: https://github.com/xaviergonz/mobx-keystone/pull/118
Let me know what you think :)

**Comment by terrysahaidak** [comment]
Changes in that PR looks good to me.

@ivandotv could you test it with some of your code? I don't have right now something I can test with.

Here is a really big app written using mobx-keystone, you can take a look:
https://github.com/consento-org/mobile

**Comment by xaviergonz** [comment]
decoratedModel released as 0.39.0

The relevant docs can be found here:
https://mobx-keystone.js.org/models#usage-without-decorators

It should be pretty straightforward to extrapolate most of the examples in the docs to that pattern I think.

Feel free to close the issue if this addresses your concern :)

> Here is a really big app written using mobx-keystone, you can take a look: https://github.com/consento-org/mobile

Nice! Let me know if you found any DX (developer experience) issues!

**Comment by ivandotv** [comment]
Indeed using decorators makes things a lot easier.
For now, we are going to stick with the vanilla mobx, and structure the app with good old oop patterns. And see how far we can go.

**Comment by terrysahaidak** [comment]
By the way, I've been prototyping and checking some things in js env without decorators and decoratedModel was pretty handy, so indeed it's really useful.
