### ISSUE TITLE
onInit not called when model instance created in class method (Babel only)

### ISSUE THREAD

**Issue by sisp** [xaviergonz/mobx-keystone#122]
I've discovered a Babel-only issue where `onInit` is not called when a model instance is created in a class method. However, when the same class method uses a factory function to create the model instance, it works fine.

I've created a [reproducible example](https://github.com/sisp/mobx-keystone-issue-oninit-babel) using create-react-app. One test case passes and one fails, but both should pass.

The same test cases pass without error when added to the `mobx-keystone` test suite.

**Comment by xaviergonz** [comment]
The repo shows as empty to me :(

**Comment by sisp** [comment]
Sorry, it's available now.

**Comment by xaviergonz** [comment]
Seems to be a bug with the babel decorator plugin :(

https://github.com/babel/babel/issues/11131

**Comment by sisp** [comment]
Thanks a lot for getting to the bottom of the issue and opening and issue in the Babel repository!

So what are the current options right now? If the decorator plugin receives a fix, I guess create-react-app still needs to bump the Babel version to receive the fix which may take some time. I could stick with the unnecessary factory function. Are there other options?

**Comment by xaviergonz** [comment]
Only the recent decoratedModel comes to mind (maybe) :(
It only happens when using the class within the class itself though. Cross-classes should be ok.

**Comment by sisp** [comment]
Such a weird bug ... I only discovered it because some of my models have a `clone` method which creates a new instance of the same class with clones of its props. The logic for this kind of `clone` probably only makes sense in a class method. I like the decorator approach as it keeps the code clean and readable.

I guess I'll stick to the factory function workaround until Babel has fixed this bug and CRA has updated its dependencies.

**Comment by xaviergonz** [comment]
btw if babel fixes it and you use yarn then you don't need to wait for CRA to update the package version, you can use yarn resolutions to force it

```
"resolutions": {
  "some package": "forced version
}
```

**Comment by xaviergonz** [comment]
There's a slightly better workaround, but still meh-ish

```ts
@model(...)
class A {
  foo() {
    return new _A(...);
  }
}
const _A = A
```

**Comment by sisp** [comment]
Thanks! That's the workaround I'll use. I think it's the least awkward.

Should we close this issue? As it turns out, this is not a `mobx-keystone` issue.

**Comment by xaviergonz** [comment]
Sounds good

**Comment by aboyer1013** [comment]
As an alternative, do you see anything wrong with calling `onInit()` manually?

```typescript
static create(modelData: any) {
    const result = new MyModel(modelData);
    result.onInit();
    return result;
  }
```

**Comment by xaviergonz** [comment]
I'd use the workaround on the post above. something else might be broken if you create a new instance of the undecorated class
