### ISSUE TITLE
instantiate model class when to assign in modelAction

### ISSUE THREAD

**Issue by misaeldossantos** [xaviergonz/mobx-keystone#127]
When I try to assign a js object to an attribute of the model, the object is not instantiated, so when I try to call a method, an exception is raised because it does not exist.

Ex.: 
<pre lang="js"><code>
@model("todo")
class Todo extends Model({
  name: prop<string>("")
}) {
  @modelAction
  setName(name) {
    this.name = name;
  }
}

@model("todos")
class Todos extends Model({
todos: prop<Todo[]>(() => [])
}) {

   @modelAction
   fill() {
       this.todos = [{name: 'test 1'}, {name: 'test 2'}]
   }
}

const todos = new Todos({})
todos.fill()
todos.todos[0].setName("name changed")
</code>
</pre>

it raise this error:
TypeError: todos.todos[0].setName is not a function
because class was not instantiate.
But if I do: 
this.todos = [new Todo({name: 'test 1'}), new Todo({name: 'test 2'})]
works.

It is too bad, because deep attrs (with array) is hard to instantiate manually, 
especially after calling an api...

**Comment by xaviergonz** [comment]
```
this.todos = [{name: 'test 1'}, {name: 'test 2'}]
```
I assume you want the todos array to be an array of Todo instances, so you'd need to do
```
this.todos = [new Todo({name: 'test 1'}), new Todo({name: 'test 2'})]

// or
this.todos = [{name: 'test 1'}, {name: 'test 2'}].map(data => new Todo(data))
```

**Comment by misaelbs** [comment]
No plains to add this feature?

**Comment by xaviergonz** [comment]
In order to implement it the use of tProp then would need to be required (so it actually knows what kind of model the array is made of). You can see https://github.com/xaviergonz/mobx-keystone/issues/123 for more details
