### ISSUE TITLE
Poll: Allow changes to any objects/arrays without requiring a model action? (would require proxy)

### ISSUE THREAD

**Issue by xaviergonz** [xaviergonz/mobx-keystone#130]
Right now, after this PR is merged (https://github.com/xaviergonz/mobx-keystone/pull/129) it will be possible to create automatic setters, but it won't work for sub-object / sub-array changes, e.g.:

```ts
@model(...)
class M extends Model({
  x: prop(0, {setterAction: true}),
  arr: prop<number[]>(() => [], {setterAction: true})
}) {}

const m = new M({})

m.x = 10 // works
m.$.x = 10 // will throw, not using modelAction
m.arr = [10] // works
m.$.arr = [10] // will throw, not using modelAction
m.arr.push(10)  // will throw, not using modelAction
```

Would you want it so simple changes to model props / objects / arrays don't require changes to be wrapped in modelAction at all?

e.g.

```ts
@model(...)
class M extends Model({
  x: prop(0),
  arr: prop<number[]>(() => [])
}) {}

const m = new M({})

m.x = 10 // works
m.$.x = 10 // works
m.arr = [10] // works
m.$.arr = [10] // works
m.arr.push(10) // works
```

It would require Proxy to work though, but  since Hermes 0.4.0 will include support for Proxy (https://github.com/facebook/hermes/releases/tag/v0.4.0) I think it wouldn't be too bad

What do you think? Worth it?

**Comment by xaviergonz** [comment]
@terrysahaidak @sisp

**Comment by terrysahaidak** [comment]
I'm not sure about this. Yes, this might be pretty handy in some cases, but still requiring an action forces you to "document" your intent by at least giving a name to the action instead of just changing some random nested props.

I would at least leave the default – requiring an action, but you may turn in off somehow.

The only case where I use – to run it from the thunk/flow (async action, and you need to update something after the an `await` thing). I used to have mobx based class with some internal states such as inProgress, isError, etc, to reduce some boilerplate.

```ts
@model('GroupList')
export class GroupList extends Model({
  list: prop<Ref<GroupModel>[]>(() => []),
}) {
  @thunk() fetch = createThunk(
    (id: number) =>
      // it binds the context under the hood
      async function(this: GroupList, flow) {
        const groups = await Api.Groups.getAll();
        // uses runUnprotected under the hood
        flow.update(() => {
          this.list = groups.map((item) => GroupModel.ref(item.id));
        });
      },
  );

  @modelAction
  remove(group: GroupModel) {
    const index = this.list.findIndex((ref) => ref.current === group);

    if (index > -1) {
      this.list.splice(index);
    }
  }
}
```

But still, I just think freedom isn't always what the user needs.

**Comment by sisp** [comment]
> I'm not sure about this. Yes, this might be pretty handy in some cases, but still requiring an action forces you to "document" your intent by at least giving a name to the action instead of just changing some random nested props.

I agree. The "documentation" aspect of actions is a good way in my opinion to improve code structure. I currently don't need this feature, but it doesn't mean nobody else has good use cases for it.

> It would require Proxy to work though, but since Hermes 0.4.0 will include support for Proxy (https://github.com/facebook/hermes/releases/tag/v0.4.0) I think it wouldn't be too bad

Personally, I'm not too concerned about Proxy support as common (modern) browsers support it. But it depends on the target group, some still rely on ancient browsers and if you're developing for those that's a problem. I think it would be more consistent if changes to arrays and objects were covered by the implicit setter action, too. Would [this polyfill](https://github.com/GoogleChrome/proxy-polyfill) work, so also older browsers are supported?

**Comment by xaviergonz** [comment]
> I think it would be more consistent if changes to arrays and objects were covered by the implicit setter action, too. 

That's what I was thinking.
Maybe another option would be to mark those objects/arrays as "unprotected" so they are differentiated from setting the actual property itself. e.g.

```ts
class M extends Model({
  arr: prop<number[]>(() => [], {unprotected: true})
}) {}

m.arr.push(5) // would work since the array is unprotected
m.arr = [5] // would not work, since there's no setterAction: true
``` 

However, it poses the problem: how deep should this unprotection go? What if it is an array of arrays? Or an object where one property is an array? Should the unprotection just go deep until/if a model is hit?

All these questions were what made me think that maybe make it all unprotected globally would make it an easier concept to grasp, but it is true that there's a merit to just have all mutations go through specific model actions.

Either way, I think the biggest boilerplate source are the setters for individual properties, which should be addressed by the setterAction PR without any Proxy requirements / API changes, so probably that's good enough for now :)

Thanks for the input!

> Would this polyfill work, so also older browsers are supported?

The polyfill wouldn't work to set/delete unknown object props/array indexes, so it would need to be a real Proxy implementation to support all cases :(

**Comment by Sladav** [comment]
If this would add a hard dependency on Proxies, then it would force me to stop using the library 😢 

We HAVE to support older browsers and are currently doing so by using Mobx 4 (no Proxy) and polyfilling.

I understand if it's determined necessary for a better library, but man, I'd be so disappointed if I couldn't use it anymore.

**Comment by xaviergonz** [comment]
Dropping the idea since in the end the new automatic setters generate a named `setX` function (plus no-proxy compat is staying for now)
