### ISSUE TITLE
a reference of type 'myapp/MyModel' could not resolve an object with id 

### ISSUE THREAD

**Issue by farism** [xaviergonz/mobx-keystone#133]
repro here 

https://codesandbox.io/s/broken-refs-3undv

add some items with plus button, select an item by clicking it (ref used to determine active selection) and then try removing with the minus button.

**Comment by martinheidegger** [comment]
The problem occurs in the removal process. When you remove an item, the reference to it still exists and on re-rendering it will look for the selected item which is gone at that moment.

Here would be an "ugly" fix:
https://codesandbox.io/s/broken-refs-f4vp7

It may be better to use "maybeCurrent" for the selectedItem:
https://codesandbox.io/s/broken-refs-b0iz2

**Comment by farism** [comment]
Oh I see, it looks like I missed this section in the docs, it looks like `maybeCurrent` is the correct solution

```
Reference objects can then be created using myRef(target: T) or myRef(id: string) and offer the following properties:

isValid - If the reference is valid (can be currently resolved).
current - The object this reference points to, or throws if invalid.
maybeCurrent - The object this reference points to, or undefined if invalid.
```

I read this part in the docs

`
The good thing is that whenever a todo is removed from the list and it was the selected one, then the selectedTodo property will automatically become undefined.
`

I assumed this would be handled for me but I just didn't read carefully enough 😅

**Comment by martinheidegger** [comment]
I opened #134 to make this a bit nicer, but it may be a good idea to improve the documentation to fix this issue. Do you have an idea how the documentation may be better?

**Comment by farism** [comment]
I think the documentation is pretty clear, I was just being too hasty.

Might be worth mentioning the usage of `.maybeCurrent` in a comment in the single selected todo example. 

```
// not strictly needed, but neat
  @computed
  get selectedTodo() {
    // or this.selectedRef.maybeCurrent
    return this.selectedRef ? this.selectedRef.current : undefined
  }
```

Or perhaps change the example to use `.maybeCurrent` by default since it doesn't throw, and instead  leave a comment about using `.current`?

```
// not strictly needed, but neat
  @computed
  get selectedTodo() {
    // or this.selectedRef.current to handle errors
    return this.selectedRef ? this.selectedRef.maybeCurrent : undefined
  }
```

But maybe unnecessary. Feel free to close this too.

**Comment by xaviergonz** [comment]
In the case of the todo example it doesn´t use maybeCurrent since (in theory) this.selectedRef will automatically become undefined if the referenced object dissapears (therefore maybeCurrent will never get to be null)
