### ISSUE TITLE
Where is the best place to store references to Dom elements or other non-serializable objects?

### ISSUE THREAD

**Issue by kingpalethe** [xaviergonz/mobx-keystone#135]
Thanks for this great library which we are digging into as a more typescript-first approach to Mobx State Tree.

One extremely useful detail in the Mobx State Tree documentation is this page  https://mobx-state-tree.js.org/concepts/volatiles  .. where we read:

> ...  sometimes you need to keep track of temporary, non-persistable state. This is called volatile state in MST. Examples include promises, sockets, DOM elements, etc. - state which is needed for local purposes as long as the object is alive......

In a previous project, we had a lot of success using `model.volatile` to store lots of different kinds of objects, including graphics objects like a for example a [canvas](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API) element on a web page.

I am finding myself wishing that the Mobx Keystone documentation was a little bit more prescriptive about this, and really tell us what part of a model should be used for this kind of state. 

I've found two parts of the documentation that seem really close, this:

> root stores can be also an alternative to store contextual/environmental volatile data that doesn't really need to be serialized anywhere.

https://github.com/xaviergonz/mobx-keystone/blob/0c8b337f351ef363cd0345334b2ac990b8bb4f72/packages/site/src/rootStores.mdx#sharing-contextual-data

... and this:

https://mobx-keystone.js.org/classModels#runtime-data

> Runtime data (data that doesn't need to be snapshotable, or that needs to be tracked in any way) can be declared as a usual property. Nothing special is needed.

Can anyone suggest if it really doesn't matter, if either of these strategies could be used?

thanks

**Comment by xaviergonz** [comment]
Runtime data is the place for that. Now if it should be on the root model or on a submodel is up to your application structure really.

Just clarified the docs about the root store to try to make it a bit more clear:

> Although usually contexts are preferred for this case (see the [contexts](./contexts) section), root stores can be also an alternative to store global contextual/environmental runtime data that doesn't really need to be serialized anywhere yet need to be shared across the whole application.
