### ISSUE TITLE
How To Contribute Financially To Mobx Keystone?

### ISSUE THREAD

**Issue by kingpalethe** [xaviergonz/mobx-keystone#137]
Either on this respository, or on https://mobx-keystone.js.org/, I don't see an obvious method of contributing funds for development.

**Comment by xaviergonz** [comment]
Hey, thanks for the offering, but right now I'm not looking for financial contributions :) However if you can contribute by creating PRs to improve the docs, add / suggest features, etc that´d be great :D

**Comment by martinheidegger** [comment]
@kingpalethe you can also sponsor the writing of an article around mobx-keystone ;-)
