### ISSUE TITLE
How To Split Mobx Keystone Models Across Multiple Files?

### ISSUE THREAD

**Issue by kingpalethe** [xaviergonz/mobx-keystone#138]
A challenge we had with Mobx State Tree was that our model files grew too big, with too many `actions` and `views` per javascript file. We were able to solve this by using the pattern suggested in this StackOverflow thread:

https://stackoverflow.com/questions/54080332/how-to-split-mobx-state-tree-models-across-multiple-files

Mobx State Tree allows for the chaining of `actions` and `views`, and with the pattern provided by @luisherranz in the answer to that question, we were able to solve this problem in a simple and straightforward way. 

Can anyone suggest a pattern for Mobx Keystone that will solve the same issue? I do see that there is an example for model inheritance, like this https://mobx-keystone.js.org/classModels#inheritance -- but I don't think we should need to go there... we just need a sane way to split code for a model across multiple files.

thanks

**Comment by xaviergonz** [comment]
Are you looking for a solution using TS or just plain JS?

**Comment by kingpalethe** [comment]
Thanks -- We are using TS, so theoretically TS would be best, but generally whatever would be easiest to understand or require the least boilerplate, or some combination of those...... I have looked at these solutions --  https://stackoverflow.com/questions/23876782/how-do-i-split-a-typescript-class-into-multiple-files   ...but they seem unpleasant compared to what Mobx State Tree allowed for, and I'm still not really sure they would work with Mobx Keystone.....

**Comment by mikecann** [comment]
I guess you could make "extension methods" for your class like this:

```typescript
import { Model, model, prop, modelAction, rootRef, Ref } from "mobx-keystone";

@model("MyModel")
export class MyModel extends Model({
  text: prop("foo")
}) {
  concat = myExtensionMethod(this)
} 

const myExtensionMethod = (model: MyModel) => (someProp: string) => model.text + someProp;

const myModel = new MyModel({});

console.log(myModel.concat("bar")) // prints "foobar"
```

**Comment by xaviergonz** [comment]
https://stackoverflow.com/questions/23876782/how-do-i-split-a-typescript-class-into-multiple-files

closing since this is really a TS topic
