### ISSUE TITLE
actionAsync from mobx-utils  instead modelFlow

### ISSUE THREAD

**Issue by swayf** [xaviergonz/mobx-keystone#140]
Can **asyncAction** from **mobx-utils**  be used just instead **modelFlow**?? =) or **modelFlow** still has something specific for the **mobx-keystone**?

**Comment by xaviergonz** [comment]
I'm afraid it can't (also I think asyncAction is actually deprecated in favor of flow / actionAsync IIRC?)

**Comment by swayf** [comment]
oops.. sorry.. I mean actionAsync (with async/await)
