### ISSUE TITLE
Congrats on this project!

### ISSUE THREAD

**Issue by robclouth** [xaviergonz/mobx-keystone#146]
I know this isn't really an issue, but I'm absolutely loving this project. It's taken all the best bits from mobx and mobx-state-tree and put them into a single package that's a joy to work with. You've literally thought of everything!
That's all, thanks.

**Comment by robclouth** [comment]
The only issue is that now I'll have to refactor my old projects into mobx-keystone...

**Comment by xaviergonz** [comment]
Much appreciated! 😁
