### ISSUE TITLE
Partial snapshots

### ISSUE THREAD

**Issue by robclouth** [xaviergonz/mobx-keystone#149]
It seems like the current behaviour of ```applySnapshot``` removes properties in the target that aren't present in the snapshot. It would be handy to be able to partially update a model from a partial snapshot.

E.g. if the model is
``` 
{
   x: 1,
   y: 1
}
```
and the json is 
```
{
   x: 2
}
```
then the model after is 
``` 
{
   x: 2,
   y: 1
}
```

**Comment by xaviergonz** [comment]
Yep, that's by design.

Maybe what you want to do is this?

```ts
applySnapshot(obj, {
  ...getSnapshot(obj),
  ...partialSnapshot
})
```

**Comment by robclouth** [comment]
Yup, that's an extremely easy way of doing it that I should have noticed.
It's been a long day... thanks
