### ISSUE TITLE
Autorun not triggered for prop

### ISSUE THREAD

**Issue by robclouth** [xaviergonz/mobx-keystone#151]
```
@model("Test")
export default class Test extends Model({
  test: prop(0, { setterAction: true })
}) {
  onInit() {
    setInterval(() => (this.test += 1), 1000);
    autorun(() => console.log(this.test));
  }
}
```
Why isn't the autorun working?

**Comment by xaviergonz** [comment]
It seems working for me

https://stackblitz.com/edit/typescript-39gr9j

maybe you forgot to do a "new Test({})" and therefore onInit didn't get called?

**Comment by robclouth** [comment]
Sorry, just getting back to this now. It seems to be that onInit isn't called when restoring from a snapshot. How can I get around this?

https://stackblitz.com/edit/typescript-xrf4ed?file=index.ts

**Comment by robclouth** [comment]
It's working fine, I got confused about when onInit is called
