### ISSUE TITLE
Assignment best practices?

### ISSUE THREAD

**Issue by mikecann** [xaviergonz/mobx-keystone#170]
Apologies for so many issues, this one is more of a discussion on best practices tho.

I keep running into issues like this when trying to model my game using Keystone:

```typescript
import { model, Model, prop, modelAction } from "mobx-keystone";
import { Point2D } from "../src/model/geometry/point2D";

interface Position {
  x: number;
  y: number;
}

@model("TestModel")
class TestModel extends Model({
  position: prop<Position>(),
}) {
  @modelAction
  applyEvent(event: { position: Point2D }) {
    this.position = event.position;
  }
}

test(``, () => {
  const modelA = new TestModel({ position: { x: 3, y: 3 } });
  const modelB = new TestModel({ position: { x: 0, y: 0 } });

  // The below throws an error "an object cannot be assigned a new parent when it already has one"
  modelB.applyEvent({ position: modelA.position });
});

```

Now this error is thrown because `position` has been converted into an observable and has been parented under modelA and so errors when it assigned in modelB.

I keep running into issues like this, and im not 100% sure what to do about it.

I guess this is a mutable / immutable issue? Maybe I could somehow flag postion as immutable and so the above would work?

**Comment by xaviergonz** [comment]
Basically what happens is this:

```const modelA = new TestModel({ position: { x: 3, y: 3 } });```
modelA tree now "owns" the object (now a tree node)  PA ```{ x: 3, y: 3}```

``` const modelB = new TestModel({ position: { x: 0, y: 0 } });```
modlB tree now "owns" the object (now tree node) PB ```{ x: 0, y: 0 }```

```modelB.applyEvent({ position: modelA.position });```
now you try to move into the modelA tree the object (tree node) PB, but that node is already attached to model B and a same tree node cannot be attached to two different trees at the same time (therefore the error).

There are some ways to avoid this:
1) cloning the object before passing it to the action (either using clone (only for tree nodes)) from mobx-keystone or the usual js shallow clone ```{ ...point }```)
2) cloning inside the action itself

**Comment by mikecann** [comment]
Yep pretty much what I thought. 

Okay thanks!

**Comment by airtonix** [comment]
> There are some ways to avoid this:
> 
>     1. cloning the object before passing it to the action (either using clone (only for tree nodes)) from mobx-keystone or the usual js shallow clone `{ ...point }`)
> 
>     2. cloning inside the action itself

I'm also running into this, just to gain some clarity into the suggestion you made @xaviergonz;
- are you suggesting this because PA and PB are not models? 
- if they were models would you instead suggest that references be used?
