### ISSUE TITLE
Better type checking on model constructor

### ISSUE THREAD

**Issue by Amareis** [xaviergonz/mobx-keystone#178]
https://codesandbox.io/s/mobx-keystone-typings-yo2rs?file=/src/index.tsx:0-179

Currently there no ts error if some object with exta fields is passed to model constructor, but there is runtime error, which even don't report about these extra fields. It's not really good when model created with some external type (such as server data), I spent hour, trying to understand about it.

**Comment by Amareis** [comment]
There is some tricks to do so https://fettblog.eu/typescript-match-the-exact-object-shape/
But it's not working with keystone, because `ModelInstanceCreationData<Mod>` has no exact shape.

**Comment by xaviergonz** [comment]
Blame typescript :/

```ts
function f(data: { value: number }) { }

const tt = { value: 0, a: 1 }
f(tt) // ok

f({value: 0, a: 1}) // error, a should not be there
```

same happens if you use new with an object vs new with a literal.
Maybe you could try to type `t`

```ts
const t: SnapshotInOf<Mod> = { value: 0, a: 1 }; // a should not be there
new Mod(t); //runtime error
```

Edit: Thanks for the heads up, I'll check the article and see if I can use that :D

**Comment by Amareis** [comment]
I think the runtime error should be more specific, for pure js users it will be helpful.

Also maybe there is some ts trick to make compilation error more detailed (not just turn arg into `never`). I try to dig into it.

**Comment by Amareis** [comment]
>Maybe you could try to type t

It's not really working for me, actually, in WebStorm:
```ts
const m: ModelInstanceCreationData<Message> = {}  //m has any type
```

**Comment by Amareis** [comment]
If open BaseModel.d.ts in codesandbox, there is ts errors:
```
A computed property name in a class property declaration must refer to an expression whose type is a literal type or a 'unique symbol' type.ts(1166)
Cannot find name 'propsDataTypeSymbol'.ts(2304)
```
![image](https://user-images.githubusercontent.com/4806617/90869095-2fddc100-e3b1-11ea-8a64-c0a71a921a12.png)

**Comment by Amareis** [comment]
Also, in ts 3.9 there is ts-expect-error feature, it can be really good for typings tests!

**Comment by Amareis** [comment]
Thank you!
