### ISSUE TITLE
serializeActionCallArgument could not serialize the given value: [arrow function]

### ISSUE THREAD

**Issue by Amareis** [xaviergonz/mobx-keystone#180]
Hello! I tried to use `onActionMiddleware` + `serializeActionCall` to log our actions as breadcrumbs to sentry. But it seems action call cannot be serialized if action arguments contains a function. Does it possible to replace it with `JSON.stringify` with custom replacer function?

**Comment by xaviergonz** [comment]
You can register your own custom serializers using registerActionCallArgumentSerializer.
Not sure how you plan to serialize / deserialize functions though...

**Comment by Amareis** [comment]
Plain `toString` is good enough for logging puproses, I think. Thank you!
