### ISSUE TITLE
Design best practice for loading "deeply nested" objects

### ISSUE THREAD

**Issue by jeffchuber** [xaviergonz/mobx-keystone#185]
Let's say my state tree is
```
Root
   Teams
       Todos
            TodoNotes
                  TodoNoteFiles
```
With routes to match.
- ` /teams/:teamKey`
- ` /teams/:teamKey/todos/:todoKey` 
- ... etc

What I am trying to figure out is how to "skip load" to a deeper resource: eg - 
- `/todoNoteFiles/:todoNoteFilesKey`

My challenge is that currently my `getter` functions are on the parent resource since that is where the collection is managed... eg
```js
@model('TodoNotes')
export class TodoNote extends Model({
  key: prop(() => uuidv4()), 
  todoNoteFiles: prop<TodoNoteFile[]>(() => []),
}) {
  // actions for getting, adding, deleting, etc...
}
```

I could add a getter function for a `TodoNoteFile` to my `RootStore`... but then I don't have a "place" to put the Mobx Model since the `RootStore` does not directly have `todoNoteFiles`. Having a place is important since I want to use `observable` in my view.

I could add `todoNoteFiles` onto teams as a convenience, but then I risk duplication of Models at different points in my tree if I navigate to a different route. 

Lastly, I've considered having the child resource, `TodoNoteFiles`, know to load in `TodoNotes`, and `Todos` via my graphql request.. but that feels bad too. 

I'm sure there is a best practice here and would love to know how you all have achieved this.

**Comment by jeffchuber** [comment]
Another approach which I just tried and seemed to work well is just to create an ephemeral detached store that is not connected to the `rootStore` for the particular object, in this contrived example `TodoNoteFiles`. Works well, just don't get the benefit of caching but that's not a big deal in my case.

**Comment by xaviergonz** [comment]
I'd say it depends on your design.

If todo note files is tightly coupled with a Todo (e.g. If you delete a todo then it's note files should be deleted as well) then I'd keep the note files as children and then make a computed on any of the parents which is the aggregate array of all children.

If they are independent entities then probably it makes more sense to have the array of note files on the root and then have references from the todo to the note files.

**Comment by jeffchuber** [comment]
References look useful, thanks!
