### ISSUE TITLE
Design pattern recommendations: patches with server response

### ISSUE THREAD

**Issue by jeffchuber** [xaviergonz/mobx-keystone#186]
I'm observing the patch stream from the stores to trigger a syncing engine to save, update, and remove objects on the server. 

For example, I create a `Team` and get instant optimistic addition of that team in the UI, then in the background, send up the request to create that team on the server, and then update the `serverKey` attributes by generating another patch and applying it. Like this:

```js
const newPatch = jsonPatchToPatch(
  { 
    path: "/" + patch.path.join("/"), 
    op: "replace", 
    value: {
      key: newTeam.key
    } 
  }
)
applyPatches(event.target, [newPatch])
```

Obviously this creates *another* patch and then triggers another mutation, ad infinitum. 

One thought is to add an optional attribute on `applyPatches` that enables skipping the `onPatches`/`patchRecorder` listener or adding an additional property on `PatchRecorderEvent` . But I think there is probably a simpler existing solution I'm just not seeing? 

One could also update the object directly, `team.setKey` but if that has a `@modelAction` on it (which it will need to afaik), then it will create a patch as well.

**Comment by xaviergonz** [comment]
Assuming you use `patchRecorder` you could set its `recording` flag to false before using `applyPatches` and once done set it back to true.

PS: I just added a `onPatches` callback to the patchRecorder in case you may need it.

**Comment by xaviergonz** [comment]
Alternatively you could use the `filter` option for patchRecorder to filter out changes to a certain path

**Comment by jeffchuber** [comment]
I ended up with something that works and feels... ok. 

I keep a list of the patches that my server response has created and then check against this list before trigger new server POSTs. 

Hopefully this will be helpful to someone else in the future!
