### ISSUE TITLE
Issue hydrating from localstorage

### ISSUE THREAD

**Issue by jeffchuber** [xaviergonz/mobx-keystone#187]
I'm running into this error while trying to restore a root tree that I have put to localstorage. 

```js
const rootObj = JSON.parse(localStorage.getItem('project_root') || '{}')
rootStore = fromSnapshot<Root>(rootObj)
```

The strange part, is that I don't have any Models with an id attribute. 

My tree structure is roughly flat and uses references for filtering. 
- Root
   - Teams
   - Users (refs teams)
    - Data (refs teams, refs users)

I add this because I suspect perhaps this has to do with references, since I had this hydration working before when I wasnt using refs. Though it could be something else! 

<img width="1204" alt="Screen Shot 2020-10-08 at 11 55 53 PM" src="https://user-images.githubusercontent.com/891664/95541679-eaf20600-09c1-11eb-8915-c903cee87080.png">

Would love any pointers! I'm totally stuck on this!

**Comment by xaviergonz** [comment]
References are certainly serialized as an object with an id field (target object id), $modelType and $modelId

Are you using your own custom references or something premade such as "rootRef"?
If you could show the code of your reference (if custom) and/or the json of a reference / target object that'd help

**Comment by jeffchuber** [comment]
Thanks! 

All my refs are like this:
```js
export const TeamRef = rootRef<Team>('project/Team', {})
export const DatasetRef = rootRef<Dataset>('project/Dataset', {})
```

Here is an example of an abbreviated model file for `Dataset`, that demonstrates how the reference it made to team.
```js
@model('project/Dataset')
export class Dataset extends ExtendedModel(ModelBase, {
  team: prop<Ref<Team> | undefined>(),
}) {
  onInit() {
    this.$modelId = this.key // this is my server key that I want to dedupe on, key is defined on ModelBase
  }

}

export const DatasetRef = rootRef<Dataset>('project/Dataset', {})
```

I can see in the serialized localstorage data, that no `id`s are present anywhere (this is before any datasets have been loaded in, so the list remains empty). I also maintain collection objects for my models... so it's really more like
- Root
  - Teams
     - Team
  - Datasets
     - Dataset

Each of those models looks something like this:
```js
@model('project/CollectionBase')
export class CollectionBase extends Model({
  objects: prop<any[]>(() => []),
}) {
```

and then each collection model inherits

```js
@model('project/Teams')
export class Teams extends ExtendedModel(CollectionBase, {
}) {
 // methods
})
```

Here is an example of a localstorage snapshot
<img width="946" alt="Screen Shot 2020-10-09 at 4 07 34 PM" src="https://user-images.githubusercontent.com/891664/95627088-92664b80-0a49-11eb-8648-efafa66c6ede.png">

***

I wonder if overwriting `ModelIds` is causing an issue...... appreciate the help!

**Comment by xaviergonz** [comment]
The ID project/Dataset seems to be used both by the Dataset model and the DatasetRef. I'm surprised you are not getting at least a warning about it, but try to change one of them.

**Comment by xaviergonz** [comment]
Also I'd inject the new model Id on the constructor object / snapshot object rather than onInit if possible

**Comment by jeffchuber** [comment]
That was it! 🤦 

changing all my references from:
```js
export const DatasetRef = rootRef<Dataset>('serra/Dataset', {})
```

to
```js
export const DatasetRef = rootRef<Dataset>('serra/DatasetRef', {})
```

did the trick. Oof that was a dumb error on my part. 

Thank you @xaviergonz for the help and the great framework :)
