### ISSUE TITLE
customRef is any

### ISSUE THREAD

**Issue by terrysahaidak** [xaviergonz/mobx-keystone#188]
Hi!

I'm on 0.47.0. For some reason, customRef is any.
I'm using ts 3.7.5. Maybe it's the reason?

![image](https://user-images.githubusercontent.com/7809008/97182235-f5274900-17a4-11eb-922b-8f74b6967fcc.png)

Let me know what info I should provide to debug this issue :) 
Thanks

**Comment by xaviergonz** [comment]
Can you try v0.47.1 and reset the typescript engine?
Which mobx version are you using?

**Comment by xaviergonz** [comment]
Closing for now. Feel free to reopen if it is still an issue!
