### ISSUE TITLE
Does not work with Snowpack

### ISSUE THREAD

**Issue by dodas** [xaviergonz/mobx-keystone#198]
Hey there!

After upgrading to `0.48.1`, `mobx-keystone` stopped working with Snowpack with error:
`ReferenceError: require is not defined`

Here is a explanation of why this happens: https://github.com/snowpackjs/snowpack/discussions/1321
Offending line:
https://github.com/xaviergonz/mobx-keystone/blob/master/packages/lib/src/utils/index.ts#L12

**Comment by xaviergonz** [comment]
Could you check the just released v0.48.3?

**Comment by dodas** [comment]
It works!
Thanks for a nice quick feedback!

**Comment by xaviergonz** [comment]
No problem 👍
