### ISSUE TITLE
[ undoMiddleware] not possible to group implicit Reference removal actions

### ISSUE THREAD

**Issue by airtonix** [xaviergonz/mobx-keystone#202]
Regarding: https://github.com/xaviergonz/mobx-keystone/issues/150#issuecomment-750711035

Removal of nodes that have back references results in more than one patch, meaning undoManager.undo requires multiple calls to restore a node and its references.

Since the references get removed by virtue of the node not existing any more, would something like wrapping my action that removes the node in a transaction decorator help here?

**Comment by xaviergonz** [comment]
Thanks for reporting, could you try v0.48.4? It should be fixed there.

**Comment by xaviergonz** [comment]
Closing since in theory it is fixed. Feel free to reopen if not
