### ISSUE TITLE
$modelId is missing, but $modelType is created

### ISSUE THREAD

**Issue by gouldingken** [xaviergonz/mobx-keystone#209]
I hate to create an issue without a way to reliably replicate, but I haven't been able to nail down when this happens. It has occurred seemingly randomly a few times now and was hoping someone might be able to shine some light on the issue.

Sometimes when creating data programmatically it seems to omit the $modelId field. The resulting snapshot creates an error when I attempt to load it back in and use applySnapshot.

My current hacky solution to this is to ensure that $modelId always exists on every object with a $modelType before calling applySnapshot - but that feels clunky and seems to defeat the purpose of using $modelId.

Has anyone else experienced this issue? Any suggestions on how to avoid it would be most welcome.

FYI the error message on applySnapshot is as follows (but the issue I'm having is with ids not being created):
"Error: a model snapshot must contain an id key ($modelId), but none was found"

**Comment by xaviergonz** [comment]
Just wondering, are you sure you want to use applySnapshot instead of fromSnapshot to load it back? applySnapshot is usually done to "update" an existing piece of  instantiated data with the contents of a (full or partial) snapshot. fromSnapshot is what would be used when you want to transform a snapshot into live data from scratch.

**Comment by gouldingken** [comment]
@xaviergonz thanks for the feedback. I have been using applySnapshot so that I can keep references to my root store and simply modify the state of that store rather than creating a whole new store. That way, whether I'm loading a new file, using undo/redo or applying a partial patch update, it all just works the same.

Maybe I have the wrong approach. I have noticed that using applySnapshot with the full snapshot fails, but applying snapshots to each member works. I usually have a top level applySnapshot on my class like this:
```js
    @modelAction
    applySnapshot(snapshot: any) {
        //NOTE: using applySnapshot directly on AppState doesn't seem to work because of mismatched IDs when applying a saved one to a newly created one...
        if (snapshot.departments) this.departments = fromSnapshot<DepartmentData[]>(snapshot.departments);
        if (snapshot.scenarios) this.scenarios = fromSnapshot<SpaceModelScenario[]>(snapshot.scenarios);
        if (snapshot.assumptions) this.assumptions = fromSnapshot<Assumptions>(snapshot.assumptions);
        if (snapshot.rooms) this.rooms = fromSnapshot<RoomData[]>(snapshot.rooms);
    }
```

**Comment by xaviergonz** [comment]
did you try using applySnapshot over the full model, but ensuring the snapshot $modelId and the model one are the same?

**Comment by xaviergonz** [comment]
Closing due to lack of feedback. Please reopen if needed.
