### ISSUE TITLE
undoManager grouping

### ISSUE THREAD

**Issue by sisp** [xaviergonz/mobx-keystone#214]
Currently, a MobX reaction is triggered when the output of the reference resolver changes. The callback function of this reaction (a) [updates the set of back-references](https://github.com/xaviergonz/mobx-keystone/blob/d0e7c225d94e09bf59405ff6c79c9d7be39d8d5a/packages/lib/src/ref/core.ts#L75) and (b) [calls the `onResolvedValueChange` callback](https://github.com/xaviergonz/mobx-keystone/blob/d0e7c225d94e09bf59405ff6c79c9d7be39d8d5a/packages/lib/src/ref/core.ts#L78) which is often used to detach the reference node when the reference cannot be resolved anymore.

I have a situation in which an action changes the state that leads to a change in back-references and/or detachment of the reference node, and I need those changes to be available within the action (immediately after the change that triggers those side-effects). Unfortunately, this is not possible at the moment because the MobX `reaction` listener is only called when the outermost transaction has completed. My initial thought was to use MobX `observe` instead of `reaction` because `observe` fires immediately when the observed observable is changed. However, when `observe` observes a computed value ([like in this case `this.maybeCurrent`](https://github.com/xaviergonz/mobx-keystone/blob/d0e7c225d94e09bf59405ff6c79c9d7be39d8d5a/packages/lib/src/ref/core.ts#L67)), [internally MobX `autorun` is used](https://github.com/mobxjs/mobx/blob/248e25e37af31c2e71ff452bc662a85816fa40d8/packages/mobx/src/core/computedvalue.ts#L264-L281) which uses the same reaction implementation as `reaction` under the hood.

Can you think of any way to run the side-effects immediately within an action/transaction when the output of the reference resolver changes?

These are tests that demonstrate the behavior I would like to have:

```ts
const aRef = rootRef<A>("aRef", {
  onResolvedValueChange(ref, newValue, oldValue) {
    if (oldValue && !newValue) {
      detach(ref)
    }
  },
})

@model("A")
class A extends Model({}) {}

@model("Root")
class Root extends Model({ a: prop<A | undefined>(), aRefs: prop<Array<Ref<A>>>(() => []) }) {
  @modelAction
  setA(a: A | undefined) {
    this.a = a
  }

  @modelAction
  addRef() {
    expect(this.a).toBeDefined()
    this.aRefs.push(aRef(this.a!))
  }
}

test("backrefs are updated within an action", () => {
  const r = new Root({ a: new A({}) })

  runInAction(() => {
    expect(getRefsResolvingTo(r.a!, aRef).size).toBe(0)
    r.addRef()
    expect(getRefsResolvingTo(r.a!, aRef).size).toBe(1)
  })
})

test("onResolvedValueChange is called within an action", () => {
  const a = new A({})
  const r = new Root({ a, aRefs: [aRef(a)] })

  runInAction(() => {
    expect(r.a).toBeDefined()
    expect(r.aRefs).toHaveLength(1)
    r.setA(undefined)
    expect(r.a).toBeUndefined()
    expect(r.aRefs).toHaveLength(0)
  })
})
```

**Comment by sisp** [comment]
I have submitted a PR to `MobX` which makes `observe` fire eagerly when an observed computed value changes (https://github.com/mobxjs/mobx/pull/2802). Using `observe` with this new behavior instead of `reaction` should let the above tests pass.

**Comment by sisp** [comment]
It seems MobX is unwilling to maintain an eager reaction mechanism in addition to the existing one although I still think that having different behaviors for `observe` when observing state and computed values is inconsistent.

**Comment by sisp** [comment]
A possible solution is to introduce a computed value that retains only resolvable references, e.g.:

```diff
   @model("Root")
-  class Root extends Model({ a: prop<A | undefined>(), aRefs: prop<Array<Ref<A>>>(() => []) }) {
+  class Root extends Model({ a: prop<A | undefined>(), aRefsRaw: prop<Array<Ref<A>>>(() => []) }) {
+    @computed
+    get aRefs() {
+      return this.aRefsRaw.filter(aRef => !!aRef.maybeCurrent)
+    }
+
     @modelAction
     setA(a: A | undefined) {
       this.a = a
@@ -706,7 +711,7 @@ describe("ref reaction", () => {
     @modelAction
     addRef() {
       expect(this.a).toBeDefined()
-      this.aRefs.push(aRef(this.a!))
+      this.aRefsRaw.push(aRef(this.a!))
     }
   }
   
@@ -722,7 +727,7 @@ describe("ref reaction", () => {
   
   test("onResolvedValueChange is called within an action", () => {
     const a = new A({})
-    const r = new Root({ a, aRefs: [aRef(a)] })
+    const r = new Root({ a, aRefsRaw: [aRef(a)] })
   
     runInAction(() => {
       expect(r.a).toBeDefined()
```

It's not perfected though IMHO because the computed property requires knowledge about the `onResolvedValueChange` logic (in this case that the reference node is detached when it can't be resolved anymore which translates to filtering references in the computed property). Also, it doesn't scale as nicely to reference nodes in nested objects (i.e. reference nodes that are not top-level props of a model).

**Comment by xaviergonz** [comment]
> I have a situation in which an action changes the state that leads to a change in back-references and/or detachment of the reference node, and I need those changes to be available within the action (immediately after the change that triggers those side-effects). 

Could you rewrite that as a non-action function that calls two model actions internally?

```ts
@modelAction
before() {
  // do whatever changes to the model that will change the back refs
}

@modelAction
after() {
  // do whatever changes to the model that will use the new back refs
}

doTheThing() {
  this.before()
  // here the back refs shoud be updated (as long as doTheThing is not actually called inside a mobx action
  this.after()
}
```

**Comment by sisp** [comment]
Unfortunately no because I need `doTheThing` to lead to a single undo step, but that currently requires `doTheThing` to be decorated with `@modelAction`. Perhaps if "action" and "undo grouping" were independent decorators, your suggestion could work. Composing actions would still require some care to make sure only methods that directly mutate state are decorated with `@modelAction` and methods that combine several action methods are only decorated with an "undo grouping" decorator. Do you see what I mean?

**Comment by xaviergonz** [comment]
So if the undoManager had a way to group actions outside of it being a model action it would suffice?
If so, would the groups need to support async stuff, or just sync would be good enough?

**Comment by sisp** [comment]
Yes, I think that should suffice. Perhaps an API like this:

```ts
@undoGroup
doTheThing() {
  this.before()
  // here the back refs shoud be updated (as long as doTheThing is not actually called inside a mobx action
  this.after()
}

// AND

doTheThing() {
  undoGroup(() => {
    this.before()
    // here the back refs shoud be updated (as long as doTheThing is not actually called inside a mobx action
    this.after()
  })
}
```

Sync would be enough at least for my use case right now.

**Comment by xaviergonz** [comment]
undoManager.withGroup is now out in 0.52.0
Let's hope that solves your issue :)

**Comment by sisp** [comment]
Looks great, thank you very much! I'll report back once I've confirmed that this solves my issue.

**Comment by sisp** [comment]
`undoManager.withGroup` solves my problem, but there is a minor side-effect: I now wrap only methods that directly change a model prop with `@modelAction` and all other/high-level methods (e.g. those that call several other methods) use a `undoManager.withGroup` block which means for every call to a `@modelAction`-decorated method, reactions will be triggered. That's what I needed for resolving back-references within an undo/redo group, but it also causes the UI to rerender more often. I think it's not a big problem, but I wanted to point it out.

What do you generally think about having reactions that fire immediately upon a change in state or a computed value? The MobX team didn't seem to like having this option and are even unhappy with `observe` which `mobx-keystone` uses for tweaking nodes. In my understanding, `reaction` was never intended to be used for triggering state changes, but I think its usage for reference resolution and calling `onResolvedValueChange` is completely valid, it would just be better if `reaction` fired immediately in that case. Do you agree?

If so, I've been thinking whether an immediate reaction could be achieved by using the fact that all nodes in the state tree are tweaked and patch events are emitted for all of them immediately. So whenever any tweaked node changes, updating the back-references and calling `onResolvedValueChange` would not be wrong, it would just be done too often, but this could be optimized perhaps. What do you think?

**Comment by xaviergonz** [comment]
Closing in favor of https://github.com/xaviergonz/mobx-keystone/issues/233
