### ISSUE TITLE
Static members of a class are lost once wrapped in ExtendedModel

### ISSUE THREAD

**Issue by Steffan-Ennis** [xaviergonz/mobx-keystone#215]
After extending a model with the ExtendModel mixin.  Typescript no longer recognises static members assigned with Object.defineProperty
```
@model('BOB')
class Bob extends Model({}){
  static LAST = 'Rules'
}

Object.defineProperty(Bob.prototype, 'name', {
  value: 'Bob',
  writable: false
})
console.log(Bob.name)
console.log(Bob.LAST)

class ExtendedBob extends ExtendedModel(Bob, {}){
  static LAST = 'Rules'
}
ExtendedBob.name

Object.defineProperty(ExtendedBob.prototype, 'last', {
  value: 'Rules',
  writable: false
})

ExtendedBob.last
console.log(ExtendedBob.LAST)
```

This makes it difficult to write new decorators/mixin which are designed to house common business logic

Is there a workaround for this?

**Comment by xaviergonz** [comment]
I'm using this test and it passes. Is there anything I might be missing?

```ts
test("ExtendedModel should bring static / prototype properties", () => {
  @model("Bobbin")
  class Bobbin extends Model({}) {
    static LAST = "Threadbare"
  }
  Object.defineProperty(Bobbin.prototype, "first", {
    value: "Bobbin",
    writable: false,
  })
  // (Bobbin.prototype as any).first = "Bobbin"

  expect((Bobbin.prototype as any).first).toBe("Bobbin")
  expect(Bobbin.LAST).toBe("Threadbare")

  const bobbin = new Bobbin({})
  expect((bobbin as any).first).toBe("Bobbin")
  expect((bobbin as any).LAST).toBe(undefined)

  @model("ExtendedBobbin")
  class ExtendedBobbin extends ExtendedModel(Bobbin, {}) {
    static LAST2 = "Threepwood"
  }
  Object.defineProperty(ExtendedBobbin.prototype, "first2", {
    value: "Guybrush",
    writable: false,
  })
  // (ExtendedBobbin.prototype as any).first2 = "Guybrush"

  expect((ExtendedBobbin.prototype as any).first).toBe("Bobbin")
  expect((ExtendedBobbin as any).LAST).toBe("Threadbare")
  expect((ExtendedBobbin.prototype as any).first2).toBe("Guybrush")
  expect((ExtendedBobbin as any).LAST2).toBe("Threepwood")

  const extendedBobbin = new ExtendedBobbin({})
  expect((extendedBobbin as any).first).toBe("Bobbin")
  expect((extendedBobbin as any).LAST).toBe(undefined)
  expect((extendedBobbin as any).first2).toBe("Guybrush")
  expect((extendedBobbin as any).LAST2).toBe(undefined)
})
```

**Comment by Steffan-Ennis** [comment]
I found that the code would run however typescript would fail to compile correctly.  
<img width="794" alt="Screen Shot 2021-02-17 at 9 42 32 am" src="https://user-images.githubusercontent.com/16796843/108133684-e45c6380-7104-11eb-901d-fe6ed0e7da5c.png">

```
npx typescript --version
npx: installed 1 in 2.507s
Version 4.1.5
```

In this example LAST came but not last

**Comment by xaviergonz** [comment]
Actually Bob.name compiles only because all classes have a "name" property. If instead of Bob.name you tried Bob.whatever you'd see it doesn't compile either.

e.g.

https://www.typescriptlang.org/play?#code/MYGwhgzhAEBCD2AjaBvAvgWAFDHgOwnhAFMA6EeAcwAoFFS8wBbYgSmgHoPoIALeAO4w62APKIAVsWAAXUgBNiAMwCWeYgAUATvAAOxLTICetJKV06Z8Y-oA00AESMWD+ygBuYEAFdiALkc6ACYHNFZsXAIiMgoaOgZmNk5uPEEefiE4JCDsCPAoaAAVeCZUTCxxKVkFZTVNHX1DE2Kmc0trIztHVS0IGVdUTx9-RxaQsIj8QhJyKmoW0h6+9i5oAXhvEHl0tLH7RG8ZIoBlaBUYVKOIJjBDaGJU70peaCtoAGtUgWhFVXVtPQGYzQMDyRTbMA-Wr-BpAozYIA

Instead of define property, why don't you just use a plain class property? e.g.

```ts
class Bob ... {
  name = "Bob"
}

class ExtendedBob extends ... {
  last = "Rules"
}
```

that way Typescript will be able to know the property is there

(again though, this is not something about this library, but something about typescript design itself)

**Comment by Steffan-Ennis** [comment]
Thanks for the help. Unfortunately some of these members are dynamic ie come from settings modules etc, of which I access statically before initialising some of my models. I'll have follow a different pattern.

**Comment by xaviergonz** [comment]
No problem. I'll close the issue since this is more about TS than this lib really.
