### ISSUE TITLE
Ability to create a reference automatically from snapshot like in MST?

### ISSUE THREAD

**Issue by terrysahaidak** [xaviergonz/mobx-keystone#23]
I was playing with the mobx-keyston and trying different things I was able to do int MST a find a thing which forces me to rewrite a lot of my MST application code to handle it.

In short, I'm using `normalizr` a lot which allows me to normalize nested responses. It generates me nice normalized structure like this:

```ts
const response = [
  {
    id: '1',
    title: 'Buy',
	// normalizr leaves the id here
	// the object itself will be placed in entities
    todos: {
  		id: '1',
  		text: 'Apple',
	}, 
  },
];

// normalized using Group scheme
const normalized = {
	// the array of all groups ids
	result: ['1'],
	// all the objects
	entities: {
		groups: {
			'1': {
				id: '1',
				title: 'Buy',
				// normalizr leaves the id here
				// the object itself will be placed in entities
				todos: ['1']
			}
		},
		todos: {
	 		'1': {
	  			id: '1',
	  			text: 'Apple',
			}, 
		}
	},
}
```

And here is the main problem. Check out fetchGroups action:

```ts
@model('RootStore')
export class RootStore extends Model({
  todos: prop(() => objectMap<TodoModel>()),
  groups: prop<GroupModel[]>(() => []),
}) {
  @modelAction
  fetchGroups() {
    const todoNode = new TodoModel(normalized.entities.todos[1]);
    this.todos.set(todoNode.id, todoNode);

    // this won't work because we haven't created references
    this.groups = normalized.results.map((id) =>
      new GroupModel(normalized.entities.groups[id])
	);

	// but this one should work just fine
	this.groups = normalized.results.map((id) =>
      new GroupModel({
        ...normalized.entities.groups[id],
        todos: normalized.entities.groups[id].todos.map(todoRef),
      })
    );
  }
}

const rootStore = new RootStore({});

rootStore.fetchGroups();
```
Also, rest of the code here:

```ts
@model('TodoModel')
export class TodoModel extends Model({
  id: prop<string>(() => uuid()),
  text: prop<string>(''),
}) {}

const todoRef = customRef<TodoModel>('todo ref', {
  getId(ref) {
    return ref.id;
  },

  resolve(ref) {
    return getRoot<RootStore>(ref).todos.get(ref.id);
  },
});

@model('Group')
export class GroupModel extends Model({
  id: prop<string>(() => uuid()),
  title: prop<string>(''),
  todos: prop<Ref<TodoModel>[]>(() => []),
}) {}
```

**Comment by xaviergonz** [comment]
If the question is if it is possible to create a ref from an id (not sure if that's the question), then yes
You can either use fromSnapshot (assumming it has the proper structure and $modelType), or pass the id directly to the ref constructor rather than the object.

e.g. new TodoRef("1") instead of new TodoRef(whateverTodoObject)

**Comment by terrysahaidak** [comment]
The question here is it possible to create a reference during model initialization automatically?

The main problem here is that the normalized entity might have 4-5 level of nesting.

But looking at a ref object itself, I discovered it's just an object with `$modelType: 'ref name'`, so probably all I need is to make the normalizr create those objects for me

**Comment by xaviergonz** [comment]
you might even create the snapshot representation with either 
```
getSnapshot(new todoRef("someId"))
```
or
```
modelSnapshotInWithMetadata(todoRef, {
  id "someId",
})
```
or
```
{
  $modelType: "todo ref",
  id: "someId"
}
```

**Comment by terrysahaidak** [comment]
Maybe it's for a different issue, but something like `preProcessSnapshot` would help here, what do you think @xaviergonz?

**Comment by xaviergonz** [comment]
Actually there is (at least for models)
If your model contains a `fromJson(json)` override you can make it return a different json than the original one.

```ts
  /**
   * Optional transformation that will be run when converting from a snapshot to the data part of the model.
   * Useful for example to do versioning and keep the data part up to date with the latest version of the model.
   *
   * @param snapshot
   * @returns
   */
  fromSnapshot?(snapshot: any): any

```
Of course another option is to just pass the json to a function and to whatever transformations there before actually using `fromSnapshot`

**Comment by terrysahaidak** [comment]
Oh, totally missed the `fromSnapshot` part in the docs, thank you :)

**Comment by SimonChaumet** [comment]
I don't really understand how to use the fromSnapshot to get refs out of it
If I want to use it with normalized data (e.g. with normalizr), I would need to override a function when the object is created with refs isn't it ?
Then what this function would be ? Is it fromSnapshot ?
Because fromSnapshot seems to be useful for changing values inside the object but not the object location.
