### ISSUE TITLE
Typing suggestion for types.model

### ISSUE THREAD

**Issue by mirco-s** [xaviergonz/mobx-keystone#230]
I want to preface this suggestion with a big thanks for creating mobx-keystone. I was kind of bumped when I noticed how mst typescript support wasn't that great and was happy when I found this library. I would like to make a suggestion for types.model to reduce the need of writing the type information twice, unless it's actually neccessary for recursive types. The suggestion would look like this:

```javascript
type Class<T> = new(...args: any[]) => T;
// If the user explicitly sets M then this expression returns `object` otherwise `Class<K>`
type ClassOrObject<M, K> = K extends M ? object : Class<K> | (() => Class<K>);
// If the user explicitly sets M then this expression returns M otherwise K.
type NonDefault<M, K> = K extends M ? M : K; 

export declare function typesModel<M = never, K = M>(modelClass: ClassOrObject<M, K>): IdentityType<NonDefault<M, K>>;
```

With this typing, it would usually be enough to just pass the model instead of declaring the generic and pass the model:

```javascript
export class TodoList extends Model({
  todos: tProp(types.array(types.model(Todo)), () => []), // infers types now from passed model
}){ /* TodoList example code */}
```

And in case of a recursive type `ClassOrObject ` would resolve into `object `when explicitly typing `M`:

```javascript
export class TodoList extends Model({
  todos: tProp(types.array(types.model<TodoList>(() => TodoList)), () => []), //still works.
}){ /* TodoList example code */}
```

I assume that the decision to define model references as `types.model<SomeModel>(SomeModel)` was only made out of necessity to support recursive types. If that is the case, my suggestion could increase the usability since I think most of the time, you don't define models with recursive types in them.

**Comment by xaviergonz** [comment]
> I want to preface this suggestion with a big thanks for creating mobx-keystone. I was kind of bumped when I noticed how mst typescript support wasn't that great and was happy when I found this library

Thanks!

Your suggestion is great (I couldn't think of a way to make it work without breaking recursive types TBH!). It should be out now in v0.56.0 :)

**Comment by mirco-s** [comment]
That was fast =). Thanks!
