### ISSUE TITLE
Suggestion: Declare lifecycle methods as protected

### ISSUE THREAD

**Issue by mirco-s** [xaviergonz/mobx-keystone#232]
If you create a new model with no properties or actions, intellisense in vscode provides the following autocompletes on a new instance:
```
$
$modelId
$modelType
fromSnapshot?
getRefId
onAttachedToRootStore
onInit
toString
typeCheck
modelIdPropertyNameSymbol
```
While most of them are necessary, I doubt you barely ever want to access the lifecycle methods `onAttachedToRootStore` and `onInit` on an instanced model. That's why I would suggest declaring them `protected` on the `BaseModel`. If, for some reason, a user still wants to access `onAttachedToRootStore` or `onInit`, he can simply declare them public or with no modifier when implementing the methods: 

```javascript
/*
 * Assuming onInit and onAttachedToRootStore are declared as follows:
 * protected onInit?(): void;
 * protected onAttachedToRootStore?(rootStore: object): (() => void) | void;
 */
@model("someModel")
export class Example extends Model({}) {
  
  // visible through intellisense with or without public modifier
  /* public */ onAttachedToRootStore() {

  }
}

const example = new Example({});

example.onInit // error, default behavior is that onInit is not visible, which makes sense when it's not even implemented
example.onAttachedToRootStore // no error
```
With the current version of mobx-keystone you could already declare the methods as protected, but it has to be done explicitly:

```javascript
@model("someModel")
export class Example extends Model({}) {

  // currently, you have to declare the methods to make them not accessible
  protected onAttachedToRootStore() {
    // empty
  }
}

const example = new Example({});

example.onInit // no error, even though there is no implementation
example.onAttachedToRootStore // error
```

**Comment by xaviergonz** [comment]
Thanks! Already in the repo. It should be out in the next version (I won't cut a new version with only that feature for now though)

**Comment by mirco-s** [comment]
Thanks!
