### ISSUE TITLE
onActionMiddleware not triggered by action on node added by patch

### ISSUE THREAD

**Issue by aidangoettsch** [xaviergonz/mobx-keystone#236]
I'm intercepting actions similar to how the [Client/Server Example](https://mobx-keystone.js.org/examples/clientServer) does and then updating the local store using patches from a server. However, when I add an item to the tree using this, actions on that item are not triggered. It seems like getParent properly resolves the item as being attached to the tree, so if there's anything else that would help debug this it would be really appreciated.

**Comment by xaviergonz** [comment]
is there a chance you might have a minimal reproduction code?

**Comment by xaviergonz** [comment]
Also, when using actions to do RPC between clients the model ids of the nodes are used to make sure the path between both are right. Are you sure the $modeld of each node in the path of the target action are the same in both machines?

**Comment by aidangoettsch** [comment]
Not quite sure what fixed it, but my initial testing was done without React, but as soon as I setup mobx-react and was able to loop over elements things ended up working. I did have model IDs synced properly - all nodes originate from the server store where actions are run and the IDs are moved to the client through patches or the initial snapshot. I'm going to close this since I haven't been able to reproduce it when doing things more "properly" and there were some hacks with my initial setup that were likely the issue.

**Comment by xaviergonz** [comment]
glad you got it sorted out
