### ISSUE TITLE
How to do routing ?

### ISSUE THREAD

**Issue by TheKeyblader** [xaviergonz/mobx-keystone#244]
Hello!.
I was working on routing with Wouter.
I am using the property page on my root model to add my page model to the root tree.

### The Problem
Certain pages models have autorun that uses getparent. 
but since getParent is observable. when the model is detached.
autorun is executed before getting disposed of by (detach ??)

Here an example of the problem. [code](https://codesandbox.io/s/routing-mobx-keystone-t120b?file=/src/stores/test.ts)

### Solutions
1. Use an if dude!
2. Modify detach to dispose onAttachedToRootStore before removing from the tree (Breaking change).
3. Use multiple root stores with react contexts ??
4. ??

P.S: I need a better issue name?

**Comment by xaviergonz** [comment]
reaction allows you to separate which part it reacts to from the part it should execute as an action. I'd look into that.

**Comment by xaviergonz** [comment]
https://mobx.js.org/reactions.html#reaction

**Comment by TheKeyblader** [comment]
On my project, I use reaction instead of autorun and I get the same problem.
I need to observe a property on the parent model. but the model is detached, the parent gets undefined and triggers a reaction or a autorun. they are a simple solution the if. but it boring to use if simply to not get an error for one execution of the reaction.

**Comment by TheKeyblader** [comment]
After some test. I found two solutions.
1. Use an if dude.
2. untracked.

And also I miss read the documentation, I thought the disposer function return by **onAttachedToRootStore** was executed before detach not after.
It a bit strange I think but ok. 
So finally I was searching for **reactions** that live only on **attach lifetime** so when my parent is never undefined.

**Comment by xaviergonz** [comment]
You might also capture the parent (assuming you don't change the parent other than when removing the node from the root store)

```ts
  onAttachedToRootStore() {
    const parent = this.parent;
    return autorun(() => {
      const fake = parent.counter + 1;
      console.log("counter " + this.$modelType);
    });
  }
```

**Comment by xaviergonz** [comment]
Btw, if what you actually need to access is the root store then you can get it from the hook parameter
```ts
onAttachedToRootStore(rootStore) {
    return autorun(() => {
      const fake = rootStore.counter + 1; // ok since already captured in the parameter
      console.log("counter " + this.$modelType);
    });
  }
```

**Comment by TheKeyblader** [comment]
First, thank you for your help 😄
> 
> 
> You might also capture the parent (assuming you don't change the parent other than when removing the node from the root store)

How I didn't found this solution 😅  ? 
Thanks!

> that being said, if it were up to me I'd use the if :)

You are totally right, just wanted if they are a better way to do a reaction that runs attach lifetime.
Now I know the alternative 👍 

> 
> 
> Btw, if what you actually need to access is the root store then you can get it from the hook parameter
> 
> ```ts
> onAttachedToRootStore(rootStore) {
>     return autorun(() => {
>       const fake = rootStore.counter + 1; // ok since already captured in the parameter
>       console.log("counter " + this.$modelType);
>     });
>   }
> ```
I don't use root store in this case but still, thank you.

Thank you for the time you have taken to help me.
