### ISSUE TITLE
How to convert model to json without `$modelId` and `$modelType`

### ISSUE THREAD

**Issue by sxwebdev** [xaviergonz/mobx-keystone#250]
Hey. How to convert model class to json without `$modelId` and `$modelType`?

Unfortunately my backend does not accept an object with these fields when I post data to the server. How can I filter them and cast the object to the desired type?

**Comment by mindreframer** [comment]
Hey @sxwebdev, you could try following code: 

```typescript
/**
 * removeKeystoneIds cleans up a snapshot object from `$modelId` and `$modelType` fields
 * @param obj any serializable object (optimally the result from getSnapshot function from Mobx Keystone)
 * @returns in-place modified obj (since we already work with a snapshot)
 */
const removeKeystoneIds = (obj: any) => {
  for (var propertyName in obj) {
    if (propertyName == '$modelId' || propertyName == '$modelType') {
      delete obj[propertyName]
    }
    if (Array.isArray(obj[propertyName])) {
      obj[propertyName] = obj[propertyName].map(removeKeystoneIds)
    }
    if (obj[propertyName] !== null && typeof obj[propertyName] === 'object') {
      obj[propertyName] = removeKeystoneIds(obj[propertyName])
    }
  }
  return obj
}

export { removeKeystoneIds }

```

**Comment by xaviergonz** [comment]
also check out data models
https://mobx-keystone.js.org/dataModels

**Comment by sxwebdev** [comment]
@mindreframer 

Thank you! this is what I needed!

```js
if (
  request.method &&
  ["post", "put"].includes(request.method) &&
  request.data?.$modelId
) {
  request.data = removeKeystoneIds(request.data);
}
```

@xaviergonz This option is unfortunately not suitable, because I need a hook `onAttachedToRootStore`

**Comment by mindreframer** [comment]
@sxwebdev Glad that it worked for you! Good luck with your app!

**Comment by xaviergonz** [comment]
> This option is unfortunately not suitable, because I need a hook onAttachedToRootStore

You can also use its inverse, `onChildAttachedTo` and add it to the parent:

### `onChildAttachedTo(target: () => object, fn: (child: object) => (() => void) | void, options?: { deep?: boolean, fireForCurrentChildren?: boolean }): (runDetachDisposers: boolean) => void`

Runs a callback every time a new object is attached to a given node.
The callback can optionally return a disposer which will be run when the child is detached.

The optional `options` parameter accepts and object with the following options:

- `deep: boolean` (default: `false`) - `true` if the callback should be run for all children deeply or `false` if it it should only run for shallow children.
- `fireForCurrentChildren: boolean` (default: `true`) - `true` if the callback should be immediately called for currently attached children, `false` if only for future attachments.
