### ISSUE TITLE
Self-model references cause TS error

### ISSUE THREAD

**Issue by dodas** [xaviergonz/mobx-keystone#251]
Hi! I feel like this used to work before:
```tsx
import { model, prop, Model } from "mobx-keystone";

@model("app/MyModel")
export class MyModel extends Model({
  child: prop<MyModel>()
}) {}
```

now it causes this TypeScript error:
```
Type 'MyModel' recursively references itself as a base type.ts(2310)
'MyModel' is referenced directly or indirectly in its own base expression.ts(2506)
```

While this works:
```tsx
export class MyPlainModel {
  child: MyPlainModel = new MyPlainModel();
}
```

Any idea? Thanks!

**Comment by xaviergonz** [comment]
That's because you are saying that your model must have your model as child, without exceptions and recursively until infinite. If you put for example undefined in your prop you break this chain, e.g.:

```ts
@model("app/MyModel")
export class MyModel extends Model({
  child: prop<MyModel | undefined>() // note undefined here
}) {}```

**Comment by xaviergonz** [comment]
In other words, if you do this you will get the same error:
```ts
interface A {
  a: A;
}
```

so you'd need to make an object like { a: { a: { a: { .... which is not possible

**Comment by dodas** [comment]
Oh that makes sense. Sorry, I got somehow confused.
Thanks for help.
