### ISSUE TITLE
A way to extend arrayActions / objectActions ? 

### ISSUE THREAD

**Issue by mindreframer** [xaviergonz/mobx-keystone#258]
Hey @xaviergonz, first: thank you for providing Mobx Keystone, I'm using it in my app and liking it much better than Mobx State Tree! 

Currently I'm trying to figure out a possibility to extend generic array / object actions without tying it up to a particular model instance. 

In concrete:  `arraySwap` function is currently non-generic and requires a "host" model: 
```typescript
@modelAction arraySwap(array: any[], indexA: number, indexB: number) {
    if (indexA < 0 || indexB < 0 || indexA > array.length - 1 || indexB > array.length - 1) {
      return
    }
    var tmp1 = array[indexA]
    var tmp2 = array[indexB]
    array[indexA] = null
    array[indexB] = null
    array[indexA] = tmp2
    array[indexB] = tmp1
    return array
  }
```
When implemented with `arrayActions` primitives, it blows up my React.js app. 

```typescript
class ArrayUtils {
  static arraySwap(array: any[], indexA: number, indexB: number) {
    if (indexA < 0 || indexB < 0 || indexA > array.length - 1 || indexB > array.length - 1) {
      return
    }
    var tmp1 = array[indexA]
    var tmp2 = array[indexB]
    arrayActions.set(array, indexA, null)
    arrayActions.set(array, indexB, null)
    arrayActions.set(array, indexA, tmp2)
    arrayActions.set(array, indexA, tmp1)
    return array
  }
}
```

I see that `arrayActions` is using `import { fnModel } from "./fnModel"`, and `fnModel` is not exposed for end users. 

Are there any other options to implement further generic Array/Object actions, without using a mounted model instance? 

As a short-term fix I could contribute a `swap` function on the `ArrayActions` module, yet this feels rather inflexible.

**Comment by xaviergonz** [comment]
my guess is that the react app is blowing because the operation is not being made in a batch, so it is trying to re-render while some elements are null

does it work if you make arraySwap a mobx action? e.g.

```ts
import {action} from "mobx"

const arraySwap = action((array: any[], indexA: number, indexB: number) => {
    if (indexA < 0 || indexB < 0 || indexA > array.length - 1 || indexB > array.length - 1) {
      return
    }
    var tmp1 = array[indexA]
    var tmp2 = array[indexB]
    arrayActions.set(array, indexA, null)
    arrayActions.set(array, indexB, null)
    arrayActions.set(array, indexA, tmp2)
    arrayActions.set(array, indexA, tmp1)
    return array
  });
```

**Comment by mindreframer** [comment]
@xaviergonz thanks for response! 

Just tried it out wrapped into `action`, same. This brought me on an idea: using a fake item of similar shape instead of null. I get 4 undo entries in the undoMiddleware with all the intermediate steps + this makes this function non-generic. Wrapping it in `action` does not change anything. 

Do you have any other ideas to try out?

**Comment by xaviergonz** [comment]
did you also try using unsoManager.withGroup inside the action?

**Comment by mindreframer** [comment]
That is the issue... My undoManager is tied to a particular UI and would be not accessible in that generic module for array manipulations. I would like to be able to re-used it with different undoManagers in a transparent fashion. 


Would exposing `fnModel` to the end user make it possible to implement user-specific generic array / object actions?

**Comment by mindreframer** [comment]
@xaviergonz I have tried exposing `fnModel` in `standardActions/index.ts`: 

```typescript
export * from "./arrayActions"
export * from "./fnModel"
export * from "./objectActions"
```

That's actually all that is required to solve this issue. Should I open a pull request with this 1-line change? 

Or: what is speaking against exposing `fnModel` to the end-user?

**Comment by mindreframer** [comment]
I have opened up https://github.com/xaviergonz/mobx-keystone/pull/262 as suggestion to resolve this issue

**Comment by mindreframer** [comment]
Hey @xaviergonz, how can we move forward with this issue? I don't want to fork mobx-keystone because of this, but I am not sure, what other options I have... Exposing `fnModel` solves those issues completely. Please don't ignore this issue.

**Comment by xaviergonz** [comment]
I promise I'll take a look once I get a bit of time

**Comment by mindreframer** [comment]
Thanks!

**Comment by xaviergonz** [comment]
This will be out soon in v0.60.0

# Standalone Actions

Sometimes you might need to define a "model" action but without an associated model. Say for example that you need an array swap method that needs the be processed by middlewares (undoable, etc.). One way to achieve this is to use standalone actions like this:

```ts
const arraySwap = standaloneAction(
  "myApp/arraySwap",
  <T>(array: T[], index1: number, index2: number): void => {
    const [v1, v2] = [array[index1], array[index2]]
    array[index2] = v1
    array[index1] = v2
  }
)
```

Note the following pre-requisites apply to standalone actions:

- The name provided must be unique across your whole application.
- The first argument (the target) must always be an existing tree node.

**Comment by xaviergonz** [comment]
out now

**Comment by xaviergonz** [comment]
Actually also added swap to array actions in 0.60.2 while at it

**Comment by mindreframer** [comment]
🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉  THANK YOU! This looks super-clean!

**Comment by mindreframer** [comment]
Just updated it in my codebase, works flawlessly. Thanks again for the extra effort to come up with such a clean solution. 

Going to close this issue.
