### ISSUE TITLE
Package issues with metro bundler / react-native

### ISSUE THREAD

**Issue by andriimuzh** [xaviergonz/mobx-keystone#263]
I'm trying to setup a new project with React Native v. 0.64.1 and typescript 3.8.3.
Installation  of mobx-keystone using npm or yarn is going well but I'm facing a warning when trying to start a Metro Bundler using `npx react-native start` command and receive a warning in console:

`
warn Package mobx-keystone has been ignored because it contains invalid configuration. Reason: Package subpath './package.json' is not defined by "exports" in /Users/andrii/projects/tsApp/node_modules/mobx-keystone/package.json
`

**Comment by xaviergonz** [comment]
is there a chance you might publish a repo with this error?

**Comment by andriimuzh** [comment]
yes I can publish it if you want, but you can easily reproduce it just by initing a new React Native project and installing mobx-keystone. so steps to reproduce it's just:
1) `npx react-native init AwesomeTSProject --template react-native-template-typescript`
2) `npm i mobx-keystone` or using yarn if you want
3) `npx react-native start`
4) see the warning in console

Also I did some research and noticed that I can' face warning using mobx-keystone 0.55.0, this warning seems to become visible only in newest versions

Thank you

**Comment by xaviergonz** [comment]
I couldn't get it to fail (at least not without connecting a phone), but I published a tentative fix in 0.60.1, let me know if it works...

**Comment by andriimuzh** [comment]
Yes, the issue is resolved in the new 0.60.2 version. Thanks a lot for the help

**Comment by xaviergonz** [comment]
you are welcome!
