### ISSUE TITLE
is computedFn (from mobx-utils) supported?

### ISSUE THREAD

**Issue by devlittlemac** [xaviergonz/mobx-keystone#279]
Hello!

I'm wondering if something like computedFn (computed + arguments) is available with this library.

Thank you!

**Comment by xaviergonz** [comment]
I think you should be able to use the one from mibx-utils directly

**Comment by devlittlemac** [comment]
ok I'll try out!

Thank you for your quick reply!

**Comment by xaviergonz** [comment]
please reopen if the provided solution did not work for you :)
