### ISSUE TITLE
Prior to typescript 4.2.* you could use abstract classes as the base class for models

### ISSUE THREAD

**Issue by Steffan-Ennis** [xaviergonz/mobx-keystone#280]
The Following pattern is not longer possible 
```
abstract class BaseModel extends Model({}){
  /// abstract properties and functions ...
}

@model('MyModel')
class MyModel extends ExtendedModel(BaseModel, {}){
 /// implementations of abstract properties and functions
}
```

Typescript 4.2.* will throw the following error 
`TS2509: Base constructor return type 'never' is not an object type or intersection of object types with statically known members.`

Suggested fix
```
export declare function ExtendedModel<TProps extends ModelProps, TBaseModelClass>(baseModel: TBaseModelClass, modelProps: TProps): _Model<TBaseModelClass & Object extends ModelClass<infer M> ? M : {}, TProps>;
```

When extending an abstract class it should be inferred as a an empty construct

**Comment by Steffan-Ennis** [comment]
Looks like this has already been resolved

**Comment by justin-hackin** [comment]
Side not for the record: there's another way to make a keystone model implement an interface that's purely TS: use the `implements BaseModel` following the call to `Model`. It's a bit cleaner but of course you can't define base methods/properties this was as you can with ExtendedModel
