### ISSUE TITLE
A thought experiment: Battleships

### ISSUE THREAD

**Issue by mikecann** [xaviergonz/mobx-keystone#281]
Suppose we wanted to make a multiplayer game of Battleships using mobx-keystone.

This can easily be modeled in MobX Keystone. We have  a root model Battle, it has two Player models which have a number of Ship models and a number of Cell models. 

Using the [TodoList](https://mobx-keystone.js.org/examples/clientServer) example we can intercept a "take turn" action on ClientA and send that to the server which then sends that to ClientB thus updating the state of the model.

Now the problem is that Battleship is a game of imperfect information. So that is ClientA should not know of ClientB's ship positions and visa-versa.

So how to handle this? The server is going to have to be the adjudicator here but how precicely? [onActionMiddleware](https://mobx-keystone.js.org/actionMiddlewares/onActionMiddleware) only intercepts the "top level action" so its not going to send the resulting "hit" or "miss" action to the client.

I know this is a very simple example but imagine a much more complex example such as the game Hearthstone where there are many actions and sub-actions thats occur as the result of a "turn".

Thoughts? How would you solve this?

**Comment by xaviergonz** [comment]
You could have a root store (or branch) per client in the server, replicate the action on one of the clients root stores and then have a reaction or something that whenever the store in client 1 changes applies a change in client 2 store.

That's just some random idea though, for a battleship game actually probably you just want to go simple (a websocket message from each client where it is firing at and the response sent to each client)

**Comment by mikecann** [comment]
@xaviergonz thanks for your reply mate I appreciate you taking the time to think this through with me.

We could debate back and forth on this for a while but I think ill just leave it here and not take up your issue with my speculative questions.

Cheers.
