### ISSUE TITLE
`idProp.withSetter` is not a function

### ISSUE THREAD

**Issue by dodas** [xaviergonz/mobx-keystone#283]
I tried passing `idProp.withSetter()` as a prop (since types suggest that is possible), but got this error:

```
TypeError: mobx_keystone_1.idProp.withSetter is not a function
```
Looks like [`idProp` is a regular `Symbol`, but has type asserted as `ModelProp`](https://github.com/xaviergonz/mobx-keystone/blob/master/packages/lib/src/modelShared/prop.ts#L81), which is not the case on runtime.

Can we fix this and add the `withSetter` method to this symbol, or would we improve the type assertion so types don't suggest the `withSetter()` method?

Thanks!

**Comment by xaviergonz** [comment]
Thanks, it should now support withSetter in v0.60.7

**Comment by dodas** [comment]
Thank you!
