### ISSUE TITLE
TS errors: extended model does not recognize super props

### ISSUE THREAD

**Issue by justin-hackin** [xaviergonz/mobx-keystone#298]
I've reproduced this error using the example provided in the docs: https://codesandbox.io/s/affectionate-sunset-n93h2?file=/src/index.ts

P.S. in https://mobx-keystone.js.org/classModels#inheritance there's a typo where BasePoint should read Point

**Comment by xaviergonz** [comment]
Try downgrading to ts 4.2 or upgrading to a 4.4 beta

**Comment by mashaalmemon** [comment]
@xaviergonz is 4.2 the minimum required? I'm running 4.1.3 and have issues as well.

**Comment by xaviergonz** [comment]
I don't know why it doesn't work in codesandbox, but it works for me using ts 4.2.x

![image](https://user-images.githubusercontent.com/6306796/130738359-573bee28-7a4a-4cb5-b37b-3f3477298368.png)

using these tsconfig settings

```
    "strict": true,
    "noImplicitAny": true,
    "noImplicitThis": true,
    "alwaysStrict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
```

**Comment by xaviergonz** [comment]
same with stackblitz, it works

https://stackblitz.com/edit/typescript-ycwwp9?file=index.ts

**Comment by mashaalmemon** [comment]
Upgrading to ts@4.2 seems to work for me as well.

**Comment by xaviergonz** [comment]
> Thanks for providing a solution @xaviergonz. I noticed that going to ts@4.2 not only allowed me to access the inherited props on `super`, I can also access them off of `this` according to Typescript. Is there a reason why the docs use `super` and not `this`?

Because the docs code overrides a property with the same name
