### ISSUE TITLE
resetting instance properties back to their default values

### ISSUE THREAD

**Issue by justin-hackin** [xaviergonz/mobx-keystone#304]
In MST I've needed to keep a model's default values in a snapshot and then apply that snapshot in order to reset an instance's properties back to their defaults. This never seemed optimal or elegant. ASIDE: In general, I find the design of mobx-keystone to be much more ergonomic with regards to defaults. 

Now that I'm re-examining the code, I'm wondering if there's a way to keep my defaults in the prop declarations and cause the instance to revert back to its defaults. I can't replace the instance with another newly constructed instance (using {} as constructor arg) because it is persisted using mobx-keystone-persist. I'm imagining an alternate version of applySnapshot where if a property of the model is not in the snapshot, it is reset to its default. I thought of a cheap way to do this but it seems clumsy to `getSnapshot(new MyModel({}))` to find out its default snapshot.

**Comment by xaviergonz** [comment]
actually using `getSnapshot(new MyModel({}))` shouldn't be too bad

```
const defaultSn = getSnapshot(new MyModel({}))
// store it somewhere for all future uses
// you can reuse that snapshot to reset all models of that type

// to reset to default
applySnapshot(model, {...defaultSn, $modelId: model.$modelId })
```

**Comment by justin-hackin** [comment]
@xaviergonz true enough, I don't quite understand why you had to extend defaultSn though, I thought $modelId is in the snapshot

**Comment by xaviergonz** [comment]
model Id is in the snapshot, but most probably you want to keep the original object model ID when resetting it to the default values (rather than changing it)

**Comment by xaviergonz** [comment]
feel free to reopen if you have more questions about this :)

**Comment by justin-hackin** [comment]
@xaviergonz thanks for the courtesy, I should have closed this after you answered.  If one needs the reset functionality everywhere it would be easy enough to put it in a base model in one's project.
