### ISSUE TITLE
[Regression] idProp causes extended models to lose its base model props

### ISSUE THREAD

**Issue by dodas** [xaviergonz/mobx-keystone#310]
After upgrading from `0.60.7` to `0.61.0`, I started getting errors for extended models.
It looks like all props from the base model are lost if it specifies `idProp` as one of its props.

Correct behaviour when extending a model with no `idProp`:

<img width="841" alt="Screenshot 2021-09-04 at 00 08 14" src="https://user-images.githubusercontent.com/14360171/132069775-985247bb-f1a4-4469-bd4a-2a95dec6e435.png">

Incorrect behaviour when extending a model with `idProp` – notice none of the props from the base model are present:

<img width="872" alt="Screenshot 2021-09-04 at 00 08 31" src="https://user-images.githubusercontent.com/14360171/132069776-1089ead1-a235-4db5-958a-82a4f2aa0418.png">

----------
TS version: tried both `4.2.4` and `4.4.2`

Is this a bug?
Thanks!

**Comment by xaviergonz** [comment]
looks like it. thanks, I'll take a look

**Comment by xaviergonz** [comment]
fixed in 0.61.2

**Comment by dodas** [comment]
Thank you! Exceptional support as always.

Please, is there a way to contact you personally?
