### ISSUE TITLE
How to reuse the same selectors?

### ISSUE THREAD

**Issue by quolpr** [xaviergonz/mobx-keystone#311]
Suppose I have class:

```typescript
interface NodeTree<T> {
  siblings: T[];
  parent: T | undefined;
  hasChildren: boolean;
}

@model('NoteBlockModel')
export class BlocksTreeNodeModel extends Model({
  children: prop<Ref<NoteBlockModel>>(),
}) implements NodeTree<BlocksTreeNodeModel> {
  get viewTreeHolder() {
    return findParent<BlocksTreeView>(this, isViewTreeHolder)!;
  }

  get parent() {
    if (this.viewTreeHolder.rootBlockId === this.$modelId) return undefined;

    const parentBlock = this.noteBlockRef.current.parentBlock;

    return parentBlock && this.viewTreeHolder.nodesMap[parentBlock.$modelId];
  }

  @computed
  get hasChildren() {
    return this.children.length !== 0;
  }

  @computed({ equals: comparer.shallow })
  get siblings() {
    const parent = this.parent;

    if (!parent) {
      throw new Error("You can't get sibling of root noteblock");
    }

    return parent.children;
  }
}
```

And I also want to introduce another class that should implement the NodeTree interface too. I am curious, how can I do it without code duplication and model inheritance(in case I need to implement multiple interfaces)?

**Comment by xaviergonz** [comment]
I see this as a TS question rather than mobx-keystone, but you could do it like this

```ts
interface Whatever {
  someFunc1(): boolean;
  someFunc2(): boolean;
}

function someFunc1(this: Whatever) {
  return true;
}

function someFunc2(this: Whatever) {
  return true;
}

class Clazz implements Whatever {
  someFunc1 = someFunc1
  someFunc2 = someFunc2
}
```

**Comment by quolpr** [comment]
@xaviergonz good, thank you for the answer 🙂 But will the @computed  work? Where should I define it?

**Comment by justin-hackin** [comment]
@quolpr this seems like a good use case for a generics factory function: https://mobx-keystone.js.org/classModels#factory-pattern--generics

**Comment by justin-hackin** [comment]
Perhaps my answer was too tangential @quolpr , was reminded of this after I implemented the creation of a computed in onAttachedToRootStore. Something like this might help:

```
export function createGetter(node, prop, fn) {
  Object.defineProperty(node, prop, {
    get: fn,
    configurable: true,
  });
  makeObservable(node, { [prop]: computed });
}
```
 
Of course, using `this` in anonymous function isn't type-friendly so might be better to just redeclare the computeds and use pure functions that take the node instance as parameter instead of using `this`

**Comment by quolpr** [comment]
@justin-hackin that might be what I need; I will check. Thanks!
