### ISSUE TITLE
Generic model constructor data arg requires $modelId

### ISSUE THREAD

**Issue by justin-hackin** [xaviergonz/mobx-keystone#312]
I'm attempting to create a way of annotating node properties with metadata about the input type that should modify it. I settled on use of a generic class and a prop factory function. You can see the idea here https://codesandbox.io/s/test-generic-prop-yp236?file=/src/index.ts

Unfortunately this approach doesn't work and the only way to fix the TS error with the constructor data seems to be adding a $modelId property to it. This confused me because I thought the model would generate this property automatically like it usually does. Is this a good use case for generic classes? Might there be a better way to achieve my aim? 

I'm not very enthusiastic about this approach because there's no need for each property to have an id and, minor annoyance, the properties' values have an extra level of nesting. I'd much rather use a DataModel for this but then I can't put the class-based  functionality in the tree and I need the class in the tree for the label getter etc.

**Comment by justin-hackin** [comment]
I realized that I can work around this issue by using fromSnapshot/toSnapshot strategy to filter $modelId from the snapshots 🤷 The neat thing is I can

**Comment by xaviergonz** [comment]
Now that $modelId is no longer a requirement, can this issue be closed?
