### ISSUE TITLE
onAttachToStore is called twice

### ISSUE THREAD

**Issue by zeroslope** [xaviergonz/mobx-keystone#316]
The situation of this issue is similar to #103 . onAttachToStore is called twice.

You can see this example. https://codesandbox.io/s/mobx-keystone-test-forked-lzbb3?file=/src/index.ts

First, I add the node to rootStore. It produced the first output

![image](https://user-images.githubusercontent.com/10218146/132831311-27b12366-469d-4aaa-b95b-cb84a6c75410.png)

Then, I call `app.moveNode`.  It produced the second output, but onAttachToStore is called twice, I got three output.

![image](https://user-images.githubusercontent.com/10218146/132831554-ca4ebb8d-bf14-47c2-bfa3-9fd2c8d9db9a.png)

![image](https://user-images.githubusercontent.com/10218146/132831697-2a95b909-4278-4c03-b401-f7732f19f775.png)

**Comment by xaviergonz** [comment]
fixed in 0.61.3
