### ISSUE TITLE
Batch the same action undos

### ISSUE THREAD

**Issue by quolpr** [xaviergonz/mobx-keystone#319]
Imagine you are developing a note-taking app, and have a model:

```
export class NoteModel extends Model({     
   content: prop<string>(),
}) {
  @modelAction
  updateContent(newContent: string) {
    this.content = newContent;
  }
}
```

And on every keyboard press, `updateContent` is called. You also want this action to be undoable, but with the current undoMiddleware all undo actions will be done only by one symbol.

To avoid this issue, you could debounce input at your component, but the problem is if NoteModel will be displayed in two places. When the first component will be up to date(where we are typing), the content changes of the second component will be debounced.

So, is it somehow possible to introduce undo actions grouping if the same `@modelAction` is called again and again? We could, for example, introduce `@groupSequenceUndo` decorator for the action:

```
export class NoteModel extends Model({     
   content: prop<string>(),
}) {
  @modelAction
  @groupSequenceUndo
  updateContent(newContent: string) {
    this.content = newContent;
  }
}
```

Or even better if we will also could introduce a timing window, in which the batch of undos could exist `@groupSequenceUndo({windowTime: 1000})`. 
The use case: user types `Hello` then stops for the second, then `world!`. The undo at first will remove `world!` and then `Hello` even if `updateContent` was called in one sequence.

I hope my explanation is clear 😅 I want to know is it possible to implements and an overall thought on this idea. I am working on text editing app, and I need something like this. Thanks!

**Comment by xaviergonz** [comment]
you could write changes to a volatile variable in the model after each keystroke (a variable marked as `@observable`) and then commit those changes using a denounce to a model property. also you could use a reaction to make sure any changes to the model property (such as an undo action) update the observable variable

**Comment by quolpr** [comment]
@xaviergonz, thank you! It works like a charm 🙂
