### ISSUE TITLE
Manage computed model views as tree nodes

### ISSUE THREAD

**Issue by sisp** [xaviergonz/mobx-keystone#327]
I have a situation in which I need to derive one model from another (i.e. create a model view, somewhat related to [`createTransformer`](https://www.mobxjs.com/refguide/create-transformer.html)) and would like to have access to all contexts and tree navigation functions like `getParent` from the view as well as refer to it via a root ref.

Let's make this more specific:

```ts
enum DataType {
  Int = "int",
  Float = "float",
}

@model("app/Tensor")
class Tensor extends Model({
  id: idProp,
  dtype: prop<DataType>().withSetter(),
  shape: prop<number[]>().withSetter(),
}) {
  @computed
  get ndim(): number {
    return this.shape.length
  }
  
  // ...
}

const dataFrameContext = createContext<DataFrame>()

// A `Block` is an extension (because it has header names) and subset (because
// it has only 2 dimensions) of a `Tensor`. I need the `Tensor` because I
// operate on `Tensor` instances elsewhere, but I need the `Block` to configure
// the `DataFrame`.
@model("app/Block")
class Block extends Model({
  id: idProp,
  columns: prop<string[]>().withSetter(), // header names
  dtype: prop<DataType>().withSetter(),
}) {
  // Derive the `Tensor` from the `Block`.
  @computed
  get tensor(): Tensor {
    return new Tensor({
      id: `${this.id}.tensor`, // to make the tensor view ID deterministic
      dtype: this.dtype,
      shape: [dataFrameContext.get(this)?.rows ?? 0, this.columns.length],
    })
  }

  // ...
}

@model("app/DataFrame")
class DataFrame extends Model({
  id: idProp,
  blocks: prop<Block[]>().withSetter(),
  rows: prop<number>().withSetter(),
}) {
  onInit(): void {
    dataFrameContext.set(this, this)
  }

  // ...
}
```

And now I'll instantiate a `DataFrame` and, e.g., would like to access the parent of the tensor view:

```ts
const df = new DataFrame({
  blocks: [
    new Block({ columns: 1, dtype: DataType.Int }),
    new Block({ columns: 10, dtype: DataType.Float }),
  ],
  rows: 100,
})

getParent(df.blocks[0].tensor) // is `undefined` but I'd like it to be the `Block` instance
```

In order to achieve my desired behavior, I've been wondering whether it makes sense to add a new decorator called, e.g., `@modelView` which is `@computed` + attaching/detaching of the returned model. A `@modelView`-decorated getter must always return a model instance which must not already be attached anywhere else.

What do you think about this idea? And does my example make any sense, or does my modeling approach look wrong?

**Comment by xaviergonz** [comment]
Sorry for the late reply
```
getParent(df.blocks[0].tensor) // is `undefined` but I'd like it to be the `Block` instance
```

Don't you always know that this should return df.blocks[0]

Either way, I think this feature could be easily done in the app side:

```ts
const logicalParents = new WeakMap();

const logicalGetParent = (n) => getParent(n) ?? logicalParents.get(n);

 @computed
  get tensor(): Tensor {
    const t = new Tensor({
      id: `${this.id}.tensor`, // to make the tensor view ID deterministic
      dtype: this.dtype,
      shape: [dataFrameContext.get(this)?.rows ?? 0, this.columns.length],
    })

    logicalParents.set(t, this)

    return t
  }
```

**Comment by sisp** [comment]
Sorry for the possible misunderstanding. I'm not trying to just get the parent of a computed model; this is just an example. I'd like to be able to have _computed_ tree nodes or subtrees (as mentioned, along the lines of what [`createTransformer`](https://www.mobxjs.com/refguide/create-transformer.html) does) which are alternative views of the main tree. Does this make sense?

**Comment by sisp** [comment]
I've given this some more thought and think the concept of computed trees does indeed make sense. I think a computed tree has the following properties:
- **Immutable/Read-only** because it is derived from a mutable tree and state mutations are only applied there. This property would be enforced at runtime by means of the [read-only middleware](https://mobx-keystone.js.org/action-middlewares/readonly-middleware). In most cases, actions of computed model instances would be useless.
- **Middlewares** are never applied to computed trees because of immutability.
- **Contexts** are available in computed trees.
- **Root refs** are available with computed trees, both for (a) referencing computed model instances in a computed tree (when model instances have ID props and when the IDs are stable) and for (b) referencing non-computed model instances from within a computed tree. This also implies that computed model instances can reference other computed model instances.
- **Back-references** are available also for referenced computed model instances.
- **Root store** life-cycle hook (`onAttachedToRootStore`) gets called for computed model instances in the same way as for non-computed ones.

How about providing a new decorator? E.g.:
- `@computedTree` which behaves like MobX' `@computed` plus it ensures the above properties
- `@tree` (or `@computedTree`) which must be applied after MobX' `@computed` and ensures the above properties

**Comment by sisp** [comment]
@xaviergonz I sense you're not convinced by the feature or its motivation. Anything I can do to remove your doubts? :thinking:

**Comment by quolpr** [comment]
Oh yes, I miss this feature too. Something that is not attached to the state tree, but has access to all the mobx-keystone tree methods

**Comment by sisp** [comment]
@quolpr Could you sketch your use case? Perhaps with a simplified example?

**Comment by xaviergonz** [comment]
> @xaviergonz I sense you're not convinced by the feature or its motivation. Anything I can do to remove your doubts? 🤔

It is not a lack of convincement, but a lack of laptop (just got a new one yesterday after almost a full month, and trying to get the full idea while reading it on a phone is non-optimal 😓 )

Do you have an example of how you'd expect it to look using the decorators you mentioned above?

**Comment by sisp** [comment]
> It is not a lack of convincement, but a lack of laptop (just got a new one yesterday after almost a full month, and trying to get the full idea while reading it on a phone is non-optimal :sweat: )

Oh, I wasn't aware your laptop situation hadn't been resolved. Apologies for the misunderstanding. It's certainly not optimal to handle these discussions from a phone.

> Do you have an example of how you'd expect it to look using the decorators you mentioned above?

I was thinking about a design like this (using my original example again):

```ts
@model("app/Block")
class Block extends Model({
  id: idProp,
  columns: prop<string[]>().withSetter(), // header names
  dtype: prop<DataType>().withSetter(),
}) {
  // Derive the `Tensor` from the `Block`.
  @tree // <---- new decorator here
  @computed
  get tensor(): Tensor {
    return new Tensor({
      id: `${this.id}.tensor`, // to make the tensor view ID deterministic
      dtype: this.dtype,
      shape: [dataFrameContext.get(this)?.rows ?? 0, this.columns.length],
    })
  }

  // ...
}
```

The `@tree` decorator would have to be added after MobX' `@computed` decorator and adds logic for bridging between the regular parent tree and the computed subtree. I.e. when `@tree` is used, the root of the computed subtree gets attached to the parent, the read-only middleware is applied to the subtree, etc. In contrast to regular nodes, a computed root will become attached/detached more often, specifically every time it is recomputed.

To be honest, I haven't looked into ways of implementing it yet, so I don't know about the complexity of the involved changes/additions.

I tend to prefer `@tree` (+ MobX' `@computed`) over `@computedTree` because I think it's more modular and has a cleaner separation of MobX' and mobx-keystone's concerns.
