### ISSUE TITLE
When does onPatches call the listener with multiple patches?

### ISSUE THREAD

**Issue by TobiasWehrum** [xaviergonz/mobx-keystone#333]
Currently, some of my code would work differently depending on whether the onPatches listener is called with a single patch or multiple patches. All simple value replacements or array actions seem to only lead to one patch. I thought that grouping changes inside an action would lead to single onPatches listener call with a group of multiple patches, but it seems that even then the onPatches listener is just called multiple times with one patch each.

Is there any case that actually leads to multiple patches?

edit: Ah, a little dive in the code later - array.splice(), I guess? Is that the only case?

**Comment by xaviergonz** [comment]
Yes, that's currently the only case. If you want to "group patches" in a single action one trick you can use is to store patches in a buffer and then "flush the buffer" once onSnapshot is called (which is called after an action is finished).

**Comment by TobiasWehrum** [comment]
Ah, that's a neat trick. Thanks!

I'm actually glad that onPatches is mostly called with single patches. I'm augmenting the paths with $modelId information (for model instances in arrays) there because our app is online collaborative with undo/redo for actions each local user did - so raw indizes might not always point at the right element anymore. And that's much easier with non-grouped patches because you can be sure that the state is still "right after the patch".
