### ISSUE TITLE
Migrate docs from Docz to Docusaurus

### ISSUE THREAD

**Issue by sisp** [xaviergonz/mobx-keystone#341]
The docs are currently based on [Docz](https://www.docz.site/) which is lightweight, quite flexible, and based on Gatsby :+1:. However, I'm thinking it might be nice to switch to [Docusaurus](https://docusaurus.io/) for a couple of reasons:

- Docusaurus sites are really beautiful by default! :heart_eyes:
- Easy theming, e.g. color adjustments according to the project's brand
- Light/Dark mode out of the box
- Full-text [search](https://docusaurus.io/docs/search) (via a search service or also with a local index)
- Site navigation sidebar available out of the box which helps with quick navigation to sections
- Built-in support for [explicit heading IDs](https://docusaurus.io/docs/markdown-features/headings#explicit-ids), e.g. for linking to a section on a page like [https://mobx-keystone.js.org/snapshots#onsnapshot](https://mobx-keystone.js.org/snapshots#onsnapshott-extends-objectobj-t----t-listener-sn-snapshotoutoft-prevsn-snapshotoutoft--void---void) where the auto-generated ID is ugly
- MDX (like Docz)
- Widely-used, e.g. [Create React App](https://create-react-app.dev/), [MobX](https://mobx.js.org/), [mobx-state-tree](https://mobx-state-tree.js.org/intro/welcome), [Immer](https://immerjs.github.io/immer/), ...

What do you think?

**Comment by xaviergonz** [comment]
I'd love to, however I haven't been able to find the time for the migration so any help with this would be greatly appreciated
