### ISSUE TITLE
Generic models error: "No base constructor has the specified number of type arguments. ts(2508)"

### ISSUE THREAD

**Issue by sisp** [xaviergonz/mobx-keystone#358]
I've stumbled over a TS typing issue related to generic models where I am getting the error

> No base constructor has the specified number of type arguments. ts(2508)

on the `Model(...)` call. I've isolated the problem to the following reduced example:

```ts
type ValueType = number | string

class Value<T extends DataType> extends Model(<T extends DataType>() => ({
  data: prop<T>(),
}))<T> {}

class Container<V extends Value<T>, T extends DataType> extends Model(< // <--- ERROR
  V extends Value<T>,
  T extends DataType
>() => ({
  value: prop<V>(),
}))<V, T> {}
```

It doesn't seem to be caused by:
- more than one generic type parameter (because there's a [test with two type parameters](https://github.com/xaviergonz/mobx-keystone/blob/5351b7980f50948173cab5210fe24c070e370e18/packages/lib/test/model/subclassing.test.ts#L676-L696) that succeeds)
- simple dependence of one type parameter on another one because the following (replacing `Value<T>` by `Record<string, T>`) works:
  ```ts
  type DataType = number | string

  class Container<V extends Record<string, T>, T extends DataType> extends Model(<
    V extends Record<string, T>,
    T extends DataType
  >() => ({
    value: prop<V>(),
  }))<V, T> {}
  ```

So it looks like it's caused by the dependence of one type parameter on another _that extends a generic model_. This is as far as I've been able to narrow it down. I'm just not sure yet how to fix it. Any help is much appreciated. :pray:

**Comment by xaviergonz** [comment]
To be honest, I have no clue how to fix it. There's a workaround if you don't need a custom value type though:

```ts
class Container<V extends Value<T>, T extends DataType> extends Model(<
  T extends DataType
>() => ({
  value: prop<ValueType<T>>(),
}))<T> {}
```

**Comment by xaviergonz** [comment]
or maybe you could use a factor function instead...

**Comment by xaviergonz** [comment]
Another workaround which adds a getter to type the prop properly

```ts
  type DataType = number | string

  class Value<T extends DataType> extends Model(<T extends DataType>() => ({
    data: prop<T>(),
  }))<T> {}

  class Container<V extends Value<T>, T extends DataType> extends Model(<T extends DataType>() => ({
    value: prop<Value<T>>(),
  }))<T> {
    get valueProperlyTyped() {
      return this.value as V
    }
  }

```

**Comment by xaviergonz** [comment]
As a side note, if TS were to allow the usage of types in base expressions all of this would be so much easier

**Comment by sisp** [comment]
Remember when we were discussing about generic models and [I came up with this one trick](https://github.com/xaviergonz/mobx-keystone/issues/239#issuecomment-830773925) that you made work in this library in the end? When I use the same simplified mock of `Model` and `prop` and copy the example from above in the TS Playground there, there's no typing error :thinking:: [TS Playground](https://www.typescriptlang.org/play?#code/PTAEHEFMDtIJwJYGNQCICCrQGdKQLbagAuA9qAEaShyQCOArgrQCailyiQA2uJAFtVrEGcWGySlo2YnAZIynAO5SA5MUrUA5jHjIAUADMG0BQimgAsqRY8APOi4APYjBZFYAN3gAaUACVnV2h3AMhJOBY7GURoLT8AQ2gATwA+VIAKQ2gALlAMgDoihLgtbDz0AG0AXQBKUABeVIDavIBvUFglDNaA0ABfUDb9UBpIETFOhm5uUASiJOT9fv0jEzMLAAc4Uk27ABVM3v2hkbGJ6CmZuYWU5dXiZM3qADUE7gZIfafqBqn8KicAA+OFkCDiqyQ3HmRDeH0gByCblh70+32ezUgLmRVhsPAyiKxwVCcLRPyOjWaGWGoxYCWICTy212ByOPmWtVqrKGK30UJhoAAwlIGeD4HYXkiQij4ay-CciTjSV9yVLQtZbNwCWdJYrpaBlXKzgrsfrlejIPoKU18jTQJ5UZAmTs9i82RyuS95c02v0gA)

**Comment by xaviergonz** [comment]
I looked into it further and found the issue. Should be fixed in 0.64.1

**Comment by sisp** [comment]
Awesome, that indeed fixes the test case I provided. :tada:

However, my actual use case has prop setters and when I modify the reduced example by adding a setter in the `Value` model

```diff
- data: prop<T>(),
+ data: prop<T>().withSetter(),
```

then the error shows up again. Do you happen to know how to solve this, too? :pray:

**Comment by xaviergonz** [comment]
Ok, that one I'm afraid I'm really lost. My hunch is that it has something to do with the contravariance of setter functions (https://docs.microsoft.com/en-us/dotnet/standard/generics/covariance-and-contravariance). It seems that defining the setter manually works though as a workaround.

**Comment by xaviergonz** [comment]
Also your particular example can be written as

```ts
  type DataType = number | string

  @model("issue #358/2/Value")
  class Value<T extends DataType> extends Model(<T extends DataType>() => ({
    data: prop<T>().withSetter(),
  }))<T> {}

  @model("issue #358/2/Container")
  class Container<V extends Value<any>> extends Model(<
    V extends Value<DataType>
  >() => ({
    value: prop<V>(),
  }))<V> {}

  const c = new Container<Value<number>>({
    value: new Value<number>({
      data: 1,
    }),
  })

  assert(c.value, _ as Value<number>)
  assert(c.value.data, _ as number)
```

**Comment by sisp** [comment]
> It seems that defining the setter manually works though as a workaround.

You're right, I hadn't tried that. Thanks!

> Ok, that one I'm afraid I'm really lost.

No worries then since a manually defines setter works. But thank you very much for trying and having found a fix for the typing error without a generated setter. I'll close the issue because I think it's sufficiently resolved.

> Also your particular example can be written as [...]

I'll need to try to transfer it to the real case, not sure yet. Thanks for the suggestion!
