### ISSUE TITLE
How to donate?

### ISSUE THREAD

**Issue by dodas** [xaviergonz/mobx-keystone#362]
Hey good folks!

Once again, want to say thanks for this great project. I feel like it is greatly under-appreciated and deserves more attention and support.

Is there a way people can support this project and its development?

**Comment by sisp** [comment]
Duplicate of #137 and #163.

But I fully agree with:
> I feel like it is greatly under-appreciated and deserves more attention and support.

👍

**Comment by xaviergonz** [comment]
Spreading the word / adding it to whatever open source list of state libs is the best way to contribute :)

(Closing because it is a dupe btw, but thanks!)
