### ISSUE TITLE
Builtin prop transform for BigInt

### ISSUE THREAD

**Issue by sisp** [xaviergonz/mobx-keystone#363]
[BigInt](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt) is a useful alternative to `number` for representing (large) integers and has [good browser compatibility](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt#browser_compatibility) these days. However, there is no JSON representation for BigInt, so it needs to be encoded, e.g. as a string.

I think it would be nice to have a builtin prop transform for BigInt. It might not be overly difficult to implement a custom prop transform for it, but since BigInt is a native data type, I think it would be a nice feature of the library to have first-class support for it. I suggest to encode BigInt as a string of digits with a trailing `n`, e.g. `12345n`.

What do you think?

**Comment by xaviergonz** [comment]
I think it might be useful. why add the trailing "n" though? since it would need to be implemented as a property transform (because there's no other way for the engine to know it is a big int instead of a string otherwise (unless it is wrapped in an object with a model type or somesuch), the "n" shouldn't be needed

**Comment by sisp** [comment]
The two thoughts I had were better readability of the encoded representation (it would be clearer that string is an encoded big int) and possibility to adapt a JSON decoder to decode such string as a big int without requiring a data schema. But none of the those aspects are actually required for supporting big int in this library. I'd be fine encoding it without the trailing "n" if you prefer it this way.
