### ISSUE TITLE
onAttachedToRootStore cause maximum call stack size exceeded

### ISSUE THREAD

**Issue by quolpr** [xaviergonz/mobx-keystone#384]
Here is the example: 

https://codesandbox.io/s/on-attached-to-root-store-maximum-stack-exceeded-ik096?file=/src/index.ts:341-362

But if you will comment the `onAttachedToRootStore` method — an exception will not be raised

**Comment by xaviergonz** [comment]
Thanks, should be fixed now in v0.65.0. Feel free to reopen if it still happens!
