### ISSUE TITLE
Model data syntax

### ISSUE THREAD

**Issue by Maaartinus** [xaviergonz/mobx-keystone#39]
I'm a very new to this project and I love pretty everything, except for one thing: the two syntaxes for model data. I prefer to use the one providing optional type-checking (as it may get useful when things break and I have no clue what's going on), but it's pretty verbose. It's more verbose than with MST and that's IMHO a big drawback.

I guess, plain `done: false` can't work, but couldn't there be just `done: tProp(false)` instead of `done: tProp(types.boolean, false)`?

Am I right, you're using the simpler syntax? I guess, with lots of experience, relying on typescript is pretty safe...

**Comment by xaviergonz** [comment]
So you want something like this?

```
tProp(false) => tProp(types.boolean, false)
tProp("hi") => tProp(types.string, "hi")
tProp(5) => tProp(types.number, 5)
```

**Comment by Maaartinus** [comment]
I want the best possible syntax possible.... and I guess, more can't be done. So many thanks (for this and for the whole wonderful project) and closing for now.

**Comment by xaviergonz** [comment]
I was also thinking about supporting these, but I'm not sure how useful they'd be:

```
[A, B, C] => types.or(A, B, C)
Boolean => types.boolean
Number => types.number
String => types.String
null => types.null
undefined => types.undefined

tProp([String, null], null) => tProp(types.or(types.string, types.null), null) => tProp(types.maybeNull(types.string), null)

tProp([String, undefined]) => tProp(types.or(types.string, types.undefined)) => tProp(types.maybe(types.string))

```

**Comment by Maaartinus** [comment]
This sure makes sense, though the arrays feels hacky. At the same time, they feel redundant as e.g., with `tProp([String, null], null)` you specify `null` twice.

I've got some ideas, which don't fit nicely together, but maybe someone can make more sense of it:
```
tProp([Boolean, "whatever"])
=> tProp(types.or(types.string, types.boolean), "whatever")
```
where I'm not sure whether I like it. The rules would be
- use wrapper types (Boolean, Number and String) for primitives without specifying a default
- use boolean, number and string values for primitives with a default
- allow only the last type to specify a default (normally, I'd suggest the first one, but that'd would be confusing given that "old" way uses the second argument)

So we could have
```
tProp([String, 42])
=> tProp(types.or(types.string, types.number), 42)

tProp([String, Number])
=> tProp(types.or(types.string, types.number))
```

It feels better than using `maybe` or `maybeNull` or both, but it can get confusing sometimes:
```
tProp([String, null])
=> tProp(types.or(types.string, types.null), null) // as null comes last, it provides a default

tProp([null, String])
=> tProp(types.or(types.null, types.string)) // as String comes last, there's no default
```

Things like `tProp(["", 41])` should be forbidden as it looks like providing two defaults and (due to the third rule) the only possible meaning is the same as for `tProp([String, 41])` and you should use the latter directly.
