### ISSUE TITLE
Batching actions

### ISSUE THREAD

**Issue by terrysahaidak** [xaviergonz/mobx-keystone#40]
I'm not sure if I've just missed something in mobx docs.

I have several cases where I might do something like this:

```ts
@model('SomeModelCollection')
class SomeModelCollectionModel extends Model({
	collection: prop(() => objectMap<SomeModel>()),
}) {
	@modelAction
	add(id: string, model: SomeModel) {
		// some additional logic
		this.collection.set(id, model);
	}
}

// some reaction
reaction(() => rootStore.entities.someModel.collection.values(), () => console.log('Reaction');

// somewhere in my code
const arr: ISomeModel[] = ... // array with models
const collection = getRoot(this).entities[collectionName];

// will it be batched?
arr.forEach(modelPayload => {
	const model = new SomeModel(modelPayload);
	collection.add(model.id, model);
});
```

I'm curious will my `forEach` block trigger a single reaction call and/or snapshot? Since each `collection.add` call is the model action call and I'm changing the `values` of the map.

**Comment by xaviergonz** [comment]
In theory it should batch AFAIK, since it executes inside the same acttion

**Comment by xaviergonz** [comment]
Well actually you should probably wrap the array for each with a mobx action / runInAction

**Comment by xaviergonz** [comment]
Summarizing, changes will batch as long as they are inside action, runInAction, reaction effect, modelAction or modelFlow

**Comment by terrysahaidak** [comment]
Cool, I will reopen it if I find a case where it's not, thank you!

**Comment by vojto** [comment]
> Summarizing, changes will batch as long as they are inside action, runInAction, reaction effect, modelAction or modelFlow

Are you sure about this? I'm trying to do something like this:

```typescript
@modelFlow
applyChanges = _async(function* (this: NoteStore) {
  console.log('pushing note1')
  const note1 = Note.build({title: 'note1'})
  this.notes.push(note1)

  yield* _await(delay(50))

  console.log('pushing note2')
  const note2 = Note.build({title: 'note2'})
  this.notes.push(note2)

  console.log('all pushed!')
})
```

Then, I have this observer watching for changes of notes:


```typescript
autorun(() => {
  console.log(`current notes count: ${this.notes.length}`)
})
```

The observer is getting called after each note is added. Isn't it supposed to be called once after entire `modelFlow` is finished?

**Comment by xaviergonz** [comment]
in model flows batches are done between yield and yield

**Comment by vojto** [comment]
Oh. Is there any way to get it to execute an entire flow like that in one batch?

**Comment by xaviergonz** [comment]
mobx only supports sync batches, so no. your best bet would be to delay all state mutations at the end of the flow

**Comment by vojto** [comment]
Sorry to bother you again, but I have one more question:

What's the use of `modelFlow` if it doesn't really batch updates? You could just create async function on your model and use await, and it would be the same, no?

**Comment by xaviergonz** [comment]
the reason is the same than why mobx flow exists 
https://www.mobxjs.com/best/actions.html
