### ISSUE TITLE
Define an abstract model prop

### ISSUE THREAD

**Issue by dodas** [xaviergonz/mobx-keystone#434]
I have an abstract base class that defines common props/methods and want to define an `abstract` prop that needs to be defined on all extended models:
```ts
export abstract class MyModelBase extends Model({
  commonProp: prop<string>().withSetter(),
}) {
  abstract get abstractCommonProp(): string;
  abstract set abstractCommonProp(val: string);
}

@model("MyModel")
export class MyModel extends ExtendedModel(MyModelBase, {
  customProp: prop<string>().withSetter(),
  abstractCommonProp: prop<"abc" | "cba">().withSetter(),
}) {}
```
the above code works fine in regard to types, but throws when creating an instance of `MyModel`:
```
TypeError: Cannot set property valuePlain of [object Object] which has only a getter
```

Seems like this could be solved with generics, but that makes the code quite a bit more complicated.
Could we make this work on runtime and allow such usage?

Thanks!

**Comment by xaviergonz** [comment]
That code you pasted works for me using tsc, babel and swc (since the abstract get/set compiles in runtime to nothing at all)

**Comment by dodas** [comment]
I don't really know what I was doing. It indeed works. 🤦 
Sorry for wasting your time.
