### ISSUE TITLE
Deep observe changes through references ?

### ISSUE THREAD

**Issue by gbcreation** [xaviergonz/mobx-keystone#436]
Take for example those two models A and B, with A having a property to an instance of B, and an `onPatches()` listener on the instance of A:

```javascript
@model("A")
class A extends Model({ b: prop<B>() }) {}

@model("B")
class B extends Model({ name: prop<string>() }) {
    @modelAction
    setName(name) { this.name = name }
}

const b = new B({ name: 'Tom' })
const a = new A({ b: B })
onPatches(a, patches => console.log(patches))
b.setName('John') // <= onPatches reacts
```

Now, with model A having a reference to model B:

```javascript
@model("A")
class A extends Model({ b: prop<Ref<B>>() }) {}

// Model B unchanged

const b = new B({ name: 'Tom' })
const a = new A({ b: rootRefFactory(B) })
onPatches(a, patches => console.log(patches))
b.setName('John') // <= onPatches DOES NOT react
```

Is it possible to deep observe changes in a tree containing references ?

**Comment by xaviergonz** [comment]
you'd need to also listen for patches to the "real" parents of where the references are, since a reference is kind of like a "portal" to another branch of the model tree

**Comment by gbcreation** [comment]
OK, thank you for your answer.
