### ISSUE TITLE
[Doc] Possible ways to detect changes ?

### ISSUE THREAD

**Issue by gbcreation** [xaviergonz/mobx-keystone#438]
In the [Patches overview documentation](https://mobx-keystone.js.org/patches#overview), we can read:

> As seen in the previous snapshots section, any change made to a tree node will generate a new snapshot, but this is only one of the three possible ways mobx-keystone offers to detect changes. The second way is "patches".

So the first two ways to detect changes are snapshots and patches. Could you please indicate what is the third way?

**Comment by xaviergonz** [comment]
a typo, it should say two ways

**Comment by gbcreation** [comment]
Thanks for your reply. I created a small PR to fix this.
