### ISSUE TITLE
tProp(maybeNull(array))) not working after 0.63.2 

### ISSUE THREAD

**Issue by Amareis** [xaviergonz/mobx-keystone#445]
https://codesandbox.io/s/mobx-keystone-test-forked-hlz1k9?file=/src/index.ts

Works if change keystone version to 0.63.2 or early, so 0.64.0 broke something, I think it's related to this part of changelog:

>When tProp is used instead of prop then $modelType won't be needed in input model snapshot for that particular property. As a side effect, $modelType is now marked as optional in types. Note that for this to work for a root model instead of a sub-property you will need to use the new fromSnapshot overload that takes a type as first argument. For untyped compatibility reasons, getSnapshot will still return $modelType even for typed models.

**Comment by xaviergonz** [comment]
Thanks, should be fixed now in v0.67.3

**Comment by Amareis** [comment]
Yep, fixed in my case now! Thank you
