### ISSUE TITLE
Snapshots of tProp(array) incorrect as of v0.67

### ISSUE THREAD

**Issue by aplum** [xaviergonz/mobx-keystone#447]
https://codesandbox.io/s/mobx-keystone-test-forked-qxmvxz?file=/src/index.ts

Hi! I encountered this bug when rewriting a small app from MST, and thought I was doing something terribly wrong 😅

As of v0.67, snapshots of models using `tProp(types.array(...))` are not correct (I think they're just outdated). This can be fixed by either using `prop` instead of `tProp`, or downgrading to v0.66. I haven't tested if this affects any other types.

**Comment by xaviergonz** [comment]
Thanks for the reproduction! I'll look into it

**Comment by xaviergonz** [comment]
Try v0.67.4

**Comment by aplum** [comment]
v0.67.4 seems to work! Tested in both the codesandbox repro and my app. Thanks! (For both this very quick fix, and the library itself 🙂)
