### ISSUE TITLE
`$modelType` is still required for ref snapshots

### ISSUE THREAD

**Issue by aplum** [xaviergonz/mobx-keystone#448]
https://codesandbox.io/s/mobx-keystone-ref-snapshot-with-modeltype-rcv41t?file=/src/index.ts

Not sure if this is a bug, usage error, or working as intended: despite [this change](https://github.com/xaviergonz/mobx-keystone/pull/334) in v0.64, it looks like `$modelType` is still required for input snapshots of refs.

**Comment by xaviergonz** [comment]
Could you try v0.67.5?

**Comment by aplum** [comment]
Seems to be fixed in v0.67.5 (tested in codesandbox and my app). Thanks again 🙂
