### ISSUE TITLE
Error when undoing `array.replace(...)`

### ISSUE THREAD

**Issue by aplum** [xaviergonz/mobx-keystone#449]
https://codesandbox.io/s/mobx-keystone-undo-reorder-array-ghrrnp?file=/src/index.ts

After using `.replace()` to reorder an array (as used in [mobx-utils `moveItem`](https://github.com/mobxjs/mobx-utils/blob/f4e2cc8caa08c9559f113deb991546984948029a/src/array.ts#L41)), undoing with UndoManager will throw the error "an object cannot be assigned a new parent when it already has one". Using a different method to reorder the array (e.g. remove and reinsert element) works fine with undo, but I'm not sure if that could lead to other issues while the element is temporarily removed from the tree.

**Comment by xaviergonz** [comment]
That's because they operate internally different:
- the splice version removes the first item and then places it between index 0 and 1, which means no values live twice in the tree at the same time

- the replace version does this:
  - const [one, two] = array
  - array[0] = two // at this point two is in two places of the tree at the same time, [0] and [1]
  - array[1] = one

> but I'm not sure if that could lead to other issues while the element is temporarily removed from the tree.

That should be ok (although it depends on if you use attach events on those or not, since they might fire)

**Comment by xaviergonz** [comment]
That being said I just noticed sort would have the same problem, so I'll take a look.

**Comment by xaviergonz** [comment]
Ok, it actually was a bug, so should be fixed in v0.68.3 :)

**Comment by aplum** [comment]
Thanks! Looks like the issue's fixed with v0.68.3 in both codesandbox and my app.

Before I close this one though, I'd like to bring in some more context and get your thoughts. The solution you implemented is probably the best for this library, but please bear with me for a moment 🙂.

You fixed the issue in [this commit](https://github.com/xaviergonz/mobx-keystone/commit/47de6f739a780816958b688ff44a093ef2636eff) by switching from generating `replace` patches for each affected index, to `remove` & `add` patches for each affected index.

I wrote an app with mobx-state-tree (which I plan to switch to mobx-keystone in the next couple weeks) and also ran into issues with moving items in an array & undo. Any implementation had issues, but for comparison's sake let's use mobx-util's `moveItem()` (i.e. using `.replace()`; sorting would probably also have the same issues).

In MST, calling `array.replace(...)` generates `remove` & `add` patches for every index (not just the affected ones, as in mobx-keystone) (see [MST #1530](https://github.com/mobxjs/mobx-state-tree/issues/1530)). I'm using `safeReference` in some of my models, which per [the docs](https://mobx-state-tree.js.org/concepts/references) will set the model's property to undefined once the target node becomes invalidated. Putting that together: when undoing a `moveItem()`, the `remove` patches would be processed and any safeReferences to items in the array would be set to undefined, then the `add` patches are processed but references will remain set to undefined.

My workaround in MST was to use `undoManager.withoutUndo(() => moveItem(...))`, and manually add an undo state with a `replace` patch for the entire array.

<details>
<summary>Click to show full implementation of workaround:</summary>

```typescript
import {
  getPath,
  getSnapshot,
  IAnyType,
  IArrayType,
  IJsonPatch,
  IMSTArray,
  IStateTreeNode,
} from 'mobx-state-tree';
import { moveItem } from 'mobx-utils';

import { undoManager } from './path/to/undo-manager-instance';

function getReplacePatch(node: MstArray): IJsonPatch {
  return {
    op: 'replace',
    path: getPath(node),
    value: getSnapshot(node),
  };
}

type MstArray = IMSTArray<IAnyType> & IStateTreeNode<IArrayType<IAnyType>>; // Probably not the right way to define this but 🤷‍♂️.

/** Note that this adds its own UndoState (i.e. undo/redo might not behave correctly if this is used as part of a larger action). */
export function moveItem_withHackForUndo(
  mstArr: MstArray,
  fromIndex: number,
  toIndex: number,
) {
  const inversePatches = [getReplacePatch(mstArr)];
  undoManager.withoutUndo(() => moveItem(mstArr, fromIndex, toIndex));
  const patches = [getReplacePatch(mstArr)];
  undoManager.addUndoState({ patches, inversePatches });
}
```
</details>

So, my questions about the current fix in v0.68.3:
1. Could some references in mobx-keystone suffer the same issue where these `remove` patches cause the reference to be set to undefined/deleted/whatever? In particular, is the reference in [this example](https://mobx-keystone.js.org/references#example-reference-to-single-selected-todo) with `if (oldTodo && !newTodo) detach(ref)` similar to an MST safeReference, and would it have this issue?
2. In [MST #1530](https://github.com/mobxjs/mobx-state-tree/issues/1530), the `remove` & `add` patches cause performance issues for some people, vs the smaller patch size when using `replace`; mobx-keystone would probably fare better since it's only generating patches for the affected indices, but if question `1` is an issue anyway: would a single `replace` patch for the entire array throw "an object cannot be assigned a new parent when it already has one"? If not, would that maybe perform better on average vs `remove` & `add`? (Obviously it would perform worse when e.g. swapping indices n and n+1 in a large array.)

**Comment by aplum** [comment]
Looks like my concerns in question 1 are unfounded 🙂. Here's a test case to prove it: https://codesandbox.io/s/mobx-keystone-undo-sort-array-with-refs-0h2ymp?file=/src/index.ts

With this bug fixed and `attachedState` in UndoManager for my router state, implementing undo/redo with mobx-keystone removes ~150 lines of hacky code that was necessary with mobx-state-tree. I only wish I'd chosen mobx-keystone from the beginning!

**Comment by PEZO19** [comment]
@aplum Regarding https://github.com/xaviergonz/mobx-keystone/issues/449#issuecomment-1115461076

Have you find the answer for that? Now that I have seen that array.replace+sort+UndoManager has issues in MST (see the reference just above this comment) now I am wondering about Keystone.

>  would a single replace patch for the entire array throw "an object cannot be assigned a new parent when it already has one"? If not, would that maybe perform better on average vs remove & add? (Obviously it would perform worse when e.g. swapping indices n and n+1 in a large array.)

**Comment by aplum** [comment]
@PEZO19 I didn't look into it at all. I was just bringing up some context and issues from what I'd seen with MST for @xaviergonz to consider (which he probably had already). Since it was just about performance optimization, and I had no issues there with mobx-keystone, there was no reason to investigate.

Why are you wondering about that, anyway? As it stands, mobx-keystone should handle array.replace+sort+UndoManager without any issues.

**Comment by PEZO19** [comment]
@aplum I feel like there might be cases, where `remove` + `add` ops just too slow and `replace` op "must" be used. At least the way mentioned here: https://github.com/mobxjs/mobx-state-tree/issues/1530#issuecomment-721080899.

I am only at design phase of my app, but there might be multiple (many?!) lists with 10-20k elements and therefore I am interested in deeply understanding the limitations of any `replace` op based solution. Damn, I miss an `insert` op. :)

**Comment by aplum** [comment]
@PEZO19 Might I suggest making a codesandbox to try testing the performance? (And sharing your findings here 😉.)

**Comment by PEZO19** [comment]
@aplum Okay, if I'll go down that route, I'll try to come back and report on it, however I think I have to go on another route. I do not want to go off-topic much, just to give a bit of context for explanation.

My concern is not solely about in-memory performance, but "over the wire" sync perf too, eg. syncing ordering of elements in SQLite tables + in-memory arrays. "Replace" or "add"+"delete" approaches both have much redundancy for that (for **many huge** arrays). For sync, I'd like use an "insert (path, idx, [data])" patch instead standard JSON Patches supported by keystone.

**Comment by PEZO19** [comment]
@aplum Okay, if I'll go down that route, I'll try to come back and report on it.

**Comment by aplum** [comment]
@PEZO19 (responding to the comment you deleted re performance over the wire) Perhaps sending actions over the wire instead of patches ([onActionMiddleware](https://mobx-keystone.js.org/action-middlewares/on-action-middleware)) could help with that part of the issue?
