### ISSUE TITLE
Is there a simpler version of resolveId<ModelType>(id: string)? (gets from modelCacheMap rather than walk the tree)

### ISSUE THREAD

**Issue by cpakken** [xaviergonz/mobx-keystone#450]
I'm wondering why `resolveId` is implemented this way

https://github.com/xaviergonz/mobx-keystone/blob/96074166c2e9e36f1373646200f678b6e6141a4e/packages/lib/src/ref/core.ts#L169L181

It seems that it walks the tree starting from root and checks each path until it finds the id.

Since every model has a unique id, I assumed that every time a new model is added to the tree, it stores it into a global cache 
`Map<string, Model>`, and is deleted when the model is detached from the tree

Is there a function that resolves the id  like `const resolveId = modelCacheMap.get(id)`

**Comment by cpakken** [comment]
Sorry, I'm being dumb. That implementation is an obvious memory leak if its ancestor is detached instead. Please delete this issue.

**Comment by xaviergonz** [comment]
If you are concerned about performance issues don't be, it is a "computed" walk tree, so only parts of the tree that change will be "re-walked" whenever they change, not everytime you try to resolve a ref.
