### ISSUE TITLE
`fromSnapshot` error with optional non-primitive `tProp`s

### ISSUE THREAD

**Issue by aplum** [xaviergonz/mobx-keystone#454]
https://codesandbox.io/s/mobx-keystone-fromsnapshot-with-optional-non-primitive-tprop-074su6?file=/src/index.ts

`fromSnapshot` throws an error for models with optional non-primitive `tProp`s if that prop is omitted from the snapshot. There's no error if it's defined with `prop`.

**Comment by xaviergonz** [comment]
Thanks for the report! should be fixed in v0.68.5

**Comment by aplum** [comment]
v0.68.5 seems to fix it. Thanks!

I also have a somewhat-related question: why is the `idProp` prop required when calling `fromSnapshot`? The error message makes it seem like this is the expected behaviour, but TypeScript shows it as optional, and of course it's optional in `new MyModel({})`. Generating the id manually is easy enough in my case, but the difference here between `new` and `fromSnapshot` seems inconsistent (perhaps I just haven't thought about the problem enough though 🙂). Repro: comment out `id: "todo2"` in the above codesandbox.

**Comment by xaviergonz** [comment]
Because new is used to create a new instance (and therefore usually will have a new id) and fromSnapshot to deserialize a previously serialized and existing instance (which should have been created with new at some point and therefore should include an id).

**Comment by aplum** [comment]
That makes sense. I mostly run into this when creating data for testing (I find fromSnapshot less verbose for larger, nested models), and that code's usually temporary and infrequently written, so it's not that much friction anyway. Thanks again 🙂
