### ISSUE TITLE
Is there a way to make a change without generating additional patches?

### ISSUE THREAD

**Issue by zachdaniel** [xaviergonz/mobx-keystone#455]
We are working on something that has "preview" logic, and so you can over over a button and see what it will look like before you press the button. What we're looking for is some way to have a model action that *doesn't* emit new patches, and/or some way to add metadata to certain patches that they should be ignored. Any tips would be greatly appreciated!

**Comment by zachdaniel** [comment]
The more I think about it, the more I think that being able to set metadata on the patches is preferable to not emitting them.

**Comment by sisp** [comment]
I'm not sure if I understand your "preview" use case correctly, but could a [sandbox](https://mobx-keystone.js.org/sandboxes) help?

**Comment by zachdaniel** [comment]
Sandboxes *might* work for us. 

The preview use case is like "change this button to blue" and right now we are just changing the button to blue by setting it directly into the state tree, but we have a patch listener that is reacting to that change and we only want it to fire when they "accept" the change. 

Sandboxing sounds like a similar  concept, although it may be very difficult to work into the current structure, since we'd probably want to put some part of the subtree into "sandbox mode" i.e any changes are still reflected in the UI, but *not* sent back to the server. But ideally, we'd actually send the patches back but with some kind of metadata not to persist the change.

**Comment by sisp** [comment]
Ah, then I _think_ [drafts](https://mobx-keystone.js.org/drafts) could help. What do you think?

**Comment by zachdaniel** [comment]
I think I very clearly need to RTFM :) 

Thank you for your time!

**Comment by sisp** [comment]
No worries, I hope drafts solve your problem. Feel free to reopen the issue if none of the features work for you.
