### ISSUE TITLE
`applySnapshot` emits patches for unchanged refs in arrays

### ISSUE THREAD

**Issue by aplum** [xaviergonz/mobx-keystone#456]
https://codesandbox.io/s/mobx-keystone-applysnapshot-emits-patches-for-unchanged-refs-hteerf?file=/src/index.ts

When using `applySnapshot` on a model with an array of refs, patches are emitted for the refs even when they're unchanged. Refs that are direct properties of a model do not have patches emitted. I haven't tested this with any other data structure.

I noticed this because I have a "cancel" button that applies a snapshot that was taken upon opening a modal form, and this cancel button creates an unexpected undo event which effectively does nothing. So, not that big of a problem, but it might confuse users wondering what their "undo" did.

**Comment by xaviergonz** [comment]
Thanks, should be fixed now in v0.68.6

**Comment by aplum** [comment]
v0.68.6 seems to fix it, thanks!
