### ISSUE TITLE
Diffing models to create a patch

### ISSUE THREAD

**Issue by kcoop** [xaviergonz/mobx-keystone#457]
Hello, 

Is there an existing way to create a Patch from a diff of two models (or snapshots)? 

Or alternatively generate a Patch from a dirty draft?

I’m thinking worst case I could use jsondiffpatch against two snapshots, but wonder about the compatibility applying the result  later against a model.

**Comment by xaviergonz** [comment]
You could set up a patch listener over `draft(originalData).data`
It should provide you with all patches that are being done over the draft as they get made.

**Comment by xaviergonz** [comment]
Alternatively you could create a model from snapshot A, set up the patch listener over model A and then use applySnapshot over model A with snapshot B.
That way you can record patches between A and B

**Comment by kcoop** [comment]
Thanks, @xaviergonz. I'll see about using that second suggestion, hadn't considered listening for patches while applying a snapshot, nice idea.

While I'm here, just want to say, from what I've experienced so far of this library, excellent work! In evaluating reactive data management approaches recently, I was excited to discover MST and all its great ideas, but have been continually frustrated by the contortions required working with Typescript. You've fixed those nicely - I'm scratching my head at the TS compiler's messages much less often, and my converted code is much clearer and more concise. You've also added several other useful features that anticipated my needs, like drafts.

**Comment by xaviergonz** [comment]
Thanks! @sisp is the guy who came up with the draft idea and implementation though 😉

**Comment by xaviergonz** [comment]
If I did I'm pretty sure it was your idea though 😅

**Comment by sisp** [comment]
That might be right. 👍 Just checked the [draft history](https://github.com/xaviergonz/mobx-keystone/commits/master/packages/lib/src/treeUtils/draft.ts), all commits are yours. But we were working on the draft and sandbox (initially called "draft middleware") features in parallel. And the two do share some concepts.

In any case, just trying to make sure I don't take credit four _your_ work. 😉

**Comment by sisp** [comment]
> You've also added several other useful features that anticipated my needs, like drafts.

While at it, I imagine the value of [contexts](https://mobx-keystone.js.org/contexts) is easily underestimated. Without contexts but too many `getParent`s etc.: tight coupling, poor testability. But with contexts: less coupling, nice testability. 🎉

**Comment by kcoop** [comment]
Coming back to add this in case anyone could use some code. 

```typescript
import { applySnapshot, fromSnapshot, Patch, patchRecorder, SnapshotOutOf } from 'mobx-keystone';

export const diffSnapshots = <T extends object>(oldSnap: SnapshotOutOf<T>, newSnap: SnapshotOutOf<T>) => {
  const oldClone = fromSnapshot(oldSnap);
  const patches: Patch[] = [];
  const recorder = patchRecorder(oldClone, {
    onPatches: (newPatches: Patch[]) => {
      patches.push(...newPatches);
    }
  });
  applySnapshot(oldClone, newSnap);
  recorder.dispose();
  return patches;
};
```

**Comment by sisp** [comment]
Nice, thanks for sharing!

Just to make it a little more robust and prevent any chance of a memory leak, you might want to use a try-finally block:

```ts
try {
  applySnapshot(oldClone, newSnap);
} finally {
  recorder.dispose();
}
```

Not sure if `applySnapshot` could throw an exception here, but this way you're on the safe side.
