### ISSUE TITLE
Associating metadata with Model properties for runtime reflection?

### ISSUE THREAD

**Issue by kcoop** [xaviergonz/mobx-keystone#460]
Given a property name for a given model, I'm needing a mechanism to extract custom defined information about its associated property. I want, for example, to be able to associate custom formatter functions with different props, or to be able to mark a prop as required.

I could build a look aside table, but mobx-keystone's runtime types seem well suited to this, and it'd be nice to have everything about a prop be defined in a single place. I'm wondering if a) there's already existing code for looking up the type of a prop, and b), whether there's a way to add a generic data value to any runtime prop?

**Comment by kcoop** [comment]
Ah, think I see how this could work, using composition, i.e. create a new `TypeInfo` and have it wrap an existing type, like `types.refinement` does.

And it looks like the mechanism in [typeCheck() ](https://github.com/xaviergonz/mobx-keystone/blob/f6ccf252190c4d2fb63e2b9ce1e68aa3515cc3c9/packages/lib/src/model/BaseModel.ts#L114) could be used to get the typeInfo:
```typescript
    const modelType = typesModel<this>(this.constructor as any)
   ...
```
but `typesModel()` isn't exported, so no joy. Seems like adding something like `Model.getTypeInfo(propKey: string)` would be a useful public function. Happy to create a pull request if you think this is the right approach.

**Comment by kcoop** [comment]
Aha, looks like I can do this:

```typescript
@model('MyModel')
class MyModel extends Model({
  aPropValue: tProp(types.string, '')
}) {}

const type = types.model(MyModel);
const modelTypeInfo = getTypeInfo(type) as ModelTypeInfo;
const propTypeInfo = modelTypeInfo.props.aPropValue.typeInfo;
```

**Comment by xaviergonz** [comment]
Yes, that's the right way to get the type info out of a model.

Why do you wanna avoid your own system to get custom data?

```
const customData = new WeakMap();

@model('MyModel')
class MyModel extends Model({
  aPropValue: tProp(types.string, '')
}) {}

customData.set(MyModel, {
  aPropValue: "beautiful"
})

const m = new MyModel(...)

customData.get(m.constructor) // { aPropValue: ... }
```

you could even type a setCustomData/getCustomData so it only accepts valid prop Names and so they do the m.constructor part auto if needed

**Comment by kcoop** [comment]
Yes, not a terrible alternative, it's just that there's something nice about declaring everything about a prop in a single place.  Same reason decorators are nice, more readable, fewer footguns. 

Especially since you have a nice design for runtime property reflection. I don't really need the runtime type checking, but would certainly use it for custom reflection.

I'm considering something like this right now:

```typescript
const labeledStringType = (displayName: string) => {
  return types.annotation<{displayName: string}>(types.string, {displayName});
}

@model('MyModel')
class MyModel extends Model({
  myProp: tProp(labeledStringType('A Full Display Name'), '')
}) {}
```
It looks like some of the types creation API isn't exported though, so I may not be able to build this with vanilla mobx-keystone. Would `types.annotation` be of interest as a pull request if it turns out to be straightforward, or alternatively exposing the necessary types functions for external extensibility?

**Comment by kcoop** [comment]
I've created a pull request for this for your consideration: https://github.com/xaviergonz/mobx-keystone/pull/461

As a final pitch, I should add the broader reason for the interest. A big frustration with Typescript has been that it doesn't provide runtime reflection, which can be a powerful tool. This library is very close to providing the missing piece for data, since it offers a schema at runtime.

Prop type annotations would help bridge this gap, and open many doors for metaprogramming. And while reflection hasn't really been emphasized (other than type checking), it seems consistent with the rest of the library's philosophy.

**Comment by xaviergonz** [comment]
And thanks for MVVM :) I used it when I used to work with WPF ;)

**Comment by kcoop** [comment]
Excellent, thanks for the responsiveness on this. 

And you're welcome :-) (though I can't take all the credit).

**Comment by kcoop** [comment]
Coming back to say I no longer think this is a good approach for the scenarios I originally envisioned. It involved tightly coupling model declaration with view related behavior, which is poor practice.

Since mobx-keystone provides unique type naming, a better approach is to use prop type discovery to acquire a type id, and then use that to map any view related attributes elsewhere.

I imagine there are still model-specific use cases for prop tags. If anyone has any suggestions for those, I'm happy to update the doc example to reflect a more appropriate usage.
