### ISSUE TITLE
Recommended way to react to a model’s prop change?

### ISSUE THREAD

**Issue by kcoop** [xaviergonz/mobx-keystone#462]
I’m looking to execute some code in response to a model’s property, in this case from within a method in the model’s class. I tried using mobx’s `observe()` with no luck, and then came across this issue suggesting it’s not supported:

https://github.com/xaviergonz/mobx-keystone/issues/282

The solution suggested there seemed pretty heavyweight and awkward for what I imagine is a common scenario. 

Doing the work in a wrapping setter action is dangerous, since directly setting the prop from another action could bypass it.

Is there a cleaner way to do this? Almost seems like a bug not to support `observe()`?

**Comment by xaviergonz** [comment]
Even the mobx creator himself recommends to use reaction rather than observe:

https://mobx.js.org/intercept-and-observe.html

> Warning: intercept and observe are low level utilities, and should not be needed in practice. Use some form of [reaction](https://mobx.js.org/reactions.html) instead, as observe doesn't respect transactions and doesn't support deep observing of changes. Using these utilities is an anti-pattern. If you intend to get access to the old and new value using observe, use [reaction](https://mobx.js.org/reactions.html#reaction) instead. ⚠️

If you want to react to a primitive (e.g. a number) change you can just do

```
reaction(() => myModel.someNumber, (number) => {
  // the number changed, do something
});
```

Or if you want to react to a change of an object reference
```
reaction(() => myModel.array, (newArray) => {
  // the array REFERENCE changed
})
```

The getSnapshot trick is only needed when you want to react to an object and/or anything deeply inside it:
```
reaction(() => getSnapshot(myModel), () => {
  // myModel or anything deeply inside it changed
})
```

Note that all of this is more related to mobx than to mobx-keystone itself:
https://mobx.js.org/reactions.html

**Comment by kcoop** [comment]
Ah, excellent. Didn't realize I could use `reaction()`, and also that I could get the previous value of the property with that approach. Thanks, will use that.

Also, worth mentioning, continuing to enjoy this library. It's been joyfully easy to do testing.

**Comment by xaviergonz** [comment]
Actually you can even use useEffect in react if you use mobx-react and observer if you prefer the "reaction" to run in your components.

```
const MyComponent = observer(({myModel}) => {
  useEffect(() => {
    // this will run when myModel.someNumber changes
  }, [myModel.someNumber])
})
```

**Comment by kcoop** [comment]
Thanks. That makes sense for UI presentation, was looking more for something in the model domain (maintaining a registry based on a prop change). `reaction()` is perfect.
