### ISSUE TITLE
Error deserialising call to set array when replacing an element

### ISSUE THREAD

**Issue by andyshand** [xaviergonz/mobx-keystone#465]
I'm trying to figure out whether I'm misunderstanding something conceptually here or this is an error, I would appreciate any help.

I've adapted the code form the client/server example on the site. I make changes on the server-side only and am sending the serialised actions to the client. 

I'm using `applySerializedActionAndTrackNewModelIds` on the server and it's sister fn `syncNewModelIds` on the client, as suggested in the docs.

Here is an abridged version of my model:
```typescript
@model('korus/Mod')
export class Mod extends Model({
  name: prop<string>('').withSetter(),
  id: idProp,
  // ...other fields 
}) {}

@model('korus/ModsState')
export class ModsState extends Model({
  mods: tProp(types.array(types.model(Mod)), () => []).withSetter()
}) {}
```

If I change the `mods` array using its setter on the server (`setMods([...]`), the action arrives on the client. The JSON seems to look ok, but I get the following error when applying the action:

```
Error: object at path ["mods",17] with ids [null,"temp1"] could not be resolved
```

Where `temp1` is an id in the array that no longer exists at position 17, it's now `temp2`, since the element has been replaced. All other unchanged elements of the array work fine, it's this specific changed element that causes the error.

Am I using the library wrong here? I assumed the point of the `idProp` was to identify each element and whether it had been moved/added/removed etc.

But this error is making me question this assumption. I can give more information if needs be, but I feel I'm probably misunderstanding something here and I can't find it in the docs anywhere.

Thanks!

**Comment by xaviergonz** [comment]
could you please create a code sandbox that exhibits the problem?

**Comment by xaviergonz** [comment]
@andyshand

**Comment by andyshand** [comment]
Hi! Thanks for the reply, after a little more trial and error I figured it out, sorry for the hassle.

I changed my server -> client action forwarding to be triggered `onStart` rather than `onFinish`. Seems to be working ok now. :)
