### ISSUE TITLE
[docs] Scroll in docs isn't working on Android (chrome)

### ISSUE THREAD

**Issue by terrysahaidak** [xaviergonz/mobx-keystone#47]
How to reproduce: Open docs in chrome on Android, try to scroll

For example, this link: https://mobx-keystone.js.org/runtimeTypeChecking

**Comment by xaviergonz** [comment]
It's a known bug of docz, it should be solved in v2 but it's still on beta

**Comment by xaviergonz** [comment]
Now using docz 2,seems solved
