### ISSUE TITLE
Model constructor type doesn't line up with ModelCreationData when using transforms

### ISSUE THREAD

**Issue by evelant** [xaviergonz/mobx-keystone#471]
When using an object of type `ModelCreationData<MyModel>` to construct a model there is a typescript error if any of the model's props are using transforms. Example:

```typescript
@model("MyModel")
export class MyModel extends Model({
    myMap: tProp(t.record(t.string), () => ({})).withTransform(objectToMapTransform()),
}) {}

const data: ModelCreationData<MyModel> = { myMap: { foo: "bar" } }

//error 
const m = new MyModel(data)
```

```
TS2345: Argument of type 
'{ myMap: { [key: string]: string; }; }' is not assignable to parameter of type 'ModelPropsToTransformedCreationData<{ myMap: ModelProp<{ [k: string]: string; }, { [k: string]: string; } | null | undefined, Map<string, string>, Map<string, string> | null | undefined, never, false, never, never, never>; }>'.  

 Type '{ myMap: { [key: string]: string; }; }' is not assignable to type 
'{ myMap?: Map<string, string> | null | undefined; }'.    

 Types of property 'myMap' are incompatible.       

Type '{ [key: string]: string; }' is missing the following properties from type 'Map<string, string>': clear, delete, forEach, get, and 8 more
```

This is really just a minor inconvenience since I can always manually create the transformed types before creation but it does add some annoying boilerplate and is unexpected behavior per the docs on `ModelCreationData`

**Comment by xaviergonz** [comment]
## 0.69.3

- `ModelData` and `ModelCreationData` now take into account any possible transformations. If you want to use the old ones (without transformations) then use `ModelUntransformedData` and `ModelUntransformedCreationData`.

**Comment by evelant** [comment]
Thanks for the quick patch! My example above is still an error on 0.69.3, is this intended?
```
@model("MyModel")
export class MyModel extends Model({
    myMap: tProp(t.record(t.string), () => ({})).withTransform(objectToMapTransform()),
}) {}

// TS2322: Type '{ foo: string; }' is not assignable to type 'Map<string, string>'.   
// Object literal may only specify known properties, and 'foo' does not exist in type 'Map<string, string>'.
const data: ModelCreationData<MyModel> = { myMap: { foo: "bar" } }


const m = new MyModel(data)
```

This is effectively the same behavior as before the patch, transformed props must be converted to their transformed type before creating a model. 

Is that the intended behavior or should the constructor accept the untransformed prop as input?

**Comment by xaviergonz** [comment]
that's intended, if you want to use the snapshot type to create a model instance then probably you want to use `fromSnapshot / SnapshotInOf<M>`
