### ISSUE TITLE
typesTag wrapper check func captures wrong 'this'

### ISSUE THREAD

**Issue by kcoop** [xaviergonz/mobx-keystone#478]
Version 0.69.5 uncovered a bug in the `typesTag`: the baseChecker's check function was assigned directly rather than being wrapped within another function, which caused an endlessly recursive call to the check function from within itself because it captures `this` (i.e. `this.check()` invokes `_check()`, which is `this.check()`, which invokes `_check()`...).

I've created a pull request with the fix: https://github.com/xaviergonz/mobx-keystone/pull/477

**Comment by xaviergonz** [comment]
Thanks! merged and released as v0.69.6
