### ISSUE TITLE
How to set the type of idProp?

### ISSUE THREAD

**Issue by fineup** [xaviergonz/mobx-keystone#482]
After customizing the id according to the method of  [Setting an ID property](https://mobx-keystone.js.org/class-models/#setting-an-id-property), the similar default returned under typescript is string. How to specify the type, such as `Custom-${string}`

**Comment by xaviergonz** [comment]
`idProp.typedAs<T>()` added in v1.1.0

unit test
```ts
test("idProp.typedAs", () => {
  type Id = `custom-${string}`
  @testModel("M")
  class M extends Model({
    id: idProp.typedAs<Id>(),
  }) {}

  const m = new M({ id: "custom-1" })
  assert(m.id, _ as Id)
  assert(_ as SnapshotInOf<M>["id"], _ as Id | undefined)
  assert(_ as SnapshotOutOf<M>["id"], _ as Id)
  assert(m.$modelId, _ as Id)
})
```

**Comment by xaviergonz** [comment]
Closing since it now should be supported as shown above.
