### ISSUE TITLE
Common design patterns

### ISSUE THREAD

**Issue by sisp** [xaviergonz/mobx-keystone#5]
I think it would be nice to have a section about common design patterns in the documentation. A few patterns that have come to my mind and which I'd like to discuss/verify in the process are:

- Testable design of models, especially for models that require access to other parts of the tree using `findParent` etc. (#8)
- References across arbitrary tree branches using a "registry" (similar to MST's [`IdentifierCache`](https://github.com/mobxjs/mobx-state-tree/blob/master/packages/mobx-state-tree/src/core/node/identifier-cache.ts)) at the root of the tree (#7)
- Backreferences that give a referenced object access to its referencers/consumers (#6)
- Polymorphic collections and abstract base classes/models (e.g. adding a symbol to the base class when `instanceof` is not possible because the base class is created in a factory)
- ...

@xaviergonz What do you think?

**Comment by xaviergonz** [comment]
Sounds great :D Is there any you'd like to discuss first in particular?

**Comment by sisp** [comment]
I actually have all these issues at the moment. :-D I'll just pick one to start with if that's okay for you.

Should we discuss each design pattern in its own issue to keep the different discussions separate?

**Comment by xaviergonz** [comment]
Yeah, better keep them separated

**Comment by xaviergonz** [comment]
Closing since separate issues have been created
