### ISSUE TITLE
Upgraded mobx-keystone seeing a hasOwn error.

### ISSUE THREAD

**Issue by maccman** [xaviergonz/mobx-keystone#502]
![screencapture-reflect-64-sentry-io-issues-3983325115-2023-03-09-07_25_49](https://user-images.githubusercontent.com/2142/224009657-20309ab6-1b71-4bbd-a4a6-e61058630506.png)

**Comment by xaviergonz** [comment]
hasown was added in chrome 93 that user is using Chrome 88. can you polyfill it?

**Comment by maccman** [comment]
Ah - silly me - sorry for bugging you.
