### ISSUE TITLE
Incorrect `this` scope depending how modelAction is passed into a component

### ISSUE THREAD

**Issue by aroth** [xaviergonz/mobx-keystone#506]
I'm new to `mobx-keystone` and am facing a problem when passing a modelAction as a prop into a component.  

### ProfileModalStore.js
```
import {model, Model, modelAction, prop, onSnapshot} from 'mobx-keystone';

@model('Persona/ProfileModalStore')
class ProfileModalStore extends Model({
    showToggle: prop<boolean>(false).withSetter(),
}) {
    @modelAction
    toggleModalVisibility() {
        if (!this.setShowToggle) {
            console.log('`this` is not an instance of `ProfileModalStore`..', this.showToggle);
        } else {
            console.log('this is an instance of `ProfileModalStore`, scope is correct, behaving as expected')
            this.setShowToggle(!this.showToggle);
        }

}
export default ProfileModalStore;
```

### Screen.js
```
import {useStores} from 'stores';

const Screen = () => {
    const {profileModalStore} = useStores();
    return ( 
       <View>
         <Button onPress={toggleModalVisibility} title="This doesn't work" />
         <Button onPress={profileModalStore.toggleModalVisibility} title="This doesn't work" />
         <Button onPress={() => toggleModalVisibility()} title="This doesn't work" />

         <Button onPress={() => ProfileModalStore.toggleModalVisibility()} title="This DOES work" />
      </View>
    )
}
```

Tapping the first three buttons will call `toggleModalVisibility()` in `ProfileModalStore`, but `this` isn't the expected instance of `ProfileModalStore`.  Instead, it appears to be the global window object... thus, `this.showToggle` is undefined. How is this even possible? 

Tapping the last button also calls `toggleModalVisibility()`, but then behaves as expected because `this` is right.

---

I'm confused as to what exactly is going on here. I would expect all four buttons to behave the same.

**Comment by xaviergonz** [comment]
that's Javascript for you 

https://www.freecodecamp.org/news/this-is-why-we-need-to-bind-event-handlers-in-class-components-in-react-f7ea1a6f93eb/

**Comment by aroth** [comment]
@xaviergonz ah, of course.  Bit by this again. Thank you.
