### ISSUE TITLE
How to Limit Undo Levels with undoMiddleware in mobx-keystone?

### ISSUE THREAD

**Issue by wangzhewudiya** [xaviergonz/mobx-keystone#509]
I am writing to inquire about the undoMiddleware feature in your library. Specifically, I am wondering how to limit the number of undo levels that are available.

Could you please provide guidance on how to limit the number of undo levels using the undoMiddleware feature? I am having difficulty finding information on this in the documentation and would appreciate any assistance you can provide.

Thank you for your time and for your work on this valuable library.

**Comment by xaviergonz** [comment]
just don't call undo() when undoLevels is more than X

**Comment by xaviergonz** [comment]
I just released 1.5.0 with maxUndoLevels/maxRedoLevels options for undoMiddleware
