### ISSUE TITLE
Tooling, devtools support

### ISSUE THREAD

**Issue by PEZO19** [xaviergonz/mobx-keystone#510]
@xaviergonz 
Hi there! Awesome work, congrats!

Trying to choose between MST/Keystone, one missing thing to me seems is Mobx-devtools / Reactotron (as mentioned [on SO](https://stackoverflow.com/a/68820888)).

From the keystone docs/github repo it is not clear to me which is supported by now or what are the alternatives, what/how big are the disadvantages? Can you please help out?

**Comment by xaviergonz** [comment]
You can actually use the redux devtools with it
https://mobx-keystone.js.org/redux-compatibility#connectreduxdevtools
https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd?hl=en

**Comment by PEZO19** [comment]
@xaviergonz Makes sense! :) What about a React Native environment? how do you think it compares to Redux-devtools? (I mean features/gotchas/stability-wise.)

**Comment by xaviergonz** [comment]
No idea, I've never used reactotron
