### ISSUE TITLE
Keystone types supporting `onActionMiddleware`

### ISSUE THREAD

**Issue by PEZO19** [xaviergonz/mobx-keystone#518]
If we use keystone's `ObjectMap` which is a built-in wrapper, it seems easy to listen to it's methods with `onActionMiddleware`, because they are `@modelAction`s.

Is there a similar / easy way to do that with arrays/objects or I have to create my own wrapper to "lift" them to "keystone world"? If so, may I ask why ObjectMap has been created, but Array/Object were not?

**Comment by xaviergonz** [comment]
ObjectMap was created as a map alike wrapper around arrays/objects because objects and arrays are supported by JSON and maps are not.

In the end, to support serialization + json patches etc, everything has to be serialized into a JSON compatible snapshot.

**Comment by xaviergonz** [comment]
Btw, arrays and objects do have standard actions if you don't want to "wrap" them:

https://mobx-keystone.js.org/standard-and-standalone-actions#standard-actions

**Comment by PEZO19** [comment]
Thanks a lot, all my questions were answered.
