### ISSUE TITLE
Is it valid to start actions in onActionMiddleware's onStart/onFinish?

### ISSUE THREAD

**Issue by PEZO19** [xaviergonz/mobx-keystone#519]
The rationale is to keep multiple (huge) collections consistent / in sync, without the need to recalculate the derived from scratch.

Eg. if I `set` an ObjectMap's key to 10, I'd like to subscribe to this `set` `modelAction` via `onActionMiddleware` and automatically `set` (with fast mutation, instead mobx-ish "pure recalculation") another ObjectMap's same key based on a mapper function (x=>2*x) to 20. I want them to happen in same transaction.

I assume it is not a good idea to inject such "business logic"(?) in the middleware layer, but I can not think of any other way to do it in a reactive (and not passive) way in keystone. (Mobx has observe, but it does not respect transactions and keystone onPatches only run at the end of the transactions if I am right, which is "too late" to keep data consistent that way.)

**Comment by xaviergonz** [comment]
another alternative would be to mark the mapped object as "dirty" and make the mapped object recalculate on "get" if dirty is true

**Comment by PEZO19** [comment]
@xaviergonz Regarding https://github.com/xaviergonz/mobx-keystone/issues/519#issuecomment-1588177147:

My point is to have the freedom to eliminate "recalculation" (from scratch). I am totally fine if 95% of my app works with recalculation (it's easier to reason about + simpler code), but that 5% must rely on deep observation and listening to deep changes and propagating these deep changes solely.

As `onPatches` does not work inside a transaction, my attempts was to treat actions like these changes events which "needs to be propagated". For that, I'd need the freedom to nest "onAction"s as part of that, to emit new actions. 

Just and idea: it would be nice if we could insert a callback (eg used with standaloneAction) before and especially after an action. So, beyond `onStart` and `onFinish` there could be a `beforeStartStandaloneAction` and `afterFinishStandaloneAction`, respecting the boundaries. 

However it would be also interesting something like `afterStartStandaloneAction` and `beforeFinishStandaloneAction` which could be ("pseudo")children actions of the target action.
