### ISSUE TITLE
Not able to access static methods of parent class from child class when inheriting with generic types. 

### ISSUE THREAD

**Issue by Hemant11111** [xaviergonz/mobx-keystone#525]
Not able to access static methods of the parent class from the child class when inheriting with generic types. 

```
@model('ChildModel')
export class ChildModel extends ExtendedModel(() => ({
    baseModel: modelClass<ParentModel<ChildModel>>(ParentModel),
    props: {
        name: prop<string>()
    }
})) {}
```

```
@model('ParentModel')
export class ParentModel<T> extends Model(<T>() => ({
    id: prop<string>()
}))<T> {

    @modelAction
    static doSomething(id: string) {
        // TODO
    }

}

```

While trying to pass generic types I am not able to call `doSomething` on ChildModel. Typescript gives the error `Property 'doSomething' does not exist on type 'typeof ChildModel'.ts(2339)` 

However, if I don't use Generics:

```
@model('ChildModel')
export class ChildModel extends ExtendedModel(ParentModel, {
        name: prop<string>(),
    }
) {
}
```

It works fine and can access `doSomething` on ChildModel. (ChildModel.doSomething())

**Comment by xaviergonz** [comment]
I've been looking into it, but unfortunately I can't fix it. As soon as I add any extra static property the trick that makes generic works breaks badly and there seems to be no way in TS to do so (or at least I can't find any). :(

I recommend to either call the static using ParentModel.doSomething() or just move doSomething out of the class itself.
