### ISSUE TITLE
Should BaseModel::getRefId return this.$modelId by default?

### ISSUE THREAD

**Issue by sisp** [xaviergonz/mobx-keystone#53]
Since #50 and #51, does it make sense to let `BaseModel::getRefId` return `this.$modelId` by default?

**Comment by xaviergonz** [comment]
I guess it does :)

**Comment by xaviergonz** [comment]
Done in https://github.com/xaviergonz/mobx-keystone/pull/54

**Comment by Maaartinus** [comment]
The next question is when it makes sense to return anything else. ATM I can't see any reason how having two IDs could be better (but I'm rather a noob in this area and my imagination is limited).

**Comment by xaviergonz** [comment]
I guess in case your snapshot includes another kind of ID coming from backend for example and you want to use that one
