### ISSUE TITLE
onInit does not execute from static creation method

### ISSUE THREAD

**Issue by aboyer1013** [xaviergonz/mobx-keystone#541]
I want to create some factories around my models. This is how I typically do it, but `onInit` doesn't fire when instantiated this way. What am I missing?

Excerpt from [Code Sandbox](https://codesandbox.io/p/sandbox/reverent-elion-2pq6gg?file=%2Fsrc%2FModel.ts%3A13%2C35)

```typescript
import { prop, objectMap, Model, idProp, model } from "mobx-keystone";

@model(`MyModel`)
export class MyModel extends Model({
  id: idProp,
  name: prop<string>(),
}) {
  onInit() {
    console.log(`init ${this.name}`);
  }

  static create(modelData: any) {
    return new MyModel(modelData);
  }
}

const foo = new MyModel({ name: "foo" }); // logs "init foo"
const bar = MyModel.create({ name: "bar" }); // no log
```

**Comment by xaviergonz** [comment]
are you using babel transpiration by any chance? if so try to move the create function outside the class, there's a bug in a babel decorator plugin that makes references to the same class within static classes actually reference the undecorated class

**Comment by xaviergonz** [comment]
related issue https://github.com/xaviergonz/mobx-keystone/issues/122

**Comment by aboyer1013** [comment]
@xaviergonz Sorry for the duplicate issue. Thanks for helping. As an alternative, do you see anything wrong with calling `onInit()` manually?

```typescript
static create(modelData: any) {
    const result = new MyModel(modelData);
    result.onInit();
    return result;
  }
```
