### ISSUE TITLE
Ref::id vs. Ref::$modelId

### ISSUE THREAD

**Issue by sisp** [xaviergonz/mobx-keystone#55]
Since #50, I think `Ref::id` and `Ref::$modelId` are redundant. Should `Ref::id` be made a computed property that returns `this.$modelId`? Or should `Ref::id` perhaps be removed entirely?

**Comment by xaviergonz** [comment]
Aren't they different? Ref.$modelId is the ID of the ref object itself, while id is the ID of the target (probably should have been named targetId) .

**Comment by sisp** [comment]
Ah, yes, you're right, my bad.
