### ISSUE TITLE
tcProp confusion

### ISSUE THREAD

**Issue by Maaartinus** [xaviergonz/mobx-keystone#58]
All examples in `tProp.ts` mention `tcProp`, which IIUIC doesn't exist (I guess, it's how `tProp` used to be called earlier).

---

Another thing: There's a `tProp` overload stating that "You should only use this with primitive values and never with object values". As they're just three types useful in this place, would it be possible to split the declaration to cover exactly these types, so that errors like
```
badArray: tProp(types.array(types.string), []), // must be () => []
```
could be avoided?

**Comment by xaviergonz** [comment]
thanks! will be out in 0.26.0

**Comment by xaviergonz** [comment]
out now
