### ISSUE TITLE
Design pattern: backreference

### ISSUE THREAD

**Issue by sisp** [xaviergonz/mobx-keystone#6]
Imagine the following case:

```ts
@model("myApp/A")
class A extends Model({
  b: prop<Ref<B> | undefined>()
}) {}

@model("myApp/B")
class B extends Model({}) {}
```

`A.b` is a reference of `B`, but `B` doesn't know which `A`s reference it.

I see the following options now:

1. Get all instances of `A` from its store(s) and filter those that have `b.current === this`:

    ```ts
    @model("myApp/B")
    class B extends Model({}) {
      @computed
      public get a(): A[] {
        return /* get all instances of A */.filter(a => a.b.current === this)
      }
    }
    ```

    Pros:
    - Computed property, so cannot be outdated
    
    Cons:
    - Recomputes every time *any* instance of `A` changes
    - Needs to iterate over *all* instances of `A` anywhere in the tree (could be many)
    - How to get all instances when there is not a single store for instances of `A`?

2. Set the backreference "manually" from the reference callbacks:

    ```ts
    @model("myApp/B")
    class B extends Model({}) {
      @observable
      public readonly a: A[] = []

      @action
      public addA(a: A): void {
        this.a.push(a)
      }

      @action
      public removeA(a: A): void {
        const index = this.a.indexOf(a)
        if (index !== -1) {
          this.a.splice(index, 1)
        }
      }
    }
    
    const bRef = customRef<B>("myApp/BRef", {
      // ...
      
      onResolvedValueChange(ref, newB, oldB) {
        // Problem: `a` can be undefined, e.g., if `ref` has already been detached.
        const a = findParent(ref, parentNode => parentNode instanceof A)
        if (oldB) {
          oldB.removeA(a)
        }
        if (newB) {
          newB.addA(a)
        }
        if (oldB && !newB) {
          // If the value we were referencing disappeared then remove the reference
          // from its parent.
          detach(ref)
        }
      },
    })
    ```

    Pros:
    - No computed property that needs to iterate over possibly many instances of `A` to filter for the right ones

    Cons:
    - Is there a risk that the backreference gets out of sync because we're managing it manually?
    - The above example doesn't even work because when the reference in `A.b` gets detached, then `a` is `undefined` and we cannot remove it from `B.a`.

Are there other options and what do you think about the ones above?

**Comment by xaviergonz** [comment]
This PR should address this
https://github.com/xaviergonz/mobx-keystone/pull/34

**Comment by xaviergonz** [comment]
Closing as it has been addressed
