### ISSUE TITLE
Hot-reload error: model already exists

### ISSUE THREAD

**Issue by aksonov** [xaviergonz/mobx-keystone#65]
How to prevent such error during hot reload?

![Simulator Screen Shot - iPhone 8 - 2019-11-12 at 15 21 32](https://user-images.githubusercontent.com/1321329/68671334-2ab92f00-0560-11ea-8859-a0839e4c04de.png)

**Comment by xaviergonz** [comment]
it should have been a warning, which you can safely ignore when using hot reloading.
I'll make it a console.warn with a message such as 
```
`a model with name "${name}" already exists (if you are using hot-reloading you may safely ignore this warning)`
```

**Comment by aksonov** [comment]
Hm, as you can see I saw error screen, strange

**Comment by xaviergonz** [comment]
Yes, that's the current behaviour. Try 0.26.6, it should be a warning instead now.

**Comment by xaviergonz** [comment]
Closing since a tentative fix was released and due to inactivity. Feel free to reopen if the issue still persists!
