### ISSUE TITLE
Design pattern: model registry

### ISSUE THREAD

**Issue by sisp** [xaviergonz/mobx-keystone#7]
> References in mobx-state-tree were designed to be transparent to the user. Maybe way too transparent, up to a level where there’s no way, for example, to get the parent of a reference node. In mobx-keystone references are explicit objects, thus making for example this use-case trivial.
>
> Source: "[mobx-keystone, an alternative to mobx-state-tree without some of its pains](https://medium.com/@xaviergonz/mobx-keystone-an-alternative-to-mobx-state-tree-without-some-of-its-pains-8140767a3aa1)"

But how are model instance references resolved in `mobx-keystone` when the model store location is non-trivial to access, e.g. when model instances are not stored in a single model store with a well-known location? MST implements transparent reference resolution by means of the [`IdentifierCache`](https://github.com/mobxjs/mobx-state-tree/blob/master/packages/mobx-state-tree/src/core/node/identifier-cache.ts) which is a fully-managed collection of all model instances within the tree and lives at the root of a tree.

The "[Reference to single selected Todo](https://mobx-keystone.js.org/references#example-reference-to-single-selected-todo)" example does not require a central model instance registry as `selectedRef` lives in `TodoList`, which is the store of all `Todo` items, so the location of `Todo` items for reference resolution is simple. But if `Todo` was referenced from an arbitrary location in the tree and/or there wasn't only a single `Todo` store, I think a `Todo` registry at the root of a tree could be a general pattern to addressing this problem.

```ts
@model('myApp/Todo')
class Todo extends Model({
  id: prop<string>(),
  // ...
}) {
  public onAttachedToRootStore() {
    // find the root model and throw an error if it does not have the expected type
    const root = getRoot(this)
    if (!(root instanceof Root)) {
      throw new Error('Todo expects the root of the tree to be of type Root')
    }
    // add this Todo instance to the registry
    root.todoRegistry.add(this)
    // remove this Todo instance from the registry when it is detached from the tree
    return () => void root.todoRegistry.remove(this)
  }

  // ...
}

const todoRef = customRef<Todo>("myApp/TodoRef", {
  // ...
  resolve(ref) {
    // get the root of the tree
    const root = getRoot(this)
    // if the ref is not yet attached to the root then it cannot be resolved
    if (!(root instanceof Root)) {
      return undefined
    }
    // but if it is attached then try to find it
    return root.todoRegistry.get(ref.id)
  },
  // ...
})

@model('myApp/Root')
class Root extends Model({}) {
  public readonly todoRegistry = new Registry<Todo>()
}

class Registry<T extends { id: string }> {
  private readonly byId = observable.map<string, T>()

  @computed
  public get items(): readonly T[] {
    return values(this.byId) // import { values } from 'mobx'
  }

  @action
  public add(item: T): void {
    this.byId.set(item.id, item)
  }

  @action
  public remove(item: T): void {
    this.byId.delete(item.id)
  }

  public get(id: string): T | undefined {
    return this.byId.get(id)
  }
}
```

@xaviergonz What do you think?

**Comment by terrysahaidak** [comment]
I've been using the Entities store pattern for a while and I like it.

In my current application, there are a lot of places where I can fetch and use the same model, so I'm using a reference to it, of course. Since I'm responsible for my backend architecture, we are building it while keeping in mind the tool we are using for normalization – [normalizr](https://github.com/paularmstrong/normalizr).

Normalizr allows us always to have only references to specific objects, but storing all the data inside the Entities store.

The Entities store looks like this:
```
{
  [entityName: string]: prop<ObjectMap<EntityModel>>()
}
```

In MST I used to use Map, so it gives me all the `set`, `get` and other methods to work with it. Also, the Entities store has `merge` method which accepts `entities` payload normalizr produces for me. Merge automatically stores and merges all the objects it receives.

So every time I'm fetching some data from the server I normalize it using normalizr and merge into the Entities store. Normalizr also gives me all the ids so I assign them where I need to.

There are two problems with that approach:
1. This one does not exist in `mobx-keystone` – getting a parent of a reference itself since the parent in MST will be the Entities model instead of a real model.
2. If you need to get a snapshot of that and store somewhere, you'll need to manually extract and store all the required models in the Entities store since all the real data stores there.

The main benefit of that approach is the fact I always know where specific entity lives.

Also, it gives me the ability to build some sort of wrapper around the entity model – the Collection store.

Collection store has all the methods to fetch specific entities by its id.

**Comment by xaviergonz** [comment]
That seems like an ok solution. 

I think you could also use walkTree and the fact that it is reactive to achieve the same

```ts

test("walktree should be reactive", () => {
  @model("root")
  class Root extends Model({
    children: prop<Child[]>(() => []),
  }) {
    readonly registry = observable.map<string, Child>()

    onInit() {
      autorun(() => {
        const childrenThere = new Set<Child>()
        walkTree(
          this,
          n => {
            if (n instanceof Child) {
              childrenThere.add(n)
            }
          },
          WalkTreeMode.ParentFirst
        )

        // remove/update
        runInAction(() => {
          for (const [id, c] of this.registry.entries()) {
            if (!childrenThere.has(c)) {
              this.registry.delete(id)
            }
          }
          for (const c of childrenThere) {
            this.registry.set(c.id, c)
          }
        })
      })
    }
  }

  @model("child")
  class Child extends Model({
    id: prop<string>(),
  }) {}

  const c1 = new Child({ id: "1" })
  const c2 = new Child({ id: "2" })
  const c3 = new Child({ id: "3" })
  const r = new Root({
    children: [c1, c2, c3],
  })
  expect([...r.registry.entries()]).toEqual([["1", c1], ["2", c2], ["3", c3]])

  detach(c2)

  expect([...r.registry.entries()]).toEqual([["1", c1], ["3", c3]])
})
```

It should be easy to abstract a pattern around that to have a generic registry class that might be used in any model/root model.

**Comment by xaviergonz** [comment]
Here is the abstracted version

```ts
import { autorun, observable, ObservableMap, runInAction } from "mobx"
import { AnyModel, detach, model, Model, prop, walkTree, WalkTreeMode } from "../../src"
import "../commonSetup"

test("walktree should be reactive", () => {
  type Registry<K, V extends object> = ObservableMap<K, V>
  function registry<K, V extends object>(
    root: AnyModel,
    getId: (child: any) => K | undefined
  ): Registry<K, V> {
    const reg = observable.map<K, V>()

    autorun(() => {
      const childrenThere = new Set<V>()
      walkTree(
        root,
        n => {
          const id = getId(n)
          if (id !== undefined) {
            childrenThere.add(n)
          }
        },
        WalkTreeMode.ParentFirst
      )

      // remove/update
      runInAction(() => {
        for (const [id, c] of reg.entries()) {
          if (!childrenThere.has(c)) {
            reg.delete(id)
          }
        }
        for (const c of childrenThere) {
          reg.set(getId(c)!, c)
        }
      })
    })

    return reg
  }

  @model("root")
  class Root extends Model({
    children: prop<Child[]>(() => []),
  }) {
    readonly registry = registry(this, n => {
      if (n instanceof Child) {
        return n.id
      }
      return undefined
    })
  }

  @model("child")
  class Child extends Model({
    id: prop<string>(),
  }) {}

  const c1 = new Child({ id: "1" })
  const c2 = new Child({ id: "2" })
  const c3 = new Child({ id: "3" })
  const r = new Root({
    children: [c1, c2, c3],
  })
  expect([...r.registry.entries()]).toEqual([["1", c1], ["2", c2], ["3", c3]])

  detach(c2)

  expect([...r.registry.entries()]).toEqual([["1", c1], ["3", c3]])
})
```

**Comment by xaviergonz** [comment]
@terrysahaidak you can get the parent of the model a reference is pointing to by using `getParent(someRef.current)` or the parent of the reference by doing `getParent(someRef)`
Usually you will want to pass true as second parameter though so you don't get the '$' middle object in models.

**Comment by xaviergonz** [comment]
Btw, if you think that registry abstraction is worth it then it could be included into the lib after some performance improvements.

**Comment by xaviergonz** [comment]
That being said your approach is indeed faster though.

**Comment by sisp** [comment]
Your `walkTree` approach sounds familiar. @mweststrate [suggested something similar for MST](https://spectrum.chat/mobx-state-tree/general/how-to-get-all-models-by-type~ebc67c35-e5a1-4f88-8274-4aa0a1d01ed4?m=MTU2MzU2MDQzMTExMw==) on Spectrum. Intuitively, it feels a bit expensive though, but I haven't run any benchmark. On the other hand, it seems to be a robust solution.

Another idea that came to my mind: You introduced the concept of a true root store and `onAttachedToRootStore`. In MST, the `IdentifierCache` always lives in the root store, but the root of a tree can change in MST when a subtree gets attached to another tree which makes the root store less predictable from a developer's perspective. mobx-keystone makes the root store more deterministic through `registerRootStore` and my current understanding is that there should only be one root store in a tree (correct?). How about adding a general model registry to the root store when `registerRootStore` is called and removing it again when `unregisterRootStore` is called. It could be a nested map

```ts
Map<string /* collection */, Map<string | number /* identifier */, object>>
```
where `collection` is a user-provided collection identifier (like a database table name), so, e.g., backreferences can be implemented quite efficiently using a computed property (the first approach I sketched in #6) by only filtering the model instances of the relevant collection instead of running a filter over all model instances anywhere in the tree. A model instance would register and unregister itself in `onAttachedToRootStore` using a helper function, e.g.

```ts
registerModel(node: object, id: string | number, collection: string): () => void
```

which returns a callback for unregistering again. If needed, it would also be possible to register a model instance with multiple collections simultaneously. Similarly, there could be a helper function for retrieving a model instance from the registry, e.g. for reference resolution,

```ts
getModel<T extends object = any>(node: object, id: string | number, collection: string): T | undefined
```

and one for getting all model instances of a particular collection.

```ts
getCollection<T extends object = any>(node: object, collection: string): T[] | undefined
```

What do you think @xaviergonz?

**Comment by xaviergonz** [comment]
What if there was an "onChildAttached(child: object, path: string[]): Disposer" hook for models (that would get also get called for the initial children) and that optional returns a disposer when such child becomes detached from the model tree?

That way you wouldn't need to tweak the children in any way and it should be trivial to customize whatever kind of registry you need.

e.g.
```ts
class RootModel .... {
  @observable
  private todosRegistry = new Map<string, Todo>()

  onChildAttached(child, path) {
    if (child instanceof Todo) {
      todosRegistry.set(child.id, child)
      return () => {
        todosRegistry.delete(child.id)
      }
    }

    getTodoById(id: string) { return this.todoRegistry.get(id) }
  }
}
```

once those foundations are in place then it could be thought of what could be a good default and implement it based on those foundations

(I usually like to give a composable option valid for alternative implementations before giving an strict implementation on how to achieve something)

**Comment by xaviergonz** [comment]
For example, maybe you might want to have two set of todos registries, which might share ids. by using the path you could detect that and allow that use case.

**Comment by sisp** [comment]
That's an interesting idea! Can you efficiently detect when a child is attached/detached at an arbitrary path?

Would this approach perhaps also enable a true parent->child dependency to solve the child->parent dependency problem I described in #8? I imagine a child model could implement, e.g., a `setGetValue(get value: () => number): Disposer` method, then a parent can assign a callback during `onChildAttached` (if the child type and path match), and the disposer of `setGetValue` gets called as part of the disposer of `onChildAttached`. Does this make sense? I'm trying to think along the lines of React's compositional nature here.

In any case, I think `onChildAttached` could be a nice general feature for implementing a registry and likely other things, too.

**Comment by xaviergonz** [comment]
Actually yeah, I guess it could serve as some sort of dependency injection system too :)

**Comment by xaviergonz** [comment]
Added `onChildAttachedTo` - https://github.com/xaviergonz/mobx-keystone/pull/16

In the end I went for a functional approach since listening deeply is kind of costly, so it is better to be able to select which part of the children to listen to, and if deeply or shallowly

```ts
onChildAttachedTo(
  target: () => object,
  fn: (child: object) => () => void | void,
  options?: {
    deep?: boolean, 
    fireForCurrentChildren?: boolean 
  }): (runDetachDisposers: boolean) => void
```

Runs a callback everytime a new object is attached to a given node.
The callback can optionally return a disposer which will be run when the child is detached.

The optional options parameter accepts and object with the following options:

- `deep: boolean` (default: `false`) - true if the callback should be run for all children deeply or false if it it should only run for shallow children.
- `fireForCurrentChildren: boolean` (default: `true`) - true if the callback should be immediately called for currently attached children, false if only for future attachments.

Returns a disposer, which has a boolean parameter which should be true if pending detachment callbacks should be run or false otherwise.

**Comment by sisp** [comment]
I've started using `onChildAttachedTo` for creating a model registry and it has worked great so far, much better than my original approach. I'm thinking whether the [new contexts feature](https://github.com/xaviergonz/mobx-keystone/pull/31) may also provide additional convenience in accessing registries at different levels in the tree.

**Comment by xaviergonz** [comment]
I was thinking the same, but still need to figure out how to put all the pieces together. The new "getRefId()" on models is actually a first step towards offering a generic ref registry for those who don't want or need to fiddle up with the custom ones.

**Comment by xaviergonz** [comment]
@sisp 
care to check
https://5d7fe1e537accf0008449dee--mobx-keystone.netlify.com/references
https://github.com/xaviergonz/mobx-keystone/pull/33

to see if it fixes this issue?
might also address backrefs.

**Comment by sisp** [comment]
Yes, this looks great and will simplify reference management quite a bit - especially by making a few registries obsolete that only exist for reference resolution. :-)

How do you envision backrefs to be addressed by root references? This is essentially how I'm computing backreferences right now:

```ts
@model('A')
class A extends Model({ b: prop<Ref<B>>() }) {}

@model('B')
class B extends Model({ ... }) {
  @computed
  public get allA(): A[] {
    return /* get all instances of A */.filter(a => a.b.current === this)
  }
}
```

I have a registry for all instances of `A` and can access it in `B`. How would root references help here?

**Comment by terrysahaidak** [comment]
Backreffing manually is the most annoying thing in MST and would be really cool to have some sort of API in order to handle that in mobx-keystone.

**Comment by xaviergonz** [comment]
Just wondering, do you need to persist the list of references that point to the object or knowing that in runtime would be enough?

**Comment by xaviergonz** [comment]
In other words, would something like ```myRefType. getRefsPointingTo(node) ``` or similar be enough?

**Comment by sisp** [comment]
I don't need to persist the backreferences. `getRefsPointingTo` would be called in a computed getter, I assume, and if this listed needed to be persisted, I imagine it could be done easily using a reaction which updates a prop of `Ref`s.

**Comment by terrysahaidak** [comment]
My use case is something like that:

```ts
@model('Application')
class Application extends Model({}) {
  get post() {
    // how to get the post itself here?
	// getParent will return RootStore here
  }
}

@model('Post')
class Post extends Model({
  application: prop<Ref<Application> | undefined>(),
}) {
  @modelAction
  setApplication(application: Application) {
    this.application = applicationRef(application);
  }
}

@model('RootStore')
class RootStore extends Model({
  applicationCollection: prop(() => objectMap<Application>()),
  posts: prop<Post[]>(() => []),
}) {}
```

**Comment by xaviergonz** [comment]
@terrysahaidak couldn't you just put the posts list under each application in this case?

```ts
@model('Application')
class Application extends Model({
  posts: prop<Post[]>(() => [])
}) {
}

@model('Post')
class Post extends Model({
}) {
}

@model('RootStore')
class RootStore extends Model({
  applicationCollection: prop(() => objectMap<Application>()),
}) {}
```

**Comment by terrysahaidak** [comment]
@xaviergonz, unfortunately, no, it isn't possible because I'm loading posts, then each post may have an application or may not (in some cases it might be loaded separately, in others – with the post). Also, there are several places where I can refer to the same application, so I'm putting them inside the collection (and by the way posts live in the collection map too because there are several places where I can fetch, store and modify the same Post, so I'm using references to them).

But the application itself can interact with the post (some of the APIs requires some of the post props).

**Comment by xaviergonz** [comment]
Ok, so then maybe...

```ts
@model('Application')
class Application extends Model({}) {
  @computed
  get posts() {
    return getRefsResolvingTo(this).filter(ref => getParent(ref) instanceof Post);
}
```
?

**Comment by terrysahaidak** [comment]
will the `getRefsResolvingTo` be walking through the tree and looking for all the refs? If so, would be cool to have something which will return the first possibly one, so it doesn't really need to walk all the tree.

But yeah, that workaround will help.

And I'm pretty sure this will thing be pretty common (at least for me and my use cases)

```ts
getRefsResolvingTo(this)
      .map(ref => getParent(ref))
      .filter(parent instanceof Post);
```

So would be nice to have some sort of util:

```ts
getRefsParentOfType<T extends object = any>(value: object, parent: T) T | undefined;
```

**Comment by sisp** [comment]
> So would be nice to have some sort of util:
> 
> ```ts
> getRefsParentOfType<T extends object = any>(value: object, parent: T): T | undefined;
> ```

IMHO, this is such a simple utility function so I'd say it does not need to be part of `mobx-keystone`. I imagine there may even be variations of this function, e.g. a variant that uses `findParent` rather than `getParent`.

**Comment by xaviergonz** [comment]
Agreed, it is a very simple function to write in its own code if one feels it is needed too.
This PR should address this.
https://github.com/xaviergonz/mobx-keystone/pull/34

@terrysahaidak it won't iterate the whole tree to find back references, it only gets updated when references "find" or "loose" their target.

**Comment by sisp** [comment]
Built-in support for backreferences and reference resolution using root references may alleviate the need for a model registry all together.

**Comment by xaviergonz** [comment]
just released it as 0.20.0, give it a go and let me know :)

**Comment by sisp** [comment]
Will do, may take a couple of days though. Thanks a lot (again) for all the work you're putting into this awesome library!

**Comment by sisp** [comment]
I've started using backrefs and root references and both make my code much cleaner. The registries I created for backrefs and root references are all gone, but I still have a few left for other reasons which looks fine the way it is. Contexts are tremendously helpful.

I think you can close this issue as backrefs and root references solve the problem.

**Comment by xaviergonz** [comment]
Nice! closing these then :)
