### ISSUE TITLE
Lookahead / Testing changes to a tree without actually committing them

### ISSUE THREAD

**Issue by sisp** [xaviergonz/mobx-keystone#73]
I frequently need to test how a change somewhere in the tree affects the rest of the tree. For instance, while editing a text field in a form, I validate the entered value, but the validation routine has (generally speaking) arbitrary dependencies across the tree. In some cases, I don't want the changes to take effect immediately, but I'd rather like to test what the effect would be if the changes were actually applied to the tree.

To achieve this goal, I currently clone the tree, apply the changes to the cloned tree, and check the result. E.g.:

```ts
const rootPath = getRootPath(myModel)
const rootClone = registerRootStore(clone(rootPath.root, { generateNewIds: false }))
const myModelClone = resolvePath<typeof myModel>(rootClone, rootPath.path).value!

// Make changes to `myModelClone`.
// Check result of the changes.

unregisterRootStore(rootClone)
```

While this approach works fine in terms of correctness, I'm faced with performance issues (my tree is not even big at the moment). It seems that `fromSnapshot` is quite expensive which adds up when executing the above snippet many times per second.

I've been thinking about possible solutions:

1. Debounce or throttle execution of the above snippet.
2. Find a way to avoid cloning the entire tree, perhaps using proxies along the lines of Immer drafts.  The idea is to make changes to the proxied tree which behaves as if it was the original tree, but the changes are not actually applied to the original tree. I'm not sure though whether/how this can be done with `mobx`/`mobx-keystone` because class instances may hold references to other class instances and also these references would need to be replaced by proxies, I guess.

@xaviergonz Do you have any experience with this kind of situation and advice how to deal with it?

**Comment by xaviergonz** [comment]
What is the usual case, that the change is accepted or that it is rejected?

If it is usually accepted then it should be much faster to get a snapshot before the change, apply the change directly, and if the validation fails then restore the backup.

Another possibility is having two copies of the tree, the "final" tree (for UI) and the "draft" tree (to test stuff and apply actions over).

In this case, if you add "onPatches" to the draft tree (where actions are applied), after a patch is generated you could do some checks, if checks are ok you can apply that patch to the final (UI) tree, and if they are not you can apply the inverse patch on draft to restore it.

If you want even more performance you might even do that on a single tree, but that means you could end up with a "invalid" state very momentarily before it is restored.

**Comment by sisp** [comment]
> What is the usual case, that the change is accepted or that it is rejected?

It depends. When I test form input, I'd say the changes are more likely to be accepted. There is another part of my app though where changes are always rejected because I'm merely checking validity of performing certain actions that are associated with DOM elements and depending on the outcome of the checks the DOM elements are rendered differently.

> If it is usually accepted then it should be much faster to get a snapshot before the change, apply the change directly, and if the validation fails then restore the backup (probably by using applySnapshot instead of fromSnapshot, since applySnapshot does reconciliation of nodes and reuses existing objects if possible). You might even do this process automatic with a custom action middle ware.

This may also cause a momentary "invalid" state before the restoration, wouldn't it?

> Another possibility is having two copies of the tree, the "final" tree (for UI) and the "draft" tree (to test stuff and apply actions over).
>
> In this case, if you add "onPatches" to the draft tree (where actions are applied), after a patch is generated you could do some checks, if checks are ok you can apply that patch to the final (UI) tree, and if they are not you can apply the inverse patch on draft to restore it.

I like this approach and after giving it some initial thought, I imagine it may be possible to create a custom middleware (e.g. `draftMiddleware`) that generalizes this approach, i.e. it maintains a copy of the actual tree, keeps it in sync with the original tree using `onPatches`, and simplifies (a) committing changes made in the draft back to the original tree or (b) rejecting them.

If you're interested, I'd be happy to keep you in the loop about my progress and contribute this middleware back to `mobx-keystone` if it turns out to work the way I'm envisioning it now.

Thank you very much for your valuable advice on this problem! :-)

**Comment by xaviergonz** [comment]
No problem, keep me posted! :)

**Comment by sisp** [comment]
I have created a PR (#77) that adds a "draft middleware".

**Comment by sisp** [comment]
#77 has been merged, so I think this issue can be closed.
