### ISSUE TITLE
Reset function on hot-reloads using filenames

### ISSUE THREAD

**Issue by martinheidegger** [xaviergonz/mobx-keystone#86]
I had a mistake where I accidentally gave the same model name to two classes which worked basically but resulted in a strange error in combination with `fromSnapshot` that loaded the type definition of the _wrong_/unexpected model. Now, that error is fixed I come to think that it showed as the same error message that occurs _naturally_ when using hot-reload in my react-native context: #65 .

What class is used in a hot-reload? Say, some changes happen and I try to restore a Snapshot: will it use the old or new class? What if the signature changed?

My thinking is that mobx-keystone could provide a feature like:

```typescript
import { file } from 'mobx-keystone'

const finish = file(__filename)

@model('MyModel')
class MyModel extends Model({}) {}

finish()
```

If a hot-reload is triggered the all models that were previously declared within __filename are dropped and the instances of those models receive new "prototype's" - hot-reloading.

**Comment by xaviergonz** [comment]
> Now, that error is fixed I come to think that it showed as the same error message that occurs naturally when using hot-reload in my react-native context: #65 .

Makes me wonder if there's a way to detect if a code is running in "fast-reload" mode or not.
If there is then the warning could be transformed into an error when not in fast reload mode and into a warning when it is.

> What class is used in a hot-reload? Say, some changes happen and I try to restore a Snapshot: will it use the old or new class? What if the signature changed?

In theory (if the class changes) new instances created after the reload should use the latest version of classes, while old instances will use the old version of the class.

> My thinking is that mobx-keystone could provide a feature like...

Maybe I´m wrong, but I think that'd mean mobx-keystone would need to keep track of all instances related to a given model class, (Map<class, instance>) which would break automatic garbage collecting.

**Comment by martinheidegger** [comment]
> Makes me wonder if there's a way to detect if a code is running in "fast-reload" mode or not.
If there is then the warning could be transformed into an error when not in fast reload mode and into a warning when it is.

The warning is pretty annoying as well, maybe there is a clean way to deal with this ... 🤔 

> In theory (if the class changes) new instances created after the reload should use the latest version of classes, while old instances will use the old version of the class.
> Maybe I´m wrong, but I think that'd mean mobx-keystone would need to keep track of all instances related to a given model class, (Map<class, instance>) which would break automatic garbage collecting.

You are right, it is a bad idea to do that automatically, however: it might be nice to be able to do it manually.

Thinking out loud here, but what if there was a some kind of "unload" hook that could be triggered?

```typescript
lifecycle(/* init */ () => {
   create applicationRoot = new ApplicationRoot()
   registerRootStore(applicationRoot)
   return /* exit */ () => {
     unregisterRootStore(applicationRoot)
   }
})
```

On the first time that the app is started, it will simply call the init method. When a hot-reload is happening, the returned destructor is called before the next init. This way it would be possible to reload a given model with the latest classes.

**Comment by xaviergonz** [comment]
About the warning, I could easily make it an actual exception (when not in hot reload mode / first time it is loaded) and do not show the warning at all (when in hot reload mode / 2+ time it is reloaded) if hot reloading somehow exposes that data (which it might, but I have no clue, I'd need to investigate first).

On the other hand, I'd rather not tie mobx-keystone to any hot reload solution, since it is supposed to be framework agnostic like mobx is.

For example, the lifecycle method you mention sounds like should be exposed from the hot reload solution itself, not mobx-keystone :-/

**Comment by xaviergonz** [comment]
That being said one thing I can actually (and easily) do is to only show the warning once per model class... I'll add that so it is not sooo annoying :)

**Comment by xaviergonz** [comment]
The "show warning only once" should is out in 0.35.0

**Comment by xaviergonz** [comment]
Closed since the single warning is in place and I'd rather not tie mobx-keystone to specific hot reload implementations
