### ISSUE TITLE
add onJSONPatches

### ISSUE THREAD

**Issue by martinheidegger** [xaviergonz/mobx-keystone#87]
I am using `onPatches` to store the changes in a log. Doing that I need to process the patches to fit the [json patches](http://jsonpatch.com/) standard. Namely: change the path from array to `/` joined and prefixed string. I wonder if its a good idea to add a new "onJSONPatches" api that provides this out-of-the box or alternatively a `.toJSON()` method on `Patch` that would do the same thing?

**Comment by xaviergonz** [comment]
Do you think a conversion function like:
 `function patchToJsonPatch(patch: Patch): JsonPatch`
and its inverse 
`function jsonPatchToPatch(jsonPatch: JsonPatch): Patch`
would be enough?

**Comment by martinheidegger** [comment]
I did implement a poorer version of from/to JSON patch, so the PR is nice! The reason I suggested a `onJSONPatches`, however, was because in my case I don't "need" a Patch and this generates double the amount of objects (not sure how relevant that is)

**Comment by xaviergonz** [comment]
Even if there were a onJSONPatches the internal implementation most probably would still piggyback on the current onPatches + conversion methods (unless lots of changes are made), so in the end there would still be double the amount of objects, just hidden behind the implementation.
