### ISSUE TITLE
Dedicated Patch type for each operation

### ISSUE THREAD

**Issue by martinheidegger** [xaviergonz/mobx-keystone#88]
`fast-json-patch` has [clear type definitions for Patches](https://github.com/Starcounter-Jack/JSON-Patch/blob/53caddfc924aeccdae5146793eaa31562571c11c/module/core.d.ts#L4-L26). Would it be a good idea to replace the current `Patch` interface to look like ↓ ?

```typescript
export declare type Patch = AddOperation<any> | RemoveOperation | ReplaceOperation<any>
export interface BaseOperation {
    path: string[]
}
export interface AddOperation<T> extends BaseOperation {
    op: 'add'
    value: T
}
export interface RemoveOperation extends BaseOperation {
    op: 'remove'
}
export interface ReplaceOperation<T> extends BaseOperation {
    op: 'replace'
    value: T
}
```

**Comment by xaviergonz** [comment]
I don't see why not. however in mobx-keystone case path would be `readonly (string | number)[]`

**Comment by xaviergonz** [comment]
Done in this commit: https://github.com/xaviergonz/mobx-keystone/commit/7ff26354be93b5b5e3796e3a7c1773f3e03c2215

**Comment by martinheidegger** [comment]
Nice !
