### ISSUE TITLE
Retreiving the modelType by class

### ISSUE THREAD

**Issue by martinheidegger** [xaviergonz/mobx-keystone#90]
To avoid mistakes and provide better logging it would be nice if the class instance of Models would have a `$modelType` property and print the output beautifully:

```typescript
@model('com/myModel')
class MyModel extends Model({
 name: prop(() => 'hello')
}) {
  x: number // not-stored-properties not rendered
}

console.log(MyModel.$modelType) // com/myModel
console.log(MyModel)
// [constructor MyModel#com/myModel]

const inst = new MyModel({})
console.log(inst)
// [MyModel#com/myModel$modelId { name: "hello" }]
```

**Comment by xaviergonz** [comment]
Sounds good!

**Comment by xaviergonz** [comment]
In this case I didn't add $modelId to the logging of the instance since it is already present in the snapshot
e.g.

console.log(inst)
// [MyModel#com/myModel { name: "hello",$modelId:"id1",$modelType:"com/myModel" }]
